### ISSUE TITLE
Port forwarding certain web servers from the browser-based editor can result in a 502 error

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vscodespaces#10]
Certain web servers appear to be causing 502 errors with VS Online's browser-based editor.  Here is a simple repro:

1. Create an empty VSOe
2. Open in Browser
3. Open a terminal and install Apache Tomcat by typing:

    ```bash
    curl -o tomcat.zip -SL https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.zip && unzip tomcat.zip && chmod +x apache-tomcat-*/bin/*.sh
    ```
4. Start tomcat by typing:

    ```bash
    apache-tomcat-*/bin/startup.sh
    ````

5. Verify the server responds by typing:

    ```
    curl http://localhost:8080
    ```

5. Forward the port 8080 using the "Environment Details" in in the "Remote Explorer"
6. Right Click => Copy Port URL
7. Open a new tab and paste the URL

**Expected:** You see the default Tomcat server page
**Actual:** 502 error is reported after connecting and the window refreshes.  The tomcat server access logs (under logs in the apache-tomcat folder) do indicate that the server was hit with a 200 response, but the response must have caused a problem.

**Comment by dhruva001** [comment]
Note for anyone trying to run spring boot app. This issue is present with default Tomcat server but not Jetty. So if you run into this issue, switch to Jetty server (https://howtodoinjava.com/spring-boot/configure-jetty-server/).

**Comment by webstermath** [comment]
I am also getting a 502 error after trying to run a react app created by create-react-app.

**Comment by fara-nak** [comment]
Thank you all for reporting, we are aware of this issue and working on improving our overall PortForwarding service. this issue will be resolved as part of the improvement.

**Comment by webstermath** [comment]
> Thank you all for reporting, we are aware of this issue and working on improving our overall PortForwarding service. this issue will be resolved as part of the improvement.

I am glad Microsoft is commited to fixing this issue, but am wondering, roughly, when it might be fixed.  I am very excited to start using vsonline but right now it is a non-starter until there is proper port forwarding.

**Comment by jkeech** [comment]
@webstermath, we don't have an ETA on the new port forwarding service right now, but there is a workaround that you might be able to try in the meantime: If you connect to your VSO environment from VS Code desktop, then full port forwarding works as you would expect. It is only limited in the browser. When running in the desktop version of VS Code, our agent has permissions to listen on a localhost port (which we cannot do in the browser, so we have to rely on the portforwarding service proxy in the browser).

Is it possible to install VS Code on your client machine? If so, feel free to give it a shot by installing the Visual Studio Online extension and connecting.

**Comment by webstermath** [comment]
Thank you for the quick reply.  Unfortunately it is not possible for me to install the desktop version because I develop on a Chromebook.

**Comment by discovrbookings** [comment]
I found that GitPod fixes this issue.

**Comment by lostintangent** [comment]
Closing this as resolved. Please let us know if you're still running into problems. Thanks!
