### ISSUE TITLE
JAVA_HOME should be set appropriately

### ISSUE THREAD

**Issue by brunoborges** [MicrosoftDocs/vscodespaces#102]
JAVA_HOME is required by many VS Code extensions to work properly. Therefore, it should be set automatically in the Linux environment.

**Comment by egamma** [comment]
VS Code Remote supports [remote specific settings](https://code.visualstudio.com/docs/remote/containers#_container-specific-settings). The default values of these settings can be set in the `devcontainer.json` settings section. This is how it is done for the Java dev container definition https://github.com/microsoft/vscode-dev-containers/blob/328d48644e3094eda053f08689f20577d1d6fbda/containers/java-11/.devcontainer/devcontainer.json#L9.

//fyi @lostintangent

**Comment by lostintangent** [comment]
This should now be resolved in the latest base image 👍  // CC @chuxel
