### ISSUE TITLE
Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

### ISSUE THREAD

**Issue by dotnetprofessional** [MicrosoftDocs/vscodespaces#111]
I'm attempting to create a JAVA FRC (First Robotics Competition) project and I'm getting the following error:

Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

Not being a JAVA dev, I'm assuming this means that the env. is setup for JAVA 8 and my project requires JAVA 11 which isn't installed. I couldn't find any docs (honestly the docs are not good) on how you go about installing alternative frameworks or other tooling. Its not clear to me what determines the framework/SDK version that gets installed for a project.

I'll be shutting the ENV down until I can get a resolution on this.

**Comment by jkeech** [comment]
Thanks for the feedback. We are working on improving the docs. This is an area of the docs we definitely need to focus on. Today we provide a base image with many toolsets and SDKs pre-installed, but we realize it won't cover every use case. we need to document what the default image comes with as well as how to install additional tools on top of that.

We are also working on adding support for custom images and Dockerfiles, so you can provide an image with different set of tool pre-installed if the default image doesn't work. Alternatively, once you create an environment, you can always install additional tools. You have full access to the terminal inside VS Code, so if you have a command line install, it should work.

I found these [instructions](https://linuxize.com/post/install-java-on-debian-9/) for OpenJDK 11, which seemed to work when I tried them out in an environment.

```
echo 'deb http://ftp.debian.org/debian stretch-backports main' | sudo tee /etc/apt/sources.list.d/stretch-backports.list
sudo apt update
sudo apt install openjdk-11-jdk -y
```

Then running `java -version` yields
```
vsonline:~/workspace$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-1bpo91)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-1bpo91, mixed mode, sharing)
```

**Comment by dotnetprofessional** [comment]
Appreciate the quick response. I'll try out the command you provided tomorrow. Thanks!

**Comment by lostintangent** [comment]
This should now be resolved in the latest base image 👍 Let us know if you're still running into an issue. Thanks!
