### ISSUE TITLE
Go not installed automatically 

### ISSUE THREAD

**Issue by kunalbabre** [MicrosoftDocs/vscodespaces#114]
I cloned a repo _https://github.com/kedacore/keda_ (written in GO) it created the online instance however environment did not have go installed by default. 

**Error:**
Failed to run "go env" to find GOPATH as the "go" binary cannot be found in either GOROOT(undefined) or PATH(/home/vsonline/.vscode-remote/bin/a14de79ac74f2e0e6566d3cc9410eeb7dc769cde/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/sdks/lts:/opt/python/latest/bin:/opt/yarn/stable/bin:/home/vsonline/.local/bin:/home/vsonline/.npm-global/bin:/opt/oryx:/opt/nodejs/lts/bin:/opt/dotnet/sdks/lts:/opt/python/latest/bin:/opt/yarn/stable/bin:/home/vsonline/.local/bin:/home/vsonline/.npm-global/bin)

**Comment by lostintangent** [comment]
This has now been resolved, since Go is installed in our base image. Let us know if you run into any issues 👍 Thanks!
