### ISSUE TITLE
Switching Between accounts issues

### ISSUE THREAD

**Issue by spdavid** [MicrosoftDocs/vscodespaces#118]
Issue Type: <b>Bug</b>

Open up your environments when logged into an account. 
Log out of the account
Environments under VS Online don't go away
After clicking a few times on create new environment it will finally go away
Login into another account opens browser and when i log in, visual studio code does not get the new account logged in. 
I must restart vscode in and log in with the new account in order for it to work. 

A small issue but but can be annoying with people who use multiple accounts (aka Consultants)

Extension version: 1.0.1214
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 5.0.0-1023-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.16GB free)|

|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|VS Online: My Environment|
|OS|Linux x64 5.0.0-1023-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (10.00GB free)|
|VM|0%|
</details>

**Comment by lostintangent** [comment]
Closing this as resolved, since we've made numerous changes to our authentication support over the last year. Please re-open this issue if you're continuing to encounter problems here. Thanks!
