### ISSUE TITLE
VS Code's Open Recent menu lists an overly generic name

### ISSUE THREAD

**Issue by jmezach** [MicrosoftDocs/vscodespaces#130]
I recently created my first dev environment on Visual Studio Online. When I was trying to reconnect to it at a later time I noticed this in Visual Studio Code's Open Recent menu:

![Annotation 2019-11-07 233054](https://user-images.githubusercontent.com/1225489/68477503-f119b880-022d-11ea-8b28-8194b157f2b6.png)

This is fairly generic name, so as a user I have no idea which environment I'm going to open now, especially if I have more than one in that list. Of course I could go to the Visual Studio Online action bar and connect to the environment from there, but it would be nice if I could use the Open Recent list to get to the right environment.

**Comment by roblourens** [comment]
@rajkumar42 Somewhere you are probably registering a URI formatter which contributes the "VS Online" name. You can customize that to include the name of the environment. The SSH extension does that to include the name of the SSH remote.

**Comment by lostintangent** [comment]
Closing this as resolved, since the workspace name now includes the name of the repo that you opened. Please re-open this if folks have additional feedback for this area. Thanks!
