### ISSUE TITLE
Sort environments on the web by most recently used

### ISSUE THREAD

**Issue by arjun27** [MicrosoftDocs/vscodespaces#134]
I have 5 environments on my account and they take up a considerable amount of space on the web dashboard. Finding the right environment to connect to takes a split second more than I would like, and sorting would help :)

(There might be a different solution to this problem, just suggesting what would work best for my needs)

**Comment by srivatsn** [comment]
We got feedback earlier that it was hard to understand what the sort order was and so we chose to sort alphabetically to make it deterministic. Maybe we need different sort orders..

**Comment by arjun27** [comment]
Yes, that is a fair criticism. I don't know if we have evaluated list items vs cards to show the environments - since lists can be easier to scan/filter/sort (in my opinion)

**Comment by legomushroom** [comment]
I like both ideas of having the table view of the environments and be able to quickly access the most recently used environments. It could be a switch on top of the envs list that allows you to switch between different sort modes. We can also can think of a pin feature that allows you to pin some environment to the top of the list.

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal. If this is something folks would like to see, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
