### ISSUE TITLE
Introduce a dark theme for the management portal page

### ISSUE THREAD

**Issue by legomushroom** [MicrosoftDocs/vscodespaces#137]
Currently, the VSO Web portal uses mainly the white color, but the environment page (VSCode workbench) is using dark theme by default. When switching between the pages at night makes eyes suffer, we can improve the experience by providing the setting to switch to the dark theme on the VSO management portal by default.

**Comment by bergmeister** [comment]
Yes, please

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal. If this is something folks would like to see, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
