### ISSUE TITLE
Attempting to reconnect while suspending the connected environment

### ISSUE THREAD

**Issue by kumarz** [MicrosoftDocs/vscodespaces#156]
VSonline is attempting to reconnect while suspending the connected environment.

Steps to repro:
1) login to VSO
2) connect to an environment
3) click on the remote explorer icon
4) choose the plan that the environment belongs to
5) click suspend for the environment that is being already connected
6) it will prompt the user to disconnect and suspend.
7) while it is trying to suspend the environment, it tries to reconnect again and again.

![image](https://user-images.githubusercontent.com/22509606/68606266-ee53d900-0462-11ea-9882-7bbce4967cf6.png)

**Comment by lostintangent** [comment]
Closing this as resolved. If folks are still encountering this issue, please let us know. Thanks!
