### ISSUE TITLE
Roaming VS Code Settings

### ISSUE THREAD

**Issue by DanJ210** [MicrosoftDocs/vscodespaces#169]
I'm trying to locate the docs, if any, that explains...

"Visual Studio Online roams your settings, themes, Git identity, and dotfiles so that no matter what machine you’re on,..."

All I've found so far is docs on dotfiles but the statement above on the VS Online landing page says it roams settings, themes, git identity AND dotfiles and I'm seeing that as dotfiles being a separate thing and there's something that roams settings, themes and git identity. Except I cannot find where else this is. My settings in my environments are not roaming and I don't see where they would roam from.

**Comment by DanJ210** [comment]
I've also added VS Code settings to the user settings files. The settings reflected in VS Code. I closed down the instance and then went back into it and settings were back to default but the settings I added in the file were still there. Extensions were still installed. I tried editing and saving the file to see if that would load the changes but it didn't, still default. So I'm pretty lost as to how to roam settings and also how to save your settings in one environment so that the next time you login to that environment those settings/extensions remain.

**Comment by Chuxel** [comment]
@lostintangent @nikmd23 Quick question: Are settings supposed to be retained in the same environment on resume? 

There's roaming settings across environments, but the second comment here surprised me a bit.  Feels like that second part is much more important and more like a bug, but maybe I'm wrong.

**Comment by legomushroom** [comment]
The settings are stored in the IndexedDb of the browser and should be the same between for all environments connected from the same browser (workspace settings will be different though).

We don't roam the settings between browser and desktop at the moment, but it is on our road map.

**Comment by DanJ210** [comment]
Is it possible I was doing something wrong @legomushroom? Or has the issue I described above where environment savings I was saving weren't applying when I returned?

**Comment by jkeech** [comment]
@DanJ210, settings are not really roamed today. The docs are not quite accurate -- they seem to share the long term vision, not what is currently implemented (cc @nikmd23, @abuchholtzau). Currently settings are persisted on the client side. So if you come back from the same browser or VS Code instance, then the settings should re-apply. But if you switch machines, they would not roam.

VS Code is working on a built-in settings sync service which is going to be our solution for truly roaming settings/themes/etc: https://github.com/microsoft/vscode/issues/90129

**Comment by lostintangent** [comment]
Closing this as resolved, now that VS Code's settings sync has been shipped!
