### ISSUE TITLE
Port forwarding in the web editor doesn’t support requests that depend on cookies (e.g. CSRF)

### ISSUE THREAD

**Issue by zhaoxin** [MicrosoftDocs/vscodespaces#193]
Hi,

Thanks for the awesome work on VSO.

I'm running a Django dev server in my environment, while CSRF does not working behind the port forwarding mechanism. It seems like cookie or some header is striped by the proxy.

**Comment by lostintangent** [comment]
Thanks for reporting this! I’m guessing the issue isn’t specific to Django, but rather, any site that relies on CSRF. We’re making a handful of improvements to our port forwarding service, and so we’ll make sure to account for this scenario as well 👍

**Comment by lostintangent** [comment]
Updating this title to call out that this issue is with proxying cookies in general, with CSRF being just one symptom of that general limitation.

**Comment by lostintangent** [comment]
Closing this as resolved. Please re-open it if you're still experiencing issues. Thanks!
