### ISSUE TITLE
Collaboration VS Code - "Invite by email" link sends encoded URL which doesn't work

### ISSUE THREAD

**Issue by weznagwama** [MicrosoftDocs/vscodespaces#195]
**ISSUE**
In VS Code, when clicking "Invite by email" for code collaboration, the URL send is URL encoded (the "?" for querystring is "%3")

**REPRODUCE**
1. Open  VS Code, begin collaboration session
2. Click "Invite by email", and send to someone
3. Observe the URL is encoded and doesn't work when opened

**WHAT SHOULD HAPPEN**
Url should be handled properly

![url-encode](https://user-images.githubusercontent.com/1518569/69046737-d3c6c480-0a4d-11ea-8260-89ef21116d7c.PNG)

**Comment by lostintangent** [comment]
Closing this as resolved. Let us know if you're still running into this issue. Thanks!
