### ISSUE TITLE
Elm Reactor does not work with VS Code Online port forwarding.

### ISSUE THREAD

**Issue by twoquestions** [MicrosoftDocs/vscodespaces#204]
At least that's what Chrome is telling me, it may be caused by some other issue.

Every text asset from Visual Studio Code Online when using Elm Reactor is prepended by a handful (and only a handful) of seemingly random capital letters and numbers.

The error on the browser console is: 
Uncaught SyntaxError: Invalid or unexpected token
(index):11 Uncaught ReferenceError: Elm is not defined
    at (index):11
(anonymous) @ (index):11
(index):1 Failed to decode downloaded font: https://00b1c4069c98315a4c9d637048f909ad00ff-8000.app.online.visualstudio.com/_elm/source-sans-pro.ttf
(index):1 OTS parsing error: invalid version tag

The server-side console gives no errors.

**Comment by nikmd23** [comment]
Thanks for submitting this issue @twoquestions. Would you mind providing the repro steps, or a repo that we can use to repro the issue?

**Comment by lostintangent** [comment]
Closing this as resolved. Please reopen it if you’re running into any problems. Thanks!
