### ISSUE TITLE
Allow creating environments from a local directory/container

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vscodespaces#205]
Currently, we allow you to create an environment from a Git repo, which enables teams to spin up dev boxes for projects that are already under version control. However, we should also consider allowing you to create an environment that is "seeded" from a local directory, in order to accomodate users to transition existing/in-progress codebases to the cloud. This would compliment #57, and provide a means where files can be seamlessly moved to-and-from Visual Studio Online as appropriate.

In addition to us adding some commands/gestures to the [Visual Studio Online extension](https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline) (and [web experience](https://online.visualstudio.com/environments)), we should also consider adding an experience/entry point to the [Remote - Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) as well, so that users can choose to open their local containers within VSO, in a way that's potentially move discoverable.

// CC @Chuxel @egamma

**Comment by egamma** [comment]
//fyi @chrmarti

**Comment by lostintangent** [comment]
Closing this for now, since we haven't heard this request from users. We can always re-open it if/when we hear this feedback 👍
