### ISSUE TITLE
Port forwarding in the web editor doesn’t support HTTP requests with bodies

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vscodespaces#213]
Currently, our browser-based port forwarding  only supports HTTP requests that don’t have bodies (e.g. GET, DELETE, HEAD). As a result, HTML form submissions and/or mutative API calls don’t work, since they often rely on making POST/PUT/PATCH calls with HTTP body content.

This is only a limitation when using VSO from the browser, and therefore, you can work around it by connecting to your environment from VS Code desktop.

**Comment by nikmd23** [comment]
Could you provide more details for when you see this case?

In the ballpark-tracker app, I do a PUT with a body, and it seems to work fine. Here’s the source for that request: https://github.com/nikmd23/ballpark-tracker/blob/master/public/map.js#L368

Perhaps it doesn’t work when some other confounding factor is present?

**Comment by halfnibble** [comment]
@nikmd23  From my experience, you can make the request, and it will appear to succeed. But if you try to parse the body on the server api (assuming your server is running from VS Code Online/Codespaces via port forwarding), then the body will be empty.

I used VS Code Online/Codespaces to teach an online evening class, and this was a major problem for us when we got to the "setup a simple Express api and make a request" part of the course. We use VS Code Online/Codespaces to provide uniformity to students working on a wide variety of devices. 

Ideally, I would like my port forwarded to api endpoints to behave like any public endpoint, and be able to send requests from tools like Postman.

**Comment by halfnibble** [comment]
Also, I think there should be a big warning under "Remote Explorer" > "Forwarded Ports" to warn developers that their forwarded API's may not work as expected. I spent several hours this past weekend trying to chase down where my request body was disappearing to. 

And if I can help with this issue in any way, feel free to message me on Teams. (jowedeki)

**Comment by matt-bornstein** [comment]
+1, looking forward to a solution.  And agree that a warning should be added to the port forwarding dialog - or at least a link somewhere to this issue tracker.

**Comment by Prottoy2938** [comment]
@matt-bornstein , thanks, using `ngrok` fixed the issue for me for now
