### ISSUE TITLE
Cannot install PHP 7.3

### ISSUE THREAD

**Issue by martenvaino** [MicrosoftDocs/vscodespaces#214]
It seems that it throws an error while installing PHP.

**Steps to reproduce the issue:**
1. Create new environment
2. Follow the repository installation tutorial here: [](https://computingforgeeks.com/how-to-install-php-7-3-on-debian-9-debian-8/)
3. Update cmd: `sudo apt update`
4. `sudo apt -y install php7.3`

**Result:**

> vsonline:~/workspace$ sudo apt -y install php7.3
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package php7.3 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'php7.3' has no installation candidate

**Comment by mchelen** [comment]
Same issue here. Might be due to outdated version of Debian (Stretch). Tried following these instructions but no luck: https://linuxize.com/post/how-to-install-php-on-debian-9/

**Comment by lostintangent** [comment]
@jkeech @Chuxel What's the latest on our thinking about updating to a newer version of Debian for our base image? Do we suspect there will be other issues like this that users could run into? I just wonder if we should sync with the Oryx team on this?

**Comment by jkeech** [comment]
> @jkeech @Chuxel What's the latest on our thinking about updating to a newer version of Debian for our base image? Do we suspect there will be other issues like this that users could run into? I just wonder if we should sync with the Oryx team on this?

Yep! We have plans to move to Buster via the oryx base image. That said, we also recently added php 7.3 into the Stretch-based version of the base image, so I'm going to go ahead and close this as resolved 👍.

```$ php --version
PHP 7.3.15 (cli) (built: Feb 24 2020 22:30:19) ( NTS )
```
