### ISSUE TITLE
Allow browsing the files of a suspended environment, without needing to start it

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vscodespaces#217]
In order to provide assistive cost control to developers, we automatically suspend environments after a configurable period of inactivity (30 minutes by default). That way, you only pay for the time you actively use, and you don’t have to explicitly remember to suspend environments when you’re done with them (which can be very error prone!). As soon as you connect to the environment, we automatically start it back up, which prevents you from having to worry about it’s lifetime. Simply use environments when you need them, and let the service manage their lifecycle 👍

When an environment is suspended, its file system is persisted in cloud storage, which allows you to reduce cost, without losing any work. However, in order to browse your in-flight changes, you have to connect to the environment, and begin to incur the cost of running it. If you simply wanted to look up some work you did, and you don’t need the benefits of the running environment (e.g. using a terminal, debugging your code), this can potentially feel like too heavyweight of a process.

As a result, we could explore enabling users to “browse” a suspended environment, which would open up the web editor, and allow you to view and navigate its cloud storage, but without needing to actually start it (and therefore, reducing cost). This scenario could compliment our other “serverless” use cases (#178, #171, #207) and provide broader access to the web editor, in situations that you don’t need a running environment.

When you’re connected to the “serverless” environment, you’d see that the files are read-only, and we could potentially enable you to explicitly or implicitly (e.g. when you press F5?) start up the environment when needed. That way, we can unblock access to your files at any time, and then allow users to seamlessly “upgrade” to an environment.

This would also be complimentary to #168, which would allow committing/pushing changes without needing to start the environment. So this item would add the extra ability to browse the files, but without needing to commit them to version control in order to do it.

**Comment by nikmd23** [comment]
Brainstorming here... 🧠⛈

If we enabled this, then we may also want to consider enabling #202 at all times, not just when an environment is active as suggested in that issue.

**Comment by lostintangent** [comment]
Closing this for now, since we haven't heard this request from users. We can always re-open it if/when we hear this feedback 👍
