### ISSUE TITLE
Improve the Help menu in VSO

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#219]
Many of the items in VSO's help menu are specific to VS Code, or don't quite make sense in context with VSO.

![image](https://user-images.githubusercontent.com/199026/69574228-458e9900-0f8d-11ea-99bc-d5d41dc785f5.png)

I recommend either removing items from the menu, or linking to new content. Specific recommendations include:

| Item | Recommendation | Notes |
|------|---------------------|--------|
| Documentation | Change link | To https://aka.ms/vso-docs |
| Release Notes | TBD | Linking to VS Code's release notes mostly makes sense, but some content that is desktop specific does not |
| Introductory Videos | Change link | We need to create an intro video for VSO, and then link to it |
| Join Us on Twitter | Remove | VSO is not on Twitter |
| Search Feature Requests | Change link | To https://github.com/MicrosoftDocs/vsonline/labels/enhancement |
| View Licence | Change link | Work with legal to get right link |
| Privacy Statement | Change link | Work with legal to get right link |

We may also want to add a "Billing Support" link to the menu.

Additionally, the "Submit a bug" and "Request a missing feature" links have caused some user confusion (#227). We may want to hide this feedback menu (it tweets to @code) or update the links to direct users to this repo.

![image](https://user-images.githubusercontent.com/199026/71295953-9652a100-2343-11ea-8052-ccbfb78d0b9e.png)

**Comment by lostintangent** [comment]
Closing this as wont fix, and we’ll discuss the help menu customizations as part of the new GitHub Codespaces experience 👍
