### ISSUE TITLE
Can't enter single or double quote using international English keyboard in online.visualstudio.com in Edge on Chrome

### ISSUE THREAD

**Issue by eisber** [MicrosoftDocs/vscodespaces#225]
On US-International keyboards single and double quote are entered using "double quote followed by space". This simplifies entering umlauts using "double quote followed by a" for ä.

**Comment by SuHwak** [comment]
I have this same issue. Also, entering the ALT code (ALT+39) for a single quote does work, but entering the ALT code for double quote (ALT+32) does not work.

**Comment by SuHwak** [comment]
Hmm, it might also be change of behavior of Windows 10, but more likely I have screwed up my carefully set up language/region/keyboard settings (English/Dutch/US International, respectively) with testing this stuff. 

In windows (VS Code):
Now if I want to type a doublequote " I need to hold shift, and add space, so: [shift]+" then [keep holding shift]+[space] will result in a ". If you do [shift]+"" it will print "". However, this behavior is difficult for typing letters with umlaut: [shift]+a results in just 'a'. holding shift results in Ä, which is a capital letter. The only way now to type an ä, ö or ü is by holding [alt-gr] and checking which of the keys corresponds to the letter you want to type on the on-screen keyboard... far from ideal.

Still though (in VSCode Online), it will not allow me to type in " or ' with my physical keyboard, only with the on-screen keyboard...

**Comment by lostintangent** [comment]
@bpasero @VincentDondain Do we have any outstanding issues with the web editor and international keyboards?

**Comment by bpasero** [comment]
@lostintangent could be https://github.com/microsoft/vscode/issues/83993

**Comment by lostintangent** [comment]
@bpasero Ah yeah that looks exactly the same! Thanks for the reference to that 👍 I'm going to close this as external, and we'll track this issue via the aforementioned VS Code bug. Thanks!
