### ISSUE TITLE
Automatically authenticate the user with az CLI

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vscodespaces#231]
We install the `az` CLI as part of our default environment, however, we don't automatically authenticate the user with the CLI even though we already authenticate them with Azure. In order to make it easier to use the `az` CLI, we should explore how to provide a better SSO experience for new environments. This way, a user can create an environment, and choose between the Azure VS Code extensions and/or the Az CLI when managing their Azure resources.

**Comment by kitaev-chen** [comment]
Strongly agree with this!!!

there are lots of problems when registering the local environment, especially the local environment is a remote server (I believe the reason that lots of people seek to use vsonline is that they usually have to work on the remote (GPU) server). 

When registering the remote server we have to find a way to launch a VNC or X11 server, then forward to local laptop, then launch a vscode, then register the remote server inside vscode. The vscode will request to sign in azure through a web browser several times and invoke vscode through a link such as "vscode:// xxx". The whole procedure has many steps which is extremely easy to fail and heavily rely on GUI.

The best way for this scenario is to provide a pure command-line and GUI free solution. Hope it will come soon.

**Comment by lostintangent** [comment]
Closing this as resolved.
