### ISSUE TITLE
Self hosted environment and remote-container plugin "Could not resolve workspace folder"

### ISSUE THREAD

**Issue by sethamclean** [MicrosoftDocs/vscodespaces#232]
When using a .devcontainer.json (remote-container plugin) and prompted to "re-open" workspace in a container, the re-opened workspace displays no files and reports "Could not resolve workspace folder".

It seems like support for a .devcontainer,json would be necessary for feature parity with azure based environments. Dotfile support would be really nice as well, but I don't believe this is a feature of the remote-container plugin.

**Comment by jkeech** [comment]
Can you clarify the repro steps or provide a sample repo where the problem occurs?

**Comment by jkeech** [comment]
I’m fairly sure this is related to #116. Self-hosted environments spin up a vs-code remote server on the remote host, but that remote host can not be daisy-chained to another remote currently. So also cannot directly register the remote container as a self-hosted environment itself currently.

**Comment by sethamclean** [comment]
Steps are pretty straight forward:

- Connect to self-hosted environemnt
- Install remote-container plugin
- Open folder containing a .devcontainer.json
- Select OK on prompt to re-open in container
- No files are displayed along with "Could not resolve workspace folder"

**Comment by 2percentsilk** [comment]
Hi @sethamclean, 
As part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will be [retired](https://docs.microsoft.com/en-us/visualstudio/codespaces/resources/consolidation-faq#self-hosted-codespaces) on November 20, 2020 and there isn't a current plan to include this feature in the GitHub Codespaces roadmap. Given the upcoming retirement, I'm going to go ahead and close this issue as won't fix.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
