### ISSUE TITLE
Provide a GitHub integration that enables automatically creating environments for every PR

### ISSUE THREAD

**Issue by ziahamza** [MicrosoftDocs/vscodespaces#240]
We are trying to generate VSCode environments for every GitHub pull request. The goal would be an environment per `branch`. Whats the best way to be able to generate those links? 

Perhaps with any plans for an API or ability to create a link that will auto create a brand new environment for a given branch + git repo?

**Comment by nikmd23** [comment]
Hello @ziahamza!

Right now, we don't support creating an environment from the non-default branch. 😞 It's a feature that's coming though, and you can track it at #81.

In terms of links, we need to update the documentation, but for now, you can see an example [here](https://github.com/nikmd23/ballpark-tracker/blob/master/README.md).

**Comment by lostintangent** [comment]
I'm going to re-open this issue, so that we can use it to track the idea of enabling a GitHub integration that auto-creates environments for PRs. This is something we definitely want to explore 👍

**Comment by lostintangent** [comment]
Since we're consolidating Codespaces into GitHub, we'll be tracking roadmap requests via the [Community Support](https://github.community/c/codespaces-beta/45) forum. So I'm going to close this for now, so we can move the conversation there. Thanks!
