### ISSUE TITLE
Support creating Windows based environments

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#243]
Some of the workloads I have are dependent on Windows. 

I'd like to be able to work on them in VSO, but the only available instance types are Linux based.

**Comment by nikmd23** [comment]
Note: This capability is currently in private preview. Sign up [here](https://aka.ms/vsfutures-signup) to request access.

**Comment by lostintangent** [comment]
Closing this as resolved per the private preview release 👍
