### ISSUE TITLE
Support registering self-hosted, SSH-enabled environment via VSO website

### ISSUE THREAD

**Issue by smikitky** [MicrosoftDocs/vscodespaces#245]
With [AWS Cloud9 SSH Environments](https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-ssh.html), you only have to fill the following form and add the displayed public RSA key to `~/.ssh/authorized_keys` in the self-hosted machine to get started.

![image](https://user-images.githubusercontent.com/7779406/70252844-7361b200-17c5-11ea-940b-775e5d8766c6.png)

After clicking "Open IDE" for the first time, server-side dependencies (~100MiB) will be installed under `~/.c9` via plain old SSH. A very similar workflow is already possible with VSCode's "Remote - SSH" today, so I suppose VSO can do the same. Is this type of registration workflow on the VSO's roadmap?

While #69 is good, installing something via a terminal is a bit more difficult than adding a single SSH key. The approach suggested in #116 means you need a locally-installed VSCode to get started, but such an assumption kind of kills the main advantage of VSO...

**Comment by nikmd23** [comment]
Thanks for the feedback @smikitky! ATM, #69 is our the next major item on our road map for self-hosting.

As you've mentioned, the [VS Code Remote SSH extension currently allows users to follow this workflow](https://code.visualstudio.com/docs/remote/ssh). That's the recommended approach for using SSH to self-host for now.

However, this is a good idea and one that we'll have to consider where it fits into the road map.

**Comment by jkeech** [comment]
@smikitky, following up here -- #69 is now implemented.

We don't currently have this one on our roadmap, although we are considering providing an easy way to take existing Remote SSH environments and "upgrading" them to VSO self-hosted environments, which would work similarly. We might also be able to do something like this at the same time, especially if it gets enough up-votes from the community.

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal. If this is something folks would like to see, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
