### ISSUE TITLE
Support recursive cloning / submodules for git

### ISSUE THREAD

**Issue by devanlai** [MicrosoftDocs/vscodespaces#246]
For repositories that use [git submodules](https://git-scm.com/docs/git-submodule), the repository is cloned using the default `git clone` without the `--recursive` option.
For example, here's the setup VS Online terminal log when creating an environment based on https://github.com/libopencm3/libopencm3-template:

```
vsonline:~$ OPERATION_ID=4b33ade9-084d-4371-a0bd-140e1b94d7f9 /.vsonline/bin/vso exec git clone  https://github.com/libopencm3/libopencm3-template /home/vsonline/workspace
[2019-12-05 23:11:14.096 CLI I] vso v1.0.1315.65159 (pid: 129)
Cloning into '/home/vsonline/workspace'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 50 (delta 1), reused 4 (delta 1), pack-reused 46
Unpacking objects: 100% (50/50), done.
[VS Online][4b33ade9-084d-4371-a0bd-140e1b94d7f9] Process finished successfully.
```

Since it's just a regular clone and not a recursive clone, the submodule within the environment is not initialized and is just an empty folder. Either by default, or as an option, it should be possible to create an environment that performs a recursive clone. 

It's possible to work around this by running the following:

    git submodule update --init --recursive

This can either be done manually or as part of a devcontainer postCreateCommand, but it shouldn't be necessary to customize the repo just to handle submodules, which are a common feature.

**Comment by nikmd23** [comment]
This is great feedback @devanlai.

I can’t think of any negative side effects to doing this, so we should explore making it the default.

**Comment by egamma** [comment]
@nikmd23 see also https://github.com/microsoft/vscode-remote-release/issues/1710 there the recommendation is to complete the clone recursively in the `postCreateCommand`.

**Comment by nikmd23** [comment]
Thanks for the tip @egamma!

@devanlai, that’s the best way to move forward. I’ll leave this issue open until we document this suggestion.

**Comment by jkeech** [comment]
@nikmd23, @egamma any reason to not make it the default setting? I expect that the vast majority of users with submodules in their repo will want them initialized in their environment. The main downside seems to be slower clone/setup time in the cases where they did not need/want the sub module contents.

**Comment by egamma** [comment]
@jkeech if this is enabled by default, then there needs to be some way to disable the recursive behaviour (e.g. when you have large submodules). 

In VS Code Remote we currently do not have such a configuration option and we wanted to keep the UI minimal, but we could invest into this.

**Comment by jkeech** [comment]
@egamma, absolutely. I would be in favor of having this be the default, and then having a set of advanced settings that could turn this off. We also want to provide a similar checkbox for disabling the `oryx build` after clone if you haven't provided a `postCreateCommand` in devcontianer.json, so there are likely a few different advanced settings to give finer control over the create process.

**Comment by lostintangent** [comment]
Closing this for now, due to the ability to control this via a `postCreateCommand`. If adding a custom `devcontainer.json` property is something folks would like to see us invest in, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
