### ISSUE TITLE
Connection failed with HTTP ERROR 411 (Login to ASP.NET Core Website) 

### ISSUE THREAD

**Issue by DenisMtfl** [MicrosoftDocs/vscodespaces#256]
I have created a new asp.net core 3.1 with auth project. 
When i want do debug the project, connection failed when i try to login i got HTTP ERROR 411.

Where is the Problem?

**Comment by jkeech** [comment]
Thanks for reporting this issue @DenisMtfl. Can you provide some clear repro steps? Also, are you connected to the environment from VS Code desktop or from the browser (port forwarding works slightly differently in these two cases)?

**Comment by lostintangent** [comment]
We've made a lot of improvements to our port forwarding service over the last few months, so I'm going to closed this as resolved. Please re-open if it you're still running into problems. Thanks!
