### ISSUE TITLE
[self-hosted] can no longer add folders to workspace

### ISSUE THREAD

**Issue by Helianthella** [MicrosoftDocs/vscodespaces#262]
Since issue #235 was fixed I am once again able to connect to my self-hosted environment but I can no longer add/remove folders to the workspace.

1. File Explorer > Right-click > Add Folder to workspace
2. (choose the folder on the remote host)
3. the entire page refreshes unexpectedly and then there is zero folders in the workspace
4. at this point if you manually refresh you see that nothing has actually changed (no folder added/removed)

**Comment by taiyosogawa** [comment]
Hi @Helianthella, thanks for reaching out with this problem. I was able to reproduce the issue when connecting via the browser, and we will work to resolve it. 

In the meantime, it looks like the feature is working correctly when connected to the self-hosted environment via the desktop app. I don't know if that would be a viable option for you, but it could be a possible temporary workaround.

**Comment by Helianthella** [comment]
I am using VS Online on a chromebook with an armv8 arch so it cannot install vscode (no arm support) and vscodium does not support VS Online (nor Remote-SSH) because it is a "proposed" api. No big deal though, I have other laptops

**Comment by 2percentsilk** [comment]
Given the inactivity on this issue and the impending [retirement of self-hosted machines](https://docs.microsoft.com/en-us/visualstudio/codespaces/resources/consolidation-faq#self-hosted-codespaces) on November 20, 2020 as part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), I'm going to go ahead and close this issue.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
