### ISSUE TITLE
invalid favicon path

### ISSUE THREAD

**Issue by Helianthella** [MicrosoftDocs/vscodespaces#263]
not a bug, just a visual issue
vsonline tries to load a favicon from an incorrect path ([404](https://online.visualstudio.com/static/web-standalone/favicon.ico)) when accessed in the browser

```diff
-<link rel="shortcut icon" href="static/web-standalone/favicon.ico">
+<link rel="shortcut icon" href="static/web-standalone/stable/favicon.ico">
```

**Comment by nikmd23** [comment]
Thanks for the report @Helianthella! We've got someone looking into the issue.

**Comment by lostintangent** [comment]
@plisy Has this been fixed?

**Comment by plisy** [comment]
Nope, still a problem. I'm working on a larger fix for taking the right version of VSCode this sprint, so I'll take care of this as well.

**Comment by lostintangent** [comment]
I believe this is now resolved. @plisy please re-open if we still need this issue to track any further work. Thanks!
