### ISSUE TITLE
[Feature request] Support requesting a SSO URL

### ISSUE THREAD

**Issue by xcelsion** [MicrosoftDocs/vscodespaces#270]
I'm exploring the feasibility of integrating Visual Studio Online into a platform we're developing. I'd like to be able to, on a customer's request:

1) Start an ssh container in our cluster.
2) Push ssh credentials to Visual Studio Online.
3) Provide the customer with a URL that, when accessed, opens the web IDE.
4) Have the IDE utilize the supplied credentials to run vscode-server inside the ssh container.

Ideally, the customer would not be required to have a Microsoft account.

**Comment by nikmd23** [comment]
Hello @xcelsion! I'd love to learn more about your scenario and how you'd see it working. Would you mind following up with me via email so we could discuss further? ({my first name} + "." + {my last name} + "@microsoft.com")

**Comment by nikmd23** [comment]
@xcelsion has reached out and we are discussing this request out of band. I'll update the issue once we've worked together to better understand this request.

**Comment by lostintangent** [comment]
Closing this issue since the discussion has been taken offline 👍
