### ISSUE TITLE
Azure Move Visual Studio Online Plan failed

### ISSUE THREAD

**Issue by bennya1** [MicrosoftDocs/vscodespaces#275]
Hi,

When trying to move the "Visual Studio Online Plan" resource to a new subscription, the operation fails with the error:

statusMessage": "{\"error\":{\"code\":\"ResourceMoveFailed\",\"message\":\"Resources '/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/vso-rg/providers/Microsoft.VSOnline/plans/vso-plan-westeurope' **move actions failed**. The correlation Id is '3cd9b016-8a7b-433b-800a-1e0db5233cf8'\",\"details\":**[{\"code\":\"BadRequest\",\"target\":\"Microsoft.VSOnline/plans\",\"message\":\"\"}]}}"**

Is this achievable somehow? 

Appreciate your help.

**Comment by jkeech** [comment]
@bennya1, we don't support moving or renaming plan resources yet, but that is on our roadmap. For now, you would need to delete and re-create in the new subscription. Keep in mind that deleting the plan will also delete all environments in the plan, so you would need to recreate those as well. Sorry for the inconvenience.

**Comment by lostintangent** [comment]
Closing this issue since we're in the process of consolidating Codespaces into [GitHub Codespaces](https://github.com/features/codespaces), and therefore, are no longer investing into Azure-specific workflows like this.
