### ISSUE TITLE
Stopped working - Connection error: Version mismatch, client refused

### ISSUE THREAD

**Issue by stengergilles** [MicrosoftDocs/vscodespaces#276]
Since today my VSO environment does not work anymore. 
I'm unable to browse for files. ( /home/vsonline does not exist, / does not exist either ) 
I get message : Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

What can I do  ? Is the environment lost ( aka need to recreate it ) ? 

Regards 

Gilles

**Comment by jkeech** [comment]
A nee version of the client was rolled out, and VS Code server requires an exact match between both sides. But the old one is cached in your browser. We need to solve this caching bug, but for now, you can work around it with a hard refresh in your browser (Ctrl + F5).

/cc @legomushroom

**Comment by legomushroom** [comment]
@stengergilles is it still broken for you?

**Comment by jordanbean1** [comment]
I saw this issue today. I had to clear my cookies and login again. This solved the issue of not connecting to my workspace, but it lost some custom settings (like my color theme in VS Code)

**Comment by lostintangent** [comment]
Closing this as resolved, since we've made a bunch of improvements in this area over the last few months. If folks are still encountering issues here, please re-open this and we'll investigate it. Thanks!
