### ISSUE TITLE
Environment name validation on creating a new environment

### ISSUE THREAD

**Issue by arjun27** [MicrosoftDocs/vscodespaces#277]
In the web portal, when I'm creating a new environment and enter a name for the environment, I see a check mark in the name box, which seems to indicate that the name has been validated.

However, if an environment of the same name already exists, the "create environment" action will fail, saying that the environment name is not unique.

It would be useful to get the error message when the name was (seemingly) validated, before we attempted to create an environment.

**Comment by lostintangent** [comment]
Closing this as “wont fix” since we’re consolidating Codespaces into GitHub, where you don’t specify an environment name.
