### ISSUE TITLE
Unable to authenticate with Azure on Debian Linux

### ISSUE THREAD

**Issue by EverythingTech** [MicrosoftDocs/vscodespaces#278]
I am able to log in with Azure successfully. However, when I click on "Create New Environment", a log in page appears but it does not send the log in credentials back to VS Code after I login on the webpage, leaving VS Code waiting for authentication. 

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.9.0-11-amd64

**Comment by lostintangent** [comment]
We've made a bunch of improvements to the login flow over the last few months, so I'm going to close this as resolved. However, please re-open this if you're still encountering any issues. Thanks!
