### ISSUE TITLE
Indicate an environment's primary language on it's environment card

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vscodespaces#29]
We already do the work to detect an environment's primary language (e.g. in order to install the right VS Code extensions), and so, it might be a nice visual touch to indicate that on the environment's card in the management portal.

**Comment by jkeech** [comment]
@lostintangent, I believe we only detect an environment's primary language under certain conditions, such as when you don't have a devcontainer.json specified. We could do this, but it would require us to start scanning all environments for primary language.

**Comment by nikmd23** [comment]
Hey @lostintangent! Cool idea. 😀

Do you see this as "purely decorative" or do you expect that a user might do something different with this information? I'm interesting in understanding how you'd like to use this information.

Also, is it reasonable to assume users that cloned from GitHub would expect the language we detect to match the one that GitHub has detected?

![image](https://user-images.githubusercontent.com/199026/68440250-6d61bc80-0198-11ea-9da5-e192405c7513.png)

**Comment by lostintangent** [comment]
I see this as purely a “decorative” thing 😁

**Comment by nikmd23** [comment]
Thinking about this experience a little more... 🤔 

I wonder if it makes sense to extend this notion to be slightly more generic, and allow arbitrary "tags" to be added to environments, similar to tags on questions on StackOverflow. Our service could "auto-tag" environments with key data points - language (or languages) as suggested here - but other examples might include the OS of the environment or the environment seed type.

Either way, this metadata begs to be incorporated into sorting and filtering mechanisms in the future.

**Comment by abuchholtzau** [comment]
It will be interesting to see if users have similar but "different enough" environments where having a language or environment tag helps them ensure they connect to the right environment. I think @nikmd23 idea of generic key data points would be useful if we see this customer pattern emerge.

**Comment by lostintangent** [comment]
Closing since, since aside from me, no user has actually asked for this :smile: If this is something folks would like to see us invest in, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
