### ISSUE TITLE
Code changes not used when debugging

### ISSUE THREAD

**Issue by justusbotlabsgg** [MicrosoftDocs/vscodespaces#315]
Not sure what my issue is but when I make changes in the browser editor, then debug, none of my changes affect my program.  I guess I'm missing something obvious, but I don't know lol.  Thanks for any help

**Comment by lostintangent** [comment]
@justusgametv Hmm, that's unexpected! Which language are you trying to debug? We can try to repro this on our end 👍

**Comment by justusgametv** [comment]
@lostintangent I am debugging C# and was going to give some background.  This is a self-hosted set up, and I see the changes on remote machine.  VS Code debugging is fine, its just when I access the via the browser I don't get my changes when I run debugging.

**Comment by lostintangent** [comment]
Closing this as resolved, since I'm no longer able to repro it. If you're still encountering this issue, please re-open it and we'll investigate what might be going on. Thanks!
