### ISSUE TITLE
Unable to resume suspended environment - it gets stuck in the 'starting' state

### ISSUE THREAD

**Issue by fpintos** [MicrosoftDocs/vscodespaces#320]
https://online.visualstudio.com/environment/605b73fd-cf6d-454d-bb15-ab836d568788

![image](https://user-images.githubusercontent.com/4239171/75504892-92b84780-598e-11ea-8a75-be9c1f769106.png)

**Comment by edgonmsft** [comment]
Hi Fabio,

Thanks for reporting the issue, could you please suspend and restart the environment?

Thanks!

**Comment by fpintos** [comment]
Thanks @edgonmsft ! The environment is working perfectly now!

**Comment by fpintos** [comment]
Hi @edgonmsft , this issue has re-surfaced, on the same environment.

**Comment by lostintangent** [comment]
Closing this as resolved, since we've made numerous improvements to resuming Codespaces. Please re-open this issue if you're continuing to encounter any problems. Thanks!
