### ISSUE TITLE
Cannot connect to environment from VS Code on macOS

### ISSUE THREAD

**Issue by anthonychu** [MicrosoftDocs/vscodespaces#335]
I'm having trouble connect to VS Online cloud environments using VS Code on macOS.

Repro steps:

1. With Remote Explorer in VS Code, click sign in to view environments (it seems to always forget my sign in, which might be part of the problem).
    ![image](https://user-images.githubusercontent.com/3982077/76056115-89008800-5f2a-11ea-9232-64929d8a73fa.png)
1. Sign in screen opens in Edge (stable). I sign in.
1. Click Continue and Open.
    ![image](https://user-images.githubusercontent.com/3982077/76056194-c2d18e80-5f2a-11ea-8669-3879712675a4.png)
1. Click Don't ask again and Open.
    ![image](https://user-images.githubusercontent.com/3982077/76056204-ce24ba00-5f2a-11ea-83eb-8615118733ba.png)
1. Environments appear. Click on Connect to environment.
![image](https://user-images.githubusercontent.com/3982077/76056224-dda40300-5f2a-11ea-9081-2ca595cd6033.png)
1. Get sent to the browser again. Log in. When redirected back to VS Code, this appears forever:
![image](https://user-images.githubusercontent.com/3982077/76056380-44292100-5f2b-11ea-90a7-dc1b53b4fab7.png)

More info:
* If I open dev tools, there's one error in the console. Not sure if it's normal:
    ![image](https://user-images.githubusercontent.com/3982077/76056915-a9c9dd00-5f2c-11ea-976e-3199928e7d04.png)
* If I close remote connection, VS Code reloads and I'm no longer signed in to Remote Explorer.
* This works fine on my 2 Windows machines.
* I've tried changing default browser to Chrome and also tried with VS Code Insiders, same problem.
* Tried multiple cloud environments.

**Comment by nikmd23** [comment]
@legomushroom or @jkeech have you seen this issue before?

**Comment by anthonychu** [comment]
Still happening after reinstalling the extension and restarting my machine. Some logs:

I had previously signed in. When I reopen VS Code and open Remote Explorer:

```
[Client V] Initializing authentication
[Client V] Initializing self-hosted environment registry
[Client I] Trace log: /var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/vsonline_logs/20200328_190327_15854222071310_VSCode.log
[EnvironmentInfo E] Failed to fetch environments
EnvironmentProvider found no cached tokens
Error: EnvironmentProvider found no cached tokens
    at toString (/Users/antchu/.vscode/extensions/ms-vsonline.vsonline-1.0.1889/src/EnvironmentProvider.ts:431:39)
    at Object.t.getEnvironmentList (/Users/antchu/.vscode/extensions/ms-vsonline.vsonline-1.0.1889/src/EnvironmentProvider.ts:355:21)
    at d.updateEnvironmentsInfo (/Users/antchu/.vscode/extensions/ms-vsonline.vsonline-1.0.1889/src/EnvironmentInfo.ts:66:13)
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
```

Clicked sign in and authenticated. I can see my cloud hosted environments:

```
[Command:u I] Decorator starting: l
[Command:u I] Decorator starting: a
[EnvironmentDetailsExplorer I] Updating environment details
[Client I] User logged in as antchu@microsoft.com
[AuthenticationInit I] User logged in as antchu@microsoft.com
[EnvironmentDetailsExplorer I] Updating environment details
```

Now I run Reload Window command in VS Code. No longer signed in:

```
[Client V] Initializing authentication
[Client V] Initializing self-hosted environment registry
[Client I] Trace log: /var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/vsonline_logs/20200328_190714_15854224346010_VSCode.log
[EnvironmentInfo E] Failed to fetch environments
EnvironmentProvider found no cached tokens
Error: EnvironmentProvider found no cached tokens
    at toString (/Users/antchu/.vscode/extensions/ms-vsonline.vsonline-1.0.1889/src/EnvironmentProvider.ts:431:39)
    at Object.t.getEnvironmentList (/Users/antchu/.vscode/extensions/ms-vsonline.vsonline-1.0.1889/src/EnvironmentProvider.ts:355:21)
    at d.updateEnvironmentsInfo (/Users/antchu/.vscode/extensions/ms-vsonline.vsonline-1.0.1889/src/EnvironmentInfo.ts:66:13)
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
```

**Comment by lostintangent** [comment]
@legomushroom This seems like an auth issue?

**Comment by legomushroom** [comment]
Looks like keytar issue to me, we saw cases of this before but weren't able to find a repro.

**Comment by anthonychu** [comment]
@legomushroom I have a repro if you want to ping me on Teams. :)

**Comment by anthonychu** [comment]
@legomushroom Is there anything I can do to narrow down or fix this problem?

**Comment by legomushroom** [comment]
@anthonychu sent a message in teams.

**Comment by legomushroom** [comment]
Looked at this in a call with @anthonychu, clearing out the `VS Code Account` keys in the system `keychain` solves the issue. At this point, it is not clear why the keytar when into this bad state, will try to follow up with VSCode team about this.

**Comment by JoshuaToenyes** [comment]
This is happening to me as well on Chrome OS. For what it's worth, a similar thing occurs when authenticating with the Azure Account extension. Seems like when the window is closed/re-opens the credentials are lost.

Has there been any progress or new insights on this issue?

**Comment by lostintangent** [comment]
Closing this as resolved since I'm not able to repro this, and it seems like it might be related to a corrupted keychain/environment setup issue. Please re-open this if you're continuing to encounter a problem. Thanks!
