### ISSUE TITLE
Allow specifying a repo URL without the protocol

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vscodespaces#344]
Currently, when cloning an environment from a repo, you need to include a full HTTP/S URL to a git repo.

Ideally, I should be able to copy/paste several variants:
- Clone with SSH, a-la GitHub SSH Clone dropdown or `git remote get-url origin`: `git@github.com:MicrosoftDocs/vsonline.git`
- Clone with SSH, without protocol: `github.com:MicrosoftDocs/vsonline.git`
- Clone with HTTP/S, without protocol: `github.com/MicrosoftDocs/vsonline`

This has already gotten me a few times and has been moderately frustrating, having to either go get the full URL or edit the SSH URL.

**Comment by jkeech** [comment]
SSH is covered by #311.

For "clone without protocol", we already support the shorter form `{org}/{repo}`, such as `microsoft/vscode` without the `github.com` prefix. We are not currently planning to support more formats for http(s) clones besides the full url and the shorthand form for GitHub repos, but based on user feedback could consider adding others. I think keeping the number of support formats smaller is better to keep things consistent for users.

**Comment by bnb** [comment]
> I think keeping the number of support formats smaller is better to keep things consistent for users.

As a user, for me it introduces an unnecessary barrier that feels useful for implementation but does not necessarily enable me to have the lowest barrier experience possible. I can't really think of a case in which I'd personally be grateful that I didn't have the option include or omit information that could be assumed.

**Comment by jkeech** [comment]
@bnb having well-known ways to specify inputs either through common convention or through documented examples makes it much clearer around what is expected. Otherwise it's not clear what data omission is allowed vs not allowed. Just because we can be arbitrarily flexible doesn't mean we should be, because it doesn't necessarily make things simpler to understand or provide a consistent experience for users. And in some cases, the tooling could make the wrong inference around what the user intended when filling in the gaps for missing data, which would be more confusing than erroring out up front.

I've never seen anyone try to clone repos or reference repos using a format like `github.com/MicrosoftDocs/vsonline`. I don't think we want to add support for formats that are not common conventions unless there is demand from a sizeable portion of users. So if enough people request this format, we will add support for it at that time. Just curious though -- why is `github.com/MicrosoftDocs/vsonline` easier than `MicrosoftDocs/vsonline`?

**Comment by bnb** [comment]
> having well-known ways to specify inputs either through common convention or through documented examples makes it much clearer around what is expected.

As someone who works in the JavaScript ecosystem at the platform level, I am painfully aware of this ❤️ 

There's a few points here:

- If common convention is what's intended, it's worth looking at the DX of browsers which do not require user input of protocols. While not `git clone`, it's a relatively reasonable decision: users do not need to care about this since a machine can solve it.
  - Given that the people using VSO may not be familiar with `git clone` and may not be familiar with the `<org>/<repo>` shorthand, I don't think it's unreasonable to fall back to this common convention that the internet has been built on for well over a decade at this point.
- As far as I can tell this would take an addition bullet in terms of documentation - three (or four, once ssh support ships) options, rather than two. It could even be a sub-bullet or condensed into the same bullet as protocol support. Happy to help with the prose of this, if it'd be useful!

>Otherwise it's not clear what data omission is allowed vs not allowed.

This is already the case, at least in my experience.

>I've never seen anyone try to clone repos or reference repos using a format like `github.com/MicrosoftDocs/vsonline`

I have run workshops with folks who are new to programming who've stumbled over this exact problem before, so perhaps that's the difference of perspective we're coming at this with 😅

Additionally, for context _that is exactly what I did_ when I tried to use VS Online for the first time after the announcement that Dockerfiles were supported - and why I created the issue. It was not particularly clear that this was a UI for `git clone` nor that the <org>/<repo> syntax was supported. Even if it were made clear that it is a `git clone`, that syntax is native to me in the sense of `hub` and how I write about GitHub repos, but not `git clone`.

In the web, we've very much been taught that `https://` and `http://` do not matter. Given that this is a layer of DX _on top of git_, as is shown with the <org>/<repo> shorthand,  I don't think dropping protocol support is too  much of a stretch.

> And in some cases, the tooling could make the wrong inference around what the user intended when filling in the gaps for missing data, which would be more confusing than erroring out up front.

Parsing as a URL outside of the protocol should be _relatively_ straightforward. If it's not, it is concerning that there's a level of brittleness to the input validation that uses the protocol preface as a mechanism for error detection.

> Just curious though -- why is `github.com/MicrosoftDocs/vsonline` easier than `MicrosoftDocs/vsonline`

It's not - they're different use cases. One (protocol-less) enables the user to mess up but have their intent understood. The other (shorthand) is a cool-kids layer of DX that only an in-group - however large - will use.

**Comment by jkeech** [comment]
@bnb, thanks, I think I understand where you are coming from.

From what I have observed, most users copy and paste the url to clone from the browser bar or from the "Clone" links in various provider websites, and both of those already have the full protocol specified. Most folks either don't remember the entire url, or don't want to type the whole thing by hand, hence the copy + paste, which works well today. If you are hand-typing in the repo name, then I see where this issue would come up. But in the case where you frequently type memorized repo names in the form, learning the GH shorthand (via docs, help text, etc) is more convenient, so I'd rather steer people towards that approach. Then we are left with two common ways to do it:
1) The most common way where people copy and paste from the browser's address bar or the git clone url as provided by GitHub, Azure DevOps, etc
2) A manual entry way that is optimized for that scenario to keep the input as simple as possible (the shorthand form)

I'm not convinced that we need multiple different manual entry formats, but again, if we hear feedback from several users that this would be helpful, we can definitely add it.

**Comment by lostintangent** [comment]
Since SSH is already covered by #311, I’m renaming this issue to be specific to allowing HTTP/S URLs to omit the protocol (at which point, we’d assume HTTPS). 

Depending on the browser/OS, I’m pretty sure there are cases where when you copy/paste a URL from the navigation bar, it can actually omit the protocol. I’ve been hit by this as well. Let me try to repro that, since I think we all agree that we’d want to support copy/paste scenarios from meaningful/common sources.

**Comment by jkeech** [comment]
@lostintangent, I agree. If some common browsers do not include the protocol when copying out of the address bar, then we should support that pattern since that's a common use case. What did you find?

**Comment by lostintangent** [comment]
Closing this as “wont fix” not that we’re consolidating Codespaces into GitHub Codespaces, where you don’t need to type a repo URL manually. If you have any feedback on how we can improve the GitHub-based experience, let us know on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
