### ISSUE TITLE
Create New Environment requires Git client

### ISSUE THREAD

**Issue by ibidani** [MicrosoftDocs/vscodespaces#346]
When trying to create new environment on host without Git client installed the following error occurs
> Create New Environment: The issue encountered for 'Microsoft.VSOnline'; cannot fulfill the request.

Dev tools throws the following exception
> ERR command 'git.clone' NOT known: Error: command 'git.clone' NOT known

If Git client required ask the user to install or at least display proper error message

**Comment by jkeech** [comment]
@ibidani, can you clarify if you were using VS Code desktop to create the environment, or were you using the browser?

The top error you reported looks like an ARM API error when creating or querying plan resources in Azure, which would be unrelated to any Git commands.

**Comment by lostintangent** [comment]
@edgonmsft Do we still have dependencies on Git in order to create environments from any client? I recall this was an issue a while ago, but I don’t recall if we changed anything.

**Comment by lostintangent** [comment]
Closing this as resolved, since we recently removed the dependency on Git from our VS Code extension. @taiyosogawa @2percentsilk please re-open this if I'm mistaken, and this is still an issue. Thanks!
