### ISSUE TITLE
Port forwarding for Jupyter Notebooks failing token authentication

### ISSUE THREAD

**Issue by crazy4pi314** [MicrosoftDocs/vscodespaces#347]
I have been trying to use VSO to host a Jupyter notebook server and then connect to it. I can get to the server page where it asks for the token, but when I provide it, the page gives me the following message:

> # 403 : Forbidden
> The error was:
>
> `'_xsrf' argument missing from POST`

This may be related to #213 and/or #210 but I am not sure.

Steps to reproduce:
1. Create a new environment from this repo: https://github.com/crazy4pi314/learn-qc-with-python-and-qsharp
2. From the integrated terminal, in the default workspace run `jupyter notebook --ip 0.0.0.0` (sample output below)
 ```
jovyan@f2deb5972a97:~/workspace$ jupyter notebook --ip 0.0.0.0

[I 03:05:01.211 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 03:05:01.467 NotebookApp] Serving notebooks from local directory: /home/jovyan/workspace
[I 03:05:01.467 NotebookApp] The Jupyter Notebook is running at:
[I 03:05:01.467 NotebookApp] http://f2deb5972a97:8888/?token=811fb91090e2d8ebd392a669503fe242fedf3451c34c7e53
[I 03:05:01.467 NotebookApp]  or http://127.0.0.1:8888/?token=811fb91090e2d8ebd392a669503fe242fedf3451c34c7e53
[I 03:05:01.467 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
3. From the remote development panel on the left, at the bottom should be a listing for the port 8888, click it to launch a connection in a new tab.
![image](https://user-images.githubusercontent.com/6486256/76694672-0024d300-6633-11ea-961a-cb1de0e05d4a.png)
4. Step 3 should open a window that is the Jupyter server asking for a token, paste in the one that was generated in starting the server in step 2.
![image](https://user-images.githubusercontent.com/6486256/76694724-cc967880-6633-11ea-81ef-372a6e7f5acd.png)
5. You will then get this error:
![image](https://user-images.githubusercontent.com/6486256/76694736-f059be80-6633-11ea-951f-2a5da2ee83ab.png)

Thanks so much for the help!

**Comment by wpbrown** [comment]
This issue can be overcome by using the link in the console. The link passes the token as a query parameter in the URL. However once you are in, you won't be able to do anything useful because of https://github.com/MicrosoftDocs/vsonline/issues/213 .

**Comment by hamelsmu** [comment]
Yeah #213 would be really useful to fix as it would unblock using Jupyter notebooks on GitHub in addition to VSCode, which would be amazing!

**Comment by lostintangent** [comment]
This should now be resolved! Please let us know if you're still running into any issues. Thanks!
