### ISSUE TITLE
Update Java Version on Default Container

### ISSUE THREAD

**Issue by brunoborges** [MicrosoftDocs/vscodespaces#351]
Currently, Java 1.8 is installed on the default container. This version is outdated, slow, and insecure.

```bash
vsonline:~/workspace$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

Please update to Java 11 (LTS) or Java 14 (GA).

**Comment by brunoborges** [comment]
Relates to #111

**Comment by jkeech** [comment]
Java is not a scenario that we have spent much time trying to cover with the base image to date. We can look at improving support there, but now that custom containers are available, that should be another viable solution if the base image with Java 8 doesn't work well for you: https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring.

**Comment by brunoborges** [comment]
I assume most users that experiment VS Online for the first time, use the base image. If we can avoid frustration for those Java developers who decide to experiment it, to get the latest LTS release out of the box, I believe to be a good measure.

Should be easily doable and we from the Java team at Microsoft would be happy to help if you provide the pointers so we can submit a PR.

**Comment by jkeech** [comment]
The VSO base image builds on top of the [Oryx](https://github.com/Microsoft/Oryx) base image, so the preference would be to work with Oryx to get better Java support built in.

**Comment by lostintangent** [comment]
This should now be resolved in the latest base image 👍  Let us know if you ru into any issues or have further feedback. Thanks!

![image](https://user-images.githubusercontent.com/116461/92854607-31921780-f3a6-11ea-8e35-7c7ac53d39be.png)
