### ISSUE TITLE
Sign-in loop on iPadOS

### ISSUE THREAD

**Issue by sionicion** [MicrosoftDocs/vscodespaces#362]
Although iPadOS isn't supported currently, I used to be able to sign in and get into an environment. Recently I wanted to try it out again but when I sign in, it says to do two-factor auth even though I already did, and it loops. If I try going to the site again in a new tab, it loops on wanting to sign in.

**Comment by GalacticLion7** [comment]
I think they blacklisted iPadOS recently. I used to be able to sign in and get an environment as well, but now it brings you back every time and you get the yellow panel on top that tells you the browser isn't supported.

https://imgur.com/ggxjN9y

**Comment by wbpluto** [comment]
Waiting for the official support of iOS and Android

**Comment by sionicion** [comment]
> I think they blacklisted iPadOS recently. I used to be able to sign in and get an environment as well, but now it brings you back every time and you get the yellow panel on top that tells you the browser isn't supported.
> 
> https://imgur.com/ggxjN9y

Yeah but that yellow panel was always there since the beginning.. That's disappointing if they did do that. It wasn't perfect, but it did work..

**Comment by lostintangent** [comment]
@legomushroom Hey! Is this a known issue?

**Comment by legomushroom** [comment]
Safari blocks any 3rd party storage attempts and currently, we rely on `microsoftonline.com` cookies for authentication. To unblock yourself, you can enable that in the Safari settings. We are working on an authentication change at the moment that should eliminate the issue completely.

**Comment by bobyvankenobi** [comment]
Even if i do that wont work for me, but looking forward to use it on ipad! A big thank you for your efforts!

**Comment by GalacticLion7** [comment]
> Safari blocks any 3rd party storage attempts and currently, we rely on `microsoftonline.com` cookies for authentication. To unblock yourself, you can enable that in the Safari settings. We are working on an authentication change at the moment that should eliminate the issue completely.

Any update?

**Comment by lostintangent** [comment]
@legomushroom Any updates here? I just tried this on an iPad and it seemed to work great 👍

**Comment by legomushroom** [comment]
@klvnraju did some tweaks to improve Safari login experience so it should work now.

**Comment by lostintangent** [comment]
OK awesome. I’m going to close this as resolved for now, but please reopen it if you’re still experiencing any issues here. Thanks!
