### ISSUE TITLE
Unclear what's happening on live log screen

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#373]
At the end of environment creation, the live log screen appears to "freeze" for ~10 seconds before the workbench loads.

![image](https://user-images.githubusercontent.com/199026/78183459-90358b80-742d-11ea-83af-e1f5e61e7dda.png)

Now that we're auto connecting to the workbench, it'd be helpful to display an additional box on the live log that says "Connecting" (or similar) with a spinner during this time.

**Comment by osortega** [comment]
There is a gap between when all the setup processes finished and when the environment actually becomes available (which is the ~10 seconds you see there)
We could either add that new step or mark the last one as succeeded until the environment is truly available.

@nikmd23 what do you think makes more sense?

**Comment by lostintangent** [comment]
Closing this as resolved, since we’ve made a lot of improvements into this area.
