### ISSUE TITLE
Allow automating fork creation when provisioning a new environment

### ISSUE THREAD

**Issue by lostintangent** [MicrosoftDocs/vscodespaces#379]
Currently, our deep link allows automating the creation of an environment for a specific Git repo. However, there are situations where you might prefer the end-user actually creates a fork from the specified repo, so that they can commit/push changes to their own copy and submit PRs if/as-needed.

In particular, this would be valuable for open source scenarios (where the user wouldn’t likely have commit rights to the main repo), or education scenarios (where each student is working on a shared assignment, based on a “starting repo” they aren’t intended to modify).

While the user could manually create the fork and then add the new git remote, that degrades the rapid/“one-click” onboarding value prop that we’re trying to enable with VSO. That said, we should explore a mechanism for the deep link to indicate that the environment should fork the repo and then clone the fork. Or maybe we could detect that this is the right behavior somehow? (e.g. seeing that the end-user doesn’t have permission to commit to the specified repo).

In addition to allowing this behavior to be specified in the deep link URL, we should also explore adding an option to the new environment form, that allows the end-user to explicitly request a fork be created for the specified repo.

**Comment by anthonychu** [comment]
Similar to forking, it would be awesome to be able to deep link to a [template repo](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).

The behavior would be slightly different than cloning. A Codespace is created with the files in the repo as the first commit. The repo exists in the Codespace only and there's no fork created on GitHub.

This would be super useful for any quickstart or tutorial in Microsoft Docs. _"Install all of these prerequisites on your computer, OR click this magic link for a VS Codespace with everything you need to get started."_

The specific scenario I'm thinking of is someone just created an empty Azure Functions app in the portal. We want to be able to send them to a Codespace that's been configured for their type of function app using a template repo containing a dev container definition and starter files (and [CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour)!).

/cc @nikmd23

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and this experience is already available as part of the GitHub experience 👍
