### ISSUE TITLE
It is hard to leave feedback on VSO

### ISSUE THREAD

**Issue by loic-sharma** [MicrosoftDocs/vscodespaces#38]
Hi,

There's no way to leave feedback from the "homepage" of Visual Studio Online:

![image](https://user-images.githubusercontent.com/737941/68231289-9f63fa80-ffaf-11e9-80ae-236935d2a61a.png)

Also, the feedback button on online.visualstudio.com goes to Twitter. Should it send customers to this GitHub repository instead? I had a hard time finding this repository, I had to hunt through blog posts to find it.

![image](https://user-images.githubusercontent.com/737941/68138921-20eb5800-fede-11e9-89b5-db0c38948581.png)

Best,
Loic

**Comment by lostintangent** [comment]
@loic-sharma This is great feedback! We’ll use this issue to track progress on making it easier to connect with the VSO team 👍

**Comment by abuchholtzau** [comment]
Hey @loic-sharma, can you tell us what type of feedback you were trying to leave? For example, was it about creating an environment, working inside it, etc?

Thanks!

**Comment by loic-sharma** [comment]
It's been a few months, so I'm a little fuzzy on the details now. I believe I ran into several errors while trying to setup and then work inside a .NET Core environment.

**Comment by lostintangent** [comment]
Closing this issue, now that we're transitioning [Codespaces to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and therefore, will invest in a better feedback experience from github.com as opposed to our current online.visualstudio.com portal. Thanks!
