### ISSUE TITLE
Is there any way to get the port forwarding URL?

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDocs/vscodespaces#383]
When forwarding ports, is there any way to get the `...app.online.visualstudio.com` url that is used to access the forwarded port?

I am trying to get a repo set up for browser access in VSOnline and can override the base url that my web app uses, so it would help to be able to get the URL used for accessing the forwarded port so that I can configure that. Happy to get via env var or read from file.

Thanks!

**Comment by plisy** [comment]
No, not yet. We are working on a way to make this possible in the future.

Would you mind telling us more about how you imagine this would work?

The domain is different per forwarded port and right now it also changes after the environment is suspended and started again.

**Comment by lostintangent** [comment]
If you run “npx codespaces-port <port>”, that will give you the URL of the port. That said, this only works for GitHub Codespaces, which is what we’re currently consolidating Codespaces into. I’m going to close this for now, but please let us know if the above workaround isn’t sufficient for your use case. Thanks!
