### ISSUE TITLE
Document deep link capabilities

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#385]
VSO supports the ability to craft a deep link at https://online.visualstudio.com/environments/new

Supported URL parameters include:

- `name` for specifying the environment name
- `repo` for specifying the environment's repository URL
- `instanceType` for specifying the environment's instance type (standardLinux | premiumLinux)
- `plan` for specifying the billing plan. (NOTE: The billing plan must have been already created by the user) 

For example, this URL: https://online.visualstudio.com/environments/new?name=Ballpark%20Tracker&repo=nikmd23/ballpark-tracker

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal.
