### ISSUE TITLE
vso start --service requires GUI for windows

### ISSUE THREAD

**Issue by OneCyrus** [MicrosoftDocs/vscodespaces#399]
running the command over ssh fails at displaying the login window

![image](https://user-images.githubusercontent.com/7747800/78980185-ac1bea00-7b1d-11ea-96d8-20c90c952cd1.png)

**Comment by taiyosogawa** [comment]
@OneCyrus, thank you for reporting this issue. We should have included this in our docs, but Windows with the service option does currently require a GUI. We'll work on ensuring it is fully functional over SSH and post here when it is available.
