### ISSUE TITLE
code -n aDirectory/ opens a blank page

### ISSUE THREAD

**Issue by davide-rota** [MicrosoftDocs/vscodespaces#401]
**Repro**

- Open VS Online environment in Edge (Version 83.0.474.0 (Official build) dev (64-bit)) on ARM -> `https://online.visualstudio.com/environment/<env-guid>`
- Open terminal and type `code -n aDirectory/ `
- Edge opens a new Tab that remains  blank `https://online.visualstudio.com/environment/<env-guid>?folder=<url_encoded_path>`
- If you copy/paste the url in yet another Tab it works

Tracking prevention is "Balanced" default in Edge and the VS Online site is also whitelisted but it doesn't seem to make a difference.

[Short repro here -Screen Recording- ](https://1drv.ms/v/s!Agn9E-HTE7F-hvVnfqPTxlQzOgkJ-g?e=0bZBsQ)

**Comment by davide-rota** [comment]
Also (probably related) `code -r aDirectory/` reload inside the same window **but** sometimes (often at the first attempt) reload in the same folder previously opened instead of the one specified in the command (`aDirectory/`)

**Comment by srivatsn** [comment]
@legomushroom @plisy @klvnraju - any idea what's going on here?

**Comment by legomushroom** [comment]
I think that is the same prerender issue that @lostintangent recently hit, - if you then open the same URL in another tab, it works just fine. 

https://codepen.io/lostintangent/pen/ZEGgrYV

We need to investigate how to prevent the chromium browsers from erroneously prerender our pages without degrading the performance.

**Comment by lostintangent** [comment]
Closing this as resolved, since I just verified that `code -n` behaves as expected. Please re-open this if you're still encountering an issue. Thanks!
