### ISSUE TITLE
Can't restart vso using Bring your Own Machine

### ISSUE THREAD

**Issue by jaredpar** [MicrosoftDocs/vscodespaces#406]
Following the instructions on [this blog post](https://devblogs.microsoft.com/visualstudio/bring-your-own-machine-to-visual-studio-online/) I hooked up one of my headless machines to the VSO service. I then was successfully using VS Code from a different machine to connect to it and do my coding. This worked fantastic. 

The headless machine rebooted last night and this night I was unable to connect with VS Code. That was somewhat expected given that I had not started `vso` in the service mode. So I remote desktop'd into the headless machine and attempted to restart the `vso` tools but ran into the following error:

``` cmd
c:\VSOnline>.\vso start
[2020-04-15 15:15:11.438 CLI I] vso v1.0.2005.59801 (pid: 16104)
[2020-04-15 15:15:11.971 CLI E] [!ERROR] An environment is already registered on this machine with ID: 8e965dac-24ea-45c7-880b-99ed710769da
```

This seemed to be a blocking error. I poked around the help text for `vso start` but couldn't find any obvious way to get the service running again. I went to the VSO resource group in my azure portal, grabbed the full subscription moniker and tried passing that via `vso start -s ...` but ran into the same error. 

I was eventually able to get this working but I had to do a combination of `vso stop` followed by `vso start`. That is unfortunate because it requires multiple Azure device login attempts. 

Is there a way to "restart" the service that I'm missing here?

**Comment by taiyosogawa** [comment]
@jaredpar, thanks for trying out self-hosted environments and providing this feedback. At the moment, running `vso stop` and `vso start` again is the only option, but we are working on improving that experience in a few ways. We can use this issue to track a `vso restore` option and I just created #410 to remove the need for multiple sign-ins.

In general, we're working on improving our components to self-repair more intelligently, but we'll be able to get a restore tool out a bit quicker.

**Comment by jaredpar** [comment]
@taiyosogawa 

Thanks for the info. I'll just keep using `stop` and `start` then when needed. That machine doesn't reboot very often so it's not a big issue. Understand this is a new story and will have a few speed bumps to get going.

Really enjoying this feature. It's **much** easier to leverage this machine now that I just have to open VS Code and do my thing vs. having to remote desktop in and constantly switch desktops (pretty jarring). 

Problem though: too many VS code instances open now. Hard to keep track of where they're all pointing to 😄

**Comment by taiyosogawa** [comment]
Glad that worked and I really appreciate the feedback, so keep it coming! 

And I know what you mean about too many VS code instances 😛

**Comment by 2percentsilk** [comment]
Given [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) and self-hosted support will be retired on November 20, 2020, we are not scheduling further investment in this service and will be closing this issue. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.

Thank you for participating in our public preview and providing this feedback!
