### ISSUE TITLE
Cannot start as non-admin after starting as admin

### ISSUE THREAD

**Issue by jaredpar** [MicrosoftDocs/vscodespaces#420]
Acquired the vso tools following the instructions on [this blog post](https://devblogs.microsoft.com/visualstudio/bring-your-own-machine-to-visual-studio-online/).

After running the tools as a non-service I decided to attempt to run it as a service so that it would persist after machine reboots. First I attempted to go through `vso start` again but choose the service option. This lead to an error around permissions which I interpreted as "ah I need to run this as admin". 

Next I opened an Admin CMD shell, went through `vso start` again, chose service but that ended up failing due to my account not having "login as service" authority. That's unfortunate but okay I can just run this as a normal service and deal with reboots for now. 

Next I opened a non-Admin CMD shell, went through `vso start` again and I end up with the following:

```cmd
[2020-04-20 18:25:16.136 CLI I] Will run as a process
[2020-04-20 18:25:16.494 CLI I] A VSO plan is required to register your environment.
[2020-04-20 18:25:16.500 CLI I] Using VSO plan: ...
Enter an environment name or blank to use [JAREDPAR06]:
[2020-04-20 18:25:18.626 CLI I] Creating your environment...
[2020-04-20 18:25:23.544 CLI I] Saving local configurations...
[2020-04-20 18:25:23.967 CLI I] Authenticating...
[2020-04-20 18:25:24.008 CLI E] [!ERROR] Access to the path is denied.
C:\vsonline> ls
```

My assumption here is that `vso start` created a file on my machine which is now marked as admin and my attempt to write it from a non-admin environment is just a simple permission error.  Then again digging through my machine I couldn't find an obvious file this could be (mostly dug into `%LOCALAPPDATA%`). 

At this point though it is a blocker because I don't want to have my VSO connections be in admin mode when I connect. Generally I dev as non-admin.

**Comment by taiyosogawa** [comment]
Thanks @jaredpar! I was able to repro this and am putting out a code change now. It should be publicly available next week. I'll update again when it has been rolled out.

**Comment by jaredpar** [comment]
Is there anything I can do short term to workaround this? A file I can delete for example?

**Comment by taiyosogawa** [comment]
Sorry - should have posted that!

If the issue you're seeing is the same as mine, then I believe it is actually an RPC pipe issue. You should see a `vsls-agent` process with the argument `--pipe "VSLS-SH"` running. Try killing that process and running again.

If that's not it, just let me know. I'm working on several clean-up improvements this week.

**Comment by jaredpar** [comment]
Thanks. That seems to have unblocked me and I'm good to go again. 

As for updates. How will updates to the script bundle I downloaded occur? Will they be automatic or will I need to manually update from time to time? If it's the latter how do I know when to grab a new release?
