### ISSUE TITLE
Port url not working

### ISSUE THREAD

**Issue by karenyoseff** [MicrosoftDocs/vscodespaces#429]
Hello!
I am working with visual studio code Cloud, and opening the port in the browser doesnt work, this is in Firefox, because I actually tryed to log in on chrome and I couldn't log in at all.
 Maybe this is helpful to fix some errors!
Thanks you!

**Comment by lostintangent** [comment]
We've made numerous fixes to our port forwarding experience, so I'm going to close this as resolved. That said, if you're still running into problems, please re-open this and we'll try to investigate it. Thanks!
