### ISSUE TITLE
PWA-ify VS Online

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vscodespaces#43]
Currently, I can personally use VS Online as an installed desktop application. However, it doesn't seem like full PWA functionality is present in the Public Preview at launch.

My strongest belief of the utility of VS Online is the intersection of Web Applications and Desktop Applications via Desktop PWAs. VS Online is a *perfect* use case for Desktop PWAs.

It would be truly awesome to see it PWA-ified before it exits public preview ❤️

**Comment by plisy** [comment]
Thank you for reaching out. 

PWA support is definitely on our radar and we will be adding it before being generally available.

**Comment by kieferrm** [comment]
In the meantime, on Chrome and the Chrome-based Edge you can install the environment-specific PWA today.

**Comment by bnb** [comment]
Yep, I've got the Chrome-based Edge and it works just fine which is largely why I was hoping it'd be non-trivial to ship. Glad to see that it's on the roadmap before GA ❤️

**Comment by nikmd23** [comment]
@bnb, out of curiosity, can you tell me a bit more about your desire to use the PWA (as opposed to installing VS Code desktop)?

**Comment by bpasero** [comment]
@nikmd23 I can maybe chime in from my pov: on my iPad Pro for example, I cannot install VSO onto my homescreen to get a nice app-like experience. I think PWA is really great for devices that otherwise cannot install VSCode desktop native.

**Comment by tclzcja** [comment]
Yeah ditto above. The major reason why I'm into the PWA idea is that VSO is the only solution we have on iPad or mobile. There's no way we can install VSC on iPad and even we can do it some day in the future, other local dev components are still unavailable there, like database or Node.js.

So if I want to code on an iPad, or on my cellphone and project it to a screen, VSO is the only solution so far. That's why I think PWA is important.

Plus, if Apple finally welcome PWA into the App Store in 2050, it'll be great to see VSO there. Yep.

**Comment by bnb** [comment]
A few things, some previously and some currently relevant:

- Using VS Online in restricted environments as a Desktop-like app via Desktop PWAs. In college, we were hard blocked from installing anything on the computers - I couldn’t instal Node.js or text editors because they were both installed via executables. Desktop PWAs would have gotten around that and persisted since they were already an “installed” app.
- Use on Chromebooks and Android devices. I know you can now install Linux apps on Chromebooks, but the point of a Chromebooks *to me* to is to just have a web browser as a computer - as such, aims avoid Linux apps in favor of PWAs. Additionally, PWA support is being slowly chipped away at by Apple for iOS / iPad OS.
- Performance. On low-end devices like the $200 laptops from Walmart I learned to code on, every ounce of memory and CPU cycle counts. Introducing this as a PWA let’s me have a desktop experience without having to run an additional instance of Chromium.
- Experience. At this point, I set up as many of my day-to-day sites as PWAs as possible. YouTube/YouTube Music, Twitter, Destiny Item Manager, D&D Beyond. I will use VSO often, and being able to have it as a discrete app rather than a tab enables me to manage my system better in the same way that having an Electron app does - fewer tabs, improved shortcuts, direct opening from Alfred/Windows Search, and less distracting browser chrome.

**Comment by legomushroom** [comment]
We got the same feedback a lot during the Ignite, the main scenario is to have app-like experience and the quick access to the VSO on tablets.

**Comment by plisy** [comment]
@bnb Do you think it would be better for you to have one VSO PWA or have one PWA per environment?

**Comment by bnb** [comment]
@plisy that is a *really* good question. Personally, I’m definitely seeing myself spinning up dozens of environments over weeks/months and wouldn’t want dozens of PWAs.

Currently if I install the site as an app, I still see the dashboard. I’ve actually kind of enjoyed that, though it’s definitely a bit of an experience breaker given the jump to the VS Code UI.

Perhaps having an environment picker as an extension to connect to the back-ends that can be used in both the PWA and VS Code would be an effective approach to solve this problem?

**Comment by bnb** [comment]
Has there been any update on this @pilsy?

**Comment by plisy** [comment]
@bnb no, not yet. For security purposes we are putting every environment on it's own domain, so PWA support needs to be specified differently than I anticipated before.

**Comment by VincentDondain** [comment]
Codespaces now supports Chrome / Edge PWA 🎉 

You should see the install button in the URL bar of those browsers.

**Comment by bnb** [comment]
@VincentDondain has this been deployed to GitHub Codespaces yet? I'm not seeing it 🤔

**Comment by bnb** [comment]
Ah, nevermind - it just didn't show up on the loading screen.
