### ISSUE TITLE
Resources are sent without caching

### ISSUE THREAD

**Issue by bpasero** [MicrosoftDocs/vscodespaces#437]
At least the request looks like it:
![80506498-f7375900-8975-11ea-90eb-bf99d2895b62](https://user-images.githubusercontent.com/746020/80507985-51abc780-892c-11ea-8551-3ad8fb7f7489.png)

![image](https://user-images.githubusercontent.com/900690/80506566-133afa80-8976-11ea-8dc0-5213fec735d3.png)

**Comment by lostintangent** [comment]
Closing this as resolved per github/codespaces#457. @jkeech @plisy @legomushroom please re-open this if there's outstanding work here to track. Thanks!
