### ISSUE TITLE
Cannot debug vscode extension

### ISSUE THREAD

**Issue by bpasero** [MicrosoftDocs/vscodespaces#438]
* create repo from https://github.com/bpasero/test-ts.git
* add a breakpoint into `vscode.window.showInformationMessage`
* Run
* execute the command "Hello World"

=> 🐛 breakpoint is not hit

**Comment by lostintangent** [comment]
I just tried this in the latest bits and the breakpoint was hit as expected 👍  So I'm going to close this as resolved, but please re-open it if you're still running into issues. Thanks!
