### ISSUE TITLE
Creation Log appears to be stuck at "Initialize Environment" even though the environment appears to be already initialized

### ISSUE THREAD

**Issue by HouzuoGuo** [MicrosoftDocs/vscodespaces#441]
Hello!

My environment was launched this way:
![image](https://user-images.githubusercontent.com/563872/80583667-31a60200-8a19-11ea-9aa2-59cd35ce480d.png)

Both repository and dotfiles repository point to https://github.com/HouzuoGuo/vsonline-config

The environment starts succesfully, and within couple of minutes it finished installation of plugins according to `devcontainer.json`, and `install.sh` has already run and exited:

![image](https://user-images.githubusercontent.com/563872/80583616-1cc96e80-8a19-11ea-8e37-fa811f42da91.png)

That should be it for the environment initialisation - everything seems to be ready. However, the Creation Log appears stuck and won't show the usual green checkmarks.

BTW - very well done with bringing VS Code online! It's going to be my daily driver soon.

**Comment by lostintangent** [comment]
Closing this as resolved, since we’ve made a lot of improvements in this area since it was filed. Please re-open this issue if you’re still experiencing problems. Thanks!
