### ISSUE TITLE
Locking Environments

### ISSUE THREAD

**Issue by bnb** [MicrosoftDocs/vscodespaces#445]
I just accidentally deleted an environment that I didn't intend to delete because I was working on autopilot and deleted the one in the first position. 

While it's frustrating for me, it should be okay - I don't think there was too much uncommitted work in that one (it's the one I was actually working from). However, I knew that I had no intent to delete that one and wish the ability had been taken away from me.

This could be reasonably solved by introducing the ability to "lock" an environment so it can't be deleted. Additionally, it could be interesting to also be able to lock the settings of the environment, though it would be wonderful if those were opt-in on top of a basic level of locking that simply prevents deletion.

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal. If this is something folks would like to see, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
