### ISSUE TITLE
Self Hosted fails to flip to available

### ISSUE THREAD

**Issue by gro1m** [MicrosoftDocs/vscodespaces#453]
I would like to ask if it is possible to connect Visual Studio Codespaces to a Compute Target? It seems that with Visual Studio Code and the Remote SSH Extension (Reference: https://code.visualstudio.com/docs/remote/ssh) this would be possible, but does not seem to be configured to be installable on the remote server that Visual Studio Codespaces is running on. Is there some other way to accomplish this or is that a misconfiguration on my side?
Thank you!
Cheers, Michael

**Comment by abuchholtzau** [comment]
Hi there!
I think you might want to try out our [self-hosting service](https://docs.microsoft.com/en-us/visualstudio/online/how-to/self-hosting-cli#known-issues) for this scenario. By installing our CLI and running the agent, it will allow you to register the VM and then access it through VS Code with the Codespaces UI or through our web portal.

**Comment by gro1m** [comment]
I tried it out and successfully installed vso on the Compute Target in the JupyterLab Terminal, but somehow the creation of the vm fails. Neither 
```vso start --service```
nor
```vso start --service -s <subscription_id> -r <resource_group_id> -n <name>```
worked. In both cases it tries for one hour to create the registration (I see the creating phase on https://online.visualstudio.com/environments), but in the end there's a creation failed on https://online.visualstudio.com/environments. Can you give me any hints on what the issue is here or can I provide you with more information (I do not know where to get any debug info)?
 Thank you very much!

**Comment by taiyosogawa** [comment]
@gro1m thanks for trying that out and reporting the issue. Logs are located in the `VSFeedbackVSRTCLogs` folder in your temp directory. Could you try `grep error *` in that folder to see if there was anything logged?

**Comment by taiyosogawa** [comment]
I changed the title of the issue to reflect the latest issue - hope that is ok!

**Comment by gro1m** [comment]
Thank you very much, there seems to be an authorization issue.
The output of the grep command:
```bash
grep Error * #(N.B. case-sensitive -> it must be Error)
20200505_131218.1_CLI.log:[2020-05-05 14:18:07.535 CLI E] [!ERROR] Error calling HTTP GET at 'https://online.visualstudio.com/api/v1/environments/22f8cca1-d4eb-45fc-b00d-5fb802b04994' ErrorCode : Unauthorized
20200505_143233.1_CLI.log:[2020-05-05 15:01:19.903 CLI E] [!ERROR] Error calling HTTP GET at 'https://online.visualstudio.com/api/v1/environments/d4fe1f5b-a2dc-4074-b4f4-57902cbe444b' ErrorCode : Unauthorized
20200506_071831.1_CLI.log:[2020-05-06 08:24:04.174 CLI E] [!ERROR] Error calling HTTP GET at 'https://online.visualstudio.com/api/v1/environments/d9d70379-a5e5-4869-ae6a-d36615fee480' ErrorCode : Unauthorized
```
and the history of `vso start --service`, the content of  error log *20200506_071831.1_CLI.log*, respectively:
```
[2020-05-06 07:18:31.168 CLI I] vso v1.0.1998.63218 (pid: 53664)
[2020-05-06 07:18:31.509 CLI I] Authenticating...
[2020-05-06 07:19:05.208 CLI I] A VSO plan is required to register your environment.
[2020-05-06 07:19:05.211 CLI I] Using VSO plan: /subscriptions/<blanked>/resourceGroups/<blanked>/providers/Microsoft.VSOnline/plans/vso-plan-westeurope
[2020-05-06 07:19:36.979 CLI I] Creating your environment...
[2020-05-06 07:19:43.461 CLI I] Saving local configurations...
[2020-05-06 07:19:43.535 CLI I] Authenticating...
[2020-05-06 07:19:44.982 CLI I] Starting agent...
[2020-05-06 07:19:44.983 CLI I] Creating service...
[2020-05-06 07:19:44.991 CLI I] Created service vso.service
[2020-05-06 07:19:44.991 CLI I] Starting service vso.service...
[2020-05-06 07:20:00.785 CLI I] Waiting for environment to become available...
[2020-05-06 08:24:04.174 CLI E] [!ERROR] Error calling HTTP GET at 'https://online.visualstudio.com/api/v1/environments/d9d70379-a5e5-4869-ae6a-d36615fee480' ErrorCode : Unauthorized
```
I blanked subscription and resource group name. 
Could you maybe point me to what kind of authorization problem that could be? Authentication via portal worked fine.

**Comment by gro1m** [comment]
I have some more information for you:)
Executing vso start in JupyterLab and denying a persistent service/daemon actually leds me sign in to Visual Studio Codespaces.

```bash
azureuser@vm4:/mnt/batch/tasks/shared/LS_root/mounts/clusters/vm4/code$ vso start
[2020-05-08 07:16:32.148 CLI I] vso v1.0.1998.63218 (pid: 8992)
[2020-05-08 07:16:32.428 CLI I] Authenticating...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <blanked> to authenticate.
Would you like to run as a persistent service/daemon? [Y/n]: n
[2020-05-08 07:17:07.347 CLI I] Will run as a process
[2020-05-08 07:17:07.431 CLI I] A VSO plan is required to register your environment.
[2020-05-08 07:17:07.433 CLI I] Using VSO plan: /subscriptions/<blanked>/resourceGroups/<blanked>/providers/Microsoft.VSOnline/plans/vso-plan-westeurope
Enter an environment name or blank to use [vm4]: 
[2020-05-08 07:17:09.822 CLI I] Creating your environment...
[2020-05-08 07:17:11.243 CLI I] Saving local configurations...
[2020-05-08 07:17:11.321 CLI I] Authenticating...
[2020-05-08 07:17:12.984 CLI I] Waiting for environment to become available...
[2020-05-08 07:17:17.197 CLI I] All done! Connect: https://online.visualstudio.com/environment/<blanked>
```bash

Opening https://online.visualstudio.com/environment/<blanked>,  I then run into this problems in Visual Studio Codespaces:
<img width="960" alt="vso_compute_target_problems" src="https://user-images.githubusercontent.com/29672144/81382199-4c116700-910e-11ea-96f1-030440739a3d.PNG">

**Comment by taiyosogawa** [comment]
@gro1m, sorry I hadn't gotten to your first message. 

I'm glad you were able to get it to work eventually. Running as a process is generally less likely to present issues because it is the simpler of the two options, so it was a good thing to try. However, I am a little skeptical that it would cause that unauthorized error you saw. I am going to look at our service logs to see if I can get some more information.

**Comment by taiyosogawa** [comment]
@gro1m, it looks like the 401 occurred after many successful polling attempts, so that error was an indirect symptom of the problem at hand.

Up until that 401, the polling was working, but the codespace failed to flip to available because the service had not received any signal from the independently running agent.

If you're fine running as a process, feel free to close out this issue. If you'd like to troubleshoot the service option, we can work with you on that. The next thing I would do is to try registering as a service again, then check if `ps aux | grep vso` shows a process running with these args: `vso vmagent -t`

**Comment by legomushroom** [comment]
@taiyosogawa how much time passed before the 401s show up? Wondering if that is the token expires but still being used.

**Comment by taiyosogawa** [comment]
@legomushroom, good question. It would be highly unlikely for the polling requests to use an expired token because it is from the device login flow which happens on every CLI invocation. These requests are not using tokens from the kechain cache.

**Comment by gro1m** [comment]
> @gro1m, it looks like the 401 occurred after many successful polling attempts, so that error was an indirect symptom of the problem at hand.
> 
> Up until that 401, the polling was working, but the codespace failed to flip to available because the service had not received any signal from the independently running agent.
> 
> If you're fine running as a process, feel free to close out this issue. If you'd like to troubleshoot the service option, we can work with you on that. The next thing I would do is to try registering as a service again, then check if `ps aux | grep vso` shows a process running with these args: `vso vmagent -t`

Returns: There is no such process `vso vmagent -t`
```bash
azureuser@vm4:/mnt/batch/tasks/shared/LS_root/mounts/clusters/vm4/code$ ps aux | grep vso
azureus+   5400  1.6  0.6 3511860 92536 pts/1   Sl+  08:39   0:02 vso start --service
azureus+   6184  0.0  0.0  12948  1024 pts/4    S+   08:42   0:00 grep --color=auto vso
azureuser@vm4:/mnt/batch/tasks/shared/LS_root/mounts/clusters/vm4/code$ 
```

**Comment by 2percentsilk** [comment]
@gro1m I'm going to close this issue since you seem to have been successful running self-hosted as a process and our team has limited capacity to assist with troubleshooting self-hosted as a service moving forward. 

To provide some more context, self-hosted support is being retired on November 20, 2020 as part of the [Visual Studio Codespaces transition to GitHub Codespaces](aka.ms/vscs-transition]. Self-hosted support is not currently included in the GitHub roadmap so the team is prioritizing work elsewhere in the service. You can join the conversation about the future of self-hosted over at [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/24).

Thanks for participating in our preview and providing feedback!
