### ISSUE TITLE
Startup console is hard to read and copy

### ISSUE THREAD

**Issue by avdi** [MicrosoftDocs/vscodespaces#481]
Meta issue spawned from filing #479: viewing the startup console output in order to debug and report was a hassle. The little console output frame isn't resizable, and the only way I could actually look it over was to click and drag from the bottom to the top, copy, and paste into a text file.

**Comment by abuchholtzau** [comment]
Thanks for the feedback @avdi. Just to clarify, you're talking about the console output in our Creation Tab right?
We've been discussing some ways to make errors easier to parse when they happen but it'd be great to hear from you what you think the right move would be. Is it just making the frame resizable or is there a better way you had in mind?

**Comment by avdi** [comment]
Some possibilities:
- Make it maximizable
- Make Ctrl-A work well (I *think* I had some trouble with this)
- Provide a link to the raw text of the output in its own page

**Comment by lostintangent** [comment]
Closing this as resolved, since we’ve redesigned the way we display the creation log. Please reopen this if you think the new experience could be improved. Thanks!

**Comment by mchelen-gov** [comment]
@lostintangent what does the new design look like? currently it still displays very small:
![image](https://user-images.githubusercontent.com/63597655/93235481-9dc89e80-f74b-11ea-8d76-fb2c2b7ca802.png)
