### ISSUE TITLE
Export VM Startup/Down, User Login/out log to Azure Monitor

### ISSUE THREAD

**Issue by dahatake** [MicrosoftDocs/vscodespaces#484]
These are very basic log audit request developer in Enterprise.
Is it exposed to Azure Monitor?

**Comment by taiyosogawa** [comment]
@dahatake, thank you very much for asking. I believe we are not yet integrated with Azure Monitor, but I have brought up your request. We'll keep this issue open as an enhancement request.

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so we'll be focusing on adding audit logs to the GitHub admin experience, as opposed to Azure. If folks have specific thoughts about this area, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
