### ISSUE TITLE
Stuck on "Connecting to the forwarded port..." despite web server being accessible from terminal

### ISSUE THREAD

**Issue by DanTup** [MicrosoftDocs/vscodespaces#485]
I'm reasonably sure that in the past the port forwarding worked for our web apps (because I got further than this, and hit https://github.com/MicrosoftDocs/vsonline/issues/164). However today it just hangs like this:

![Screenshot 2020-05-06 at 15 28 57](https://user-images.githubusercontent.com/1078012/81189405-6b917e00-8fae-11ea-87df-aa38f9e54e88.png)

Yet if I use `curl` in a terminal window in the VS Codespace window, it works fine:

![Screenshot 2020-05-06 at 15 29 15](https://user-images.githubusercontent.com/1078012/81189448-79470380-8fae-11ea-936d-80c6063399b6.png)

**Comment by taiyosogawa** [comment]
@plisy, @fara-nak, have you seen this issue occur before?

**Comment by fara-nak** [comment]
@DanTup would you please share what you see in the dev tool console?

**Comment by DanTup** [comment]
There's nothing in the dev console for the newly spawned window:

![Screenshot 2020-05-13 at 16 05 40](https://user-images.githubusercontent.com/1078012/81830304-cccbcb00-9533-11ea-93f9-3fff02273011.png)

There's also nothing in the network tab:

![Screenshot 2020-05-13 at 16 05 45](https://user-images.githubusercontent.com/1078012/81830346-d6553300-9533-11ea-9c5e-827f359820e1.png)

If I reload the page with the network tab open, the request sits "Pending":

![Screenshot 2020-05-13 at 16 06 01](https://user-images.githubusercontent.com/1078012/81830369-dfde9b00-9533-11ea-834e-138a1f321e02.png)

And the dev console for the editor window lists a few errors from xterm and sourcemaps, but nothing related:

![Screenshot 2020-05-13 at 16 06 52](https://user-images.githubusercontent.com/1078012/81830432-f2f16b00-9533-11ea-8300-5c3a88af9ac0.png)

The repo I'm using to test it is here:

https://github.com/DanTup/vsonline-flutter-web

The steps to repro are:

- Open that repo in Codespaces
- Wait for the notification ("Your packages are out of date") and click the Fetch them
- Wait for "Analyzing..." to disappear from the status bar, and all compile errors to disappear
- On the debug sidebar, click to start debugging
- Wait for the window to spawn

It's normal for the editor to be stuck on "Syncing files to device Web Server" because it's waiting for the app to load and the Dart Debug Chrome extension to be connected (but you can't do that until the app is able to load).

If you go to the Terminal and run `curl http://localhost:33777` (replacing the URL with the one shown in the debug console), you'll see that the server is responding fine there.

**Comment by lostintangent** [comment]
@plisy I just tried reproing this with the latest PFS, and I'm seeing the exact same issue as @DanTup. The port spins for a while and then eventually fails with a 502. Any ideas?

**Comment by plisy** [comment]
@lostintangent my best guess right now is it's not accepting connections on the host we try to use. A similar issue to what we saw with angular hot reloading.

I'm still investigating and I may be wrong here though.

**Comment by plisy** [comment]
Running the server as

``` sh
flutter run -d web-server --web-hostname=0.0.0.0
```
works. It takes a little time for the content to show up, but there's a lot of things that are happening in the meantime based on devtools.

**Comment by DanTup** [comment]
> Is the local server simply a "standard" HTTP-based server? Does it rely on the existence of the Chrome extension, or is that simply to enable debugging? I'm just trying to think about what could be tripping up our port forwarding service in this instance 🤔

Yep, just a standard server. It doesn't rely on the Chrome extension (we do need that for debugging, but we're not getting that far here).

It's been a while since I looked at this, so I can't remember if we're binding only to the loopback address. For VS Code Remoting, I think the port is tunnelled and therefore this was fine - but possibly that's not the case here? For GitPod I think I was passing `--web-hostname any`. I'll try that and re-test on the latest version of everything soon and post back.

**Comment by DanTup** [comment]
Yep, this works when using `--web-hostname any`. So this might be working as intended. I assumed there might be something tunnelling into the instance (like with VS Code - Containers) since a lot of dev servers tend to listen on the loopback IP, but if that's not the case feel free to close this.

Thanks!

**Comment by lostintangent** [comment]
Thanks for confirming that! Closing per the previous comment.
