### ISSUE TITLE
List Private Preview Instance Types for Wider Set of Users

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#495]
If/when there is an instance type in private preview (like the Windows based one currently), it'd be useful to list it in the drop down for users who are not in the private preview yet.

![image](https://user-images.githubusercontent.com/199026/81746050-73986480-946b-11ea-8585-46f64d76fc77.png)

Click on that instance type would notify the user that it's coming soon, and that they can sign up for the preview. 

It's hypothesized that this treatment will help increase engagement and learning about new instance types in a natural place that is unobtrusive to users.

+@acangialosi

**Comment by acangialosi** [comment]
Also we'd like to attract dogfooding from existing VSCS users to make sure we're getting balanced feedback from users already familiar with Linux Codespaces.

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and this experience isn't relevant to GitHub.
