### ISSUE TITLE
Run Python File button isn't displayed in VS Codespaces

### ISSUE THREAD

**Issue by luabud** [MicrosoftDocs/vscodespaces#505]
If you install the Python extension and open a Python file to activate it, you won't see the play button on the top right:

![image](https://user-images.githubusercontent.com/45497113/81997060-8e9ddc80-9603-11ea-8ad3-5dbd29f21569.png)

Clicking on the black square will run the file correctly, it just doesn't show the icon.

This is what shows on VS Code (local):
![image](https://user-images.githubusercontent.com/45497113/81997450-9dd15a00-9604-11ea-9c9d-b3cb4b07f080.png)

**Comment by jkeech** [comment]
@plisy is this a port forwarding connection issue for custom icons?

**Comment by luabud** [comment]
hey folks! any updates on this by any chance? 😊

**Comment by lostintangent** [comment]
Closing this issue as resolved 👍 Let us know if you're still running into any issues. Thanks!
