### ISSUE TITLE
Deep link doesn't work through login flow

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#512]
Reported by @GraemeMalcolm

---

When clicking a deep link to create a new codespace, if I'm not already signed in I get redirected to do so and the deep link parameters for creating the new workspace are lost. Pretty sure this used to work OK.

**Comment by jkeech** [comment]
@klvnraju, this is probably related to the new oauth redirection flow. I think we need to add the deep link param content via the state param or something else (store in local storage and retrieve after the sign in flow completes?, etc).

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so this experience is something that we'd need to add to github.com, as opposed to the online.visualstudio.com portal.
