### ISSUE TITLE
Theme not persisting?

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#513]
Reported by @GraemeMalcolm

---

If I set "window.autoDetectColorScheme": true and "workbench.colorTheme": "Default Light+", the new codespace remains in the default dark color theme until I refresh - and then on thr next refresh it resets back to the dark theme. Is there a way to make the color theme update without the user refreshing, and to persist?

**Comment by jkeech** [comment]
@GraemeMalcolm, how are you setting these settings? When I change themes in a Codespace, it applies immediately without a refresh.

**Comment by lostintangent** [comment]
This should now be resolved 👍 Please re-open if you're still running into issues. Thanks!
