### ISSUE TITLE
FailedToRegisterResourceProvider 

### ISSUE THREAD

**Issue by gro1m** [MicrosoftDocs/vscodespaces#520]
Although Microsoft.VSOnline was registered for the subscription that I wanted to create a *VSO Billing Plan* for, I got the error message `FailedToRegisterResourceProvider`. I managed to get it working by unregistering and then registering Microsoft.VSOnline again, but I guess this should work out-of-the-box. So I thought I make you aware of this issue.

**Comment by lostintangent** [comment]
@jkeech Any thoughts on this? Presumably, this shouldn't require users to perform a manual registration of the RP?

**Comment by lostintangent** [comment]
Actually, I'm going to close this as a duplicate of #281, and we can keep the conversation going from there. Thanks again for filing this!
