### ISSUE TITLE
Question: Timeline for certain features

### ISSUE THREAD

**Issue by gro1m** [MicrosoftDocs/vscodespaces#521]
I would like to have some guidance or timelines when some of the components below could be addressed or if they ever will be addressed, because I have to test if we should licence VS Online at our company.
- It would be nice if there could be a https-only connection from VS Online to registered Compute Target from Azure Machine Learning Workspace (WebSockets are not supported at our company I guess)
- It would be nice if different users could access the same VSO Plan. I tried that and it does not work with a Contributor role.  The current limit of 2 plans and 3 environments per subscription implies for me that in a subscription only 2 users can have 3 Jupyter Lab environments that can be connected to VSO. It would be nice if the number of users and number of environments would have a rather high limit (something like 20-50 users and 5 environments).
- vso start / vso stop: only enter credentials once per session. This has already been mentioned somewhere and is somewhat annoying, but not so limiting.

Is there any chance you can maybe give me a certain hint if this issues can be addressed and possibly a timeline, so I know about when I should check again. I do not want to be pushy, but without the above features (especially the first two), I do not think I will be able to make a valid point to licence your product.

**Comment by jkeech** [comment]
Hi @gro1m, can you clarify the first issue? Codespaces does not limit any sort of outbound https connections from the Codespace to any other internet-accessible endpoint. I'm not sure exactly what the scenario is here, but it sounds like it might be a feature request on the Azure Machine Learning side of things?

The second and thirds issues are in flight. There are no exact dates, but those should be landing over the next few months. See #146 for plan sharing. @taiyosogawa, is there an issue tracking the login credential caching? I searched but couldn't find one for that. I know it has been discussed before though.

**Comment by taiyosogawa** [comment]
There wasn't a tracking issue, but I just created #527 for the credential caching.

**Comment by gro1m** [comment]
Hi @jkeech 
Thank you for your elaborate and very informative answer.
I had to realize that I got it wrong with the first issue, it is really our company's connection to Visual Studio Codespaces and the Compute Target (and not the connection from Visual Studio Codespaces to the Compute Target and vice versa) that does not work and I think we can resolve this when we decide to licence VSO definitively. Of course another solution would be to connect to a web-browser in Azure. But as far as I see the only solution would be to run that in a Virtual Machine. And this would need an RDP connection (and this blocked inside our company) to Azure Bastion (for authentication) to a Virtual Machine with a Windows OS installed.

**Comment by jkeech** [comment]
@gro1m, Thanks for the details. It sounds like you might be describing a scenario where the compute target is inside of a VNET and isolated at the network level from the public internet. If so, upcoming VNET support over the next couple months could help. The VNET support will allow you to attach a Codespace to a private VNET in your subscription, which could be the same VNET where the compute target is running. This would normally allow them to reach each other (depending on what sort of Network Security Group policies are in place on your network).

**Comment by gro1m** [comment]
@jkeech Yes, that is it: If the Codespace and the compute target is in the same VNET that would be perfect:)

**Comment by lostintangent** [comment]
Closing this, now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so we'll be sharing our roadmap as part of the GitHub public roadmap moving forward. If folks have any specific questions, please share that feedback on the [GitHub Support Community](https://github.community/c/codespaces-beta/45). Thanks!
