### ISSUE TITLE
Timeout while cloning private repository

### ISSUE THREAD

**Issue by cmbrose** [MicrosoftDocs/vscodespaces#528]
Forking a new issue off #507

@lucamorelli reported this when trying to clone an Azure Dev Ops repo:

>I tried twice, first with an angular app and second with an asp.net core solution, but in both cases gives me error while cloning, timeout while cloning private repository

@lucamorelli can you provide the full error messages and also the codespace Ids (the guid in the browser Url).

cc @klvnraju

**Comment by lucamorelli** [comment]
https://online.visualstudio.com/environment/8f59df30-0aaf-482d-a4fa-9c8660e46507

the code editor continue to show this 

![image](https://user-images.githubusercontent.com/127777/82582307-26667200-9b92-11ea-88e7-c51c5b3f4d7f.png)

but if I open the main environtments page I see this

![image](https://user-images.githubusercontent.com/127777/82582537-83fabe80-9b92-11ea-9857-213a791aa4e9.png)

no errors in the log console

**Comment by lostintangent** [comment]
@cmbrose Is this still an issue that we're tracking? We've been dogfooding Codespaces with pretty large private repos lately, so I'm wondering if we resolved this issue already?

**Comment by lostintangent** [comment]
I'm going to close this as resolved, since we've re-worked how repo cloning works over the last few months, and this should be fixed. @jkeech please re-open this if I'm closing this prematurely. Thanks!
