### ISSUE TITLE
Infinite login loop

### ISSUE THREAD

**Issue by acgetchell** [MicrosoftDocs/vscodespaces#532]
I am logging in using my UC Davis campus account. It looks like it’s getting bounced due to our use of Duo 2-factor.

**Comment by lostintangent** [comment]
@legomushroom Any thoughts here? Is the use of MFA an issue here?

**Comment by legomushroom** [comment]
2FA should not be an issue unless that is some specific college 2FA step that blocks us so would be great to get more info.

@acgetchell what browser and what OS do you use to sign in? Can you provide more info on the issue so we can investigate?

**Comment by lostintangent** [comment]
Closing this as a duplicate of #75.
