### ISSUE TITLE
"UNRESPONSIVE extension host, 'ms-vsonline.vsonline' took 100% of 1190.855ms"

### ISSUE THREAD

**Issue by DanTup** [MicrosoftDocs/vscodespaces#546]
Not sure if this is the correct repo, but I had this when loading a project today. It's stable VS Code on Windows (in a standard local session).

![Untitled](https://user-images.githubusercontent.com/1078012/83068065-97f56300-a05f-11ea-86ab-41c3006160c8.png)

- [exthost-aea0b4.cpuprofile.txt](https://github.com/MicrosoftDocs/vsonline/files/4691566/exthost-aea0b4.cpuprofile.txt)
- [exthost-c503da.cpuprofile.txt](https://github.com/MicrosoftDocs/vsonline/files/4691567/exthost-c503da.cpuprofile.txt)

I tried opening the profiles, but they seem to online include a few ms:

![Untitled](https://user-images.githubusercontent.com/1078012/83068277-063a2580-a060-11ea-9d60-c70c37d14edb.png)

**Comment by taiyosogawa** [comment]
@DanTup, good to hear from you and thanks for reporting this. Could you verify the version of the Visual Studio Codespaces extension installed on VS Code stable?

**Comment by DanTup** [comment]
It's currently 1.0.2268, but I think that's auto-updated from your release the day after I posted this. I do have auto-updates enabled so I would expect it was the latest version at the time I posted.

(Actually, looks like that happening on my windows machine which I'm not on now - however the same applies, I have it auto-update the extensions and restart VS Code frequently so it wouldn't been the latest at the time).

**Comment by lostintangent** [comment]
We've made a bunch of improvements to the extension over the last few months, so I'm going to close this as resolved since we haven't heard any recent reports of this, and I can't repro it currently. Please re-open this if you're continuing to encounter issues. Thanks!
