### ISSUE TITLE
Opening self hosted codespace in Visual Studio code (native app) doesn't work behind corporate proxy.

### ISSUE THREAD

**Issue by darktears** [MicrosoftDocs/vscodespaces#553]
Hi,

I have a self hosted codespace that is setup to be persistent. I can access it through the browser (https://online.visualstudio.com/) and it loads just fine (the self hosted codespace is not behind the proxy).

However when I try to access my codespace on my native application (Windows or macOS) it doesn't work. I can sign in to Azure, I can select my plan, I can see the Visual Studio Online tab and I can see my self hosted environment. If I click to access it (that little plug button) then it connects but then fails with the error:

`Failed to connect to the remote extension host server (Error: Request failed with status code 400)`

I'm behind a corporate proxy server and I did setup my machine for that. VSCode has its proxy set in the settings (as a matter of fact everything else works, extensions can connect, ...). The computer also has the http_proxy and https_proxy variable set.

It seems that somewhere it doesn't respect the proxy settings.

**Comment by 2percentsilk** [comment]
Given [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) and self-hosted support will be retired on November 20, 2020, we are not scheduling further investment in this service and will be closing this issue. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.

Thank you for participating in our public preview and providing this feedback!
