### ISSUE TITLE
Visual theme not activated until page refresh, and not persisted

### ISSUE THREAD

**Issue by GraemeMalcolm** [MicrosoftDocs/vscodespaces#555]
Configuring a visual theme in devcontainer.json has no affect on the new environment until the user refreshes the browser. Then, if the session is ended on reconnection the theme is reset to the default dark theme (again until the browser is refreshed).

Config settings:
    "window.autoDetectColorScheme": true, # (also tried with false - same result)
    "workbench.colorTheme": "Default Light+"

**Comment by lostintangent** [comment]
This has been resolved! Let us know if you're still running into any issues. Thanks!
