### ISSUE TITLE
Local forwarded port number is off by one (even when not in use) and tooltip is incorrect

### ISSUE THREAD

**Issue by plisy** [MicrosoftDocs/vscodespaces#559]
1. Connect to a codespace.
1. Use the Codespace Details viewlet or the Codespaces: Forward Port command to forward a port. (Pick any port, it doesn't matter if there's actually a server running.)
1. Use the viewlet or the Codespaces: Copy Port URL command to copy the port URL. Paste somewhere else.
RESULT: The local port number is 1 greater than the remote port.
EXPECTED: Local and remote ports should be the same unless the local port is in use.

Also, hover over the item in the viewlet. The tooltip is supposed to show the remote and local port numbers.

RESULT: Tooltip shows remote and local port numbers are the same, even though the local port number is actually off by one.

This is not just a bug in copying the URL; the actual local port number is off by one: I was able to use that to connect to a server running in the codespace.

> Seems like both local port number and local port number + 1 are exposing the same service.

**Comment by fara-nak** [comment]
@plisy  for your first issue, i just tried in dev and prod and I can't repro, can we talk offline? 
for the second issue yes you are right the toolpit is not showing right local port. it should be fixed in the new PF UI. I will check and update here.

**Comment by plisy** [comment]
Did you test on desktop?

**Comment by fabiom-zz** [comment]
I've always experienced the port forward to be off by 1 for months. For example, if I request forward 8080, my computer would have its local 8081 forward to 8080 in Codespaces. This is happening using VS Code v1.46 with Codespaces extension version v1.0.2349. I tested web too but it is different for me since I'm not getting a true port forward, but instead a funky url.

**Comment by fabiom-zz** [comment]
I think now I understand what @plisy is saying, I'm seeing the same thing. I port forward on 8080 and indeed it is forwarded as expected. There is *one* Code.exe process listening to 8080 as indicated by `netstat -ano`:

`  TCP    127.0.0.1:8080         0.0.0.0:0              LISTENING       244`

Once I click on the port forward, the *second* forward on 8081 appears on a separate Code.exe process as indicated in `netstat-ano`:

`  TCP    0.0.0.0:8081           0.0.0.0:0              LISTENING       14680`

And like @plisy reported, tooltips do not match what is really happening.

**Comment by lostintangent** [comment]
This issue should be fixed. Please re-open if you're still running into this problem. Thanks!
