### ISSUE TITLE
cant create Codespace environment or share it to other users

### ISSUE THREAD

**Issue by mbigelowrexall** [MicrosoftDocs/vscodespaces#562]
Hi,

Our company is having issues starting to use Visual Studio Codespaces.

If I login and try to create the environment, I cannot because the Subscription dropdown is greyed out – it fetches nothing.
And when I get our Microsoft Azure admin to create the environment he is unable to share that to my login for me to use. 

Thanks

**Comment by jkeech** [comment]
Hi @mbigelowrexall! Are your accounts registered in multiple AAD tenants? Today we have a limitation where only the default tenant works (#39). It sounds like you might have a subscription created in a non-default tenant and no subscriptions in the default tenant for your account.

**Comment by mbigelowrexall** [comment]
All of our accounts are in the same AAD tenant

**Comment by lostintangent** [comment]
Closing this as a duplicate of #550, which allows us to consolidate the multi-tenant discussion in a single place. Thanks!
