### ISSUE TITLE
I cannot paste text in VS Codespaces running in browser

### ISSUE THREAD

**Issue by skleanthous** [MicrosoftDocs/vscodespaces#566]
Initially I couldn't copy text from VS Codespaces running in browser, but I added the keybinding and now I can copy text from VS Codespaces running in a browser, However, I cannot paste _into_ a file (any file), and I get the error `command 'editor.action.clipboardPasteAction' not found`. (see picture below):

![image](https://user-images.githubusercontent.com/8543464/83927260-4c8c3480-a784-11ea-93cb-ca45492a65de.png)

I am using a dockerfile to build the container (so not using one of the ready-made images), I don't know if that's important.

This is (obviously) a blocker for me.

**Comment by jkeech** [comment]
What browser and OS are you using?

**Comment by skleanthous** [comment]
I am using Chrome latest, on Windows 10. After posting I thought I'd reset the configuration, and so I removed the binding that I added about copying. This time I didn't get the error (which was that editor.action.clipboardCopyAction was not found) that I got when I first tried it, and now it seems to somehow be fixed. Not only I can copy (which I wasn't able to do before I set this keybinding), but somehow paste magically works now.

The kicker is that _with_ the editor.action.clipboardCopyAction set to Ctrl+C, for one of my codespaces paste didn't work _at all_, but for another it worked only when I pasted within the same document.

I can work now, but I'd say there is something weird going wrong.

**Comment by jkeech** [comment]
@skleanthous, thanks for the details. I agree that something weird is going wrong there. I'm glad it's working for you now, but let's keep this issue open for a bit and see if the problem reoccurs or if we can reproduce in another way. If it doesn't happen again, we will close the issue.

**Comment by skleanthous** [comment]
Just to be clear, I can easily reproduce the paste issue (I can't seem to reproduce the copy issue I initially had now). Once I set the binding for copy to `Ctrl+C`, paste stops working, and I get the error in the picture in my initial message. Also, it seems that the `editor.action.clipboardPasteAction` keybinding it entirely absent (not just clearled) from Code.

**Comment by lostintangent** [comment]
This has now been resolved! Let us know if you're running into any other issues. Thanks!
