### ISSUE TITLE
Codespaces extension adds global "fetch" to extension host

### ISSUE THREAD

**Issue by connor4312** [MicrosoftDocs/vscodespaces#567]
It seems that recently the Codespaces extension started to import [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) which adds a global in node.

I found this because @eamodio reported that breakpoints stopped working in our new JavaScript debugger. It turns out that the [source-map](https://www.npmjs.com/package/source-map) library uses the presence of global "fetch" as an indicator of us running in the browser, which was then failing when running in Node.js.

This is not a very good detection for source-map to use and of course other extensions could pollute in the same way, but codespaces should also avoid doing so.

**Comment by lostintangent** [comment]
@plisy Any updates on this? It is still a problem?

**Comment by plisy** [comment]
I believe we fixed it with last week's release.
