### ISSUE TITLE
visual studio 2019 16.7 preview 2 codespace

### ISSUE THREAD

**Issue by vennim** [MicrosoftDocs/vscodespaces#571]
When I try to connect to a static codespace i get the error:
The 'VCManagePackage' package did not load correctly.
I tried repairing visual studio and reinstalling it.
My codespace works perfectly from visual studio code.

**Comment by jkeech** [comment]
When you say static Codespace, do you mean a self-hosted Codespace? If so, the Visual Studio client (currently in private preview) does not fully support self-hosted Codespaces today. Self-hosted Codespaces are usable from Visual Studio Code and from the web client (VS Code in the web).

**Comment by vennim** [comment]
thank you. Do you know when would self hosted codespaces will be supported in visual studio 2019?

**Comment by lostintangent** [comment]
We don't currently have any plans to support self-hosted Codespaces in Visual Studio, and so I'm going to close this as won't fix. If this is something you'd like to see us add to our backlog, it would be great if you could share that feedback [here](https://github.community/t/self-hosted-codespaces/131361/3). Thanks!
