### ISSUE TITLE
GitHub package registries don't work as docker image source

### ISSUE THREAD

**Issue by wpbrown** [MicrosoftDocs/vscodespaces#574]
The docs state that GitHub package-registry is a valid source for the docker `image` property:

> The name of an image in a public container registry (e.g. DockerHub, Azure Container Registry, [GitHub](https://github.com/features/package-registry)) that Codespaces should use to create the environment.

However even public registries fail due to auth:
```
Error response from daemon: Get https://docker.pkg.github.com/v2/.../manifests/latest: no basic auth credentials
```

**Comment by jkeech** [comment]
We do not currently support any form of auth for the docker image pull. GitHub Packages currently [requires auth, even for public image repositories](https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358), so it is not expected to work right now.

@nikmd23, can we get the docs updated to remove GitHub Packages until we support authenticated docker pulls?

**Comment by lostintangent** [comment]
We recently deployed a change that allows you to use GitHub Packages registries for Codespaces, so I'm going to close this as resolved 🚀 However, that only works from [GitHub Codespaces](https://github.com/features/codespaces), and so if you're using [Visual Studio Codespaces](https://online.visualstudio.com), I'd encourage you to sign up for the GitHub-native service, and we can get your into the beta. Thanks!
