### ISSUE TITLE
unable to log in with AAD

### ISSUE THREAD

**Issue by Helianthella** [MicrosoftDocs/vscodespaces#575]
I am suddenly unable to log in to my self-hosted Codespace [in the browser](https://online.visualstudio.com/login) that is registered with my Azure Active Directory account (@...onmicrosoft.com)

1. Navigate to https://online.visualstudio.com/environments
    - Get redirected to https://online.visualstudio.com/login
2. Click _Sign In_
    - Get redirected to login.microsoft.com
3. Sign in with the AAD account
    - Get redirected to https://online.visualstudio.com/aad-auth-callback#
    - Get redirected to https://online.visualstudio.com/login
4. Back to step 1

I am essentially stuck in an infinite login loop. This behaviour only started happening this week and using a regular, non-AAD microsoft account (@outlook.com) works fine

**Comment by Helianthella** [comment]
Using Chrome v85.0.4163.0 (dev channel)

Here is the network trace, encrypted for PGP key 0xcac9dcec039783bb (@klvnraju):
[online.visualstudio.com.har.asc](https://github.com/MicrosoftDocs/vsonline/files/4761707/online.visualstudio.com.har.asc.txt)

**Comment by klvnraju** [comment]
Thanks for the reply. I was not able to see the exact reason for failure in the network logs. (as the call most probably because the call happens in an iframe)
Can you please provide the console log as well? (We might have to add logging if the console log does not have the error logged)

**Comment by Helianthella** [comment]
@klvnraju 

![image](https://user-images.githubusercontent.com/3507758/84554855-eead9e80-ace7-11ea-9228-5515fd5f7dd6.png)

<details><summary>log (encrypted)</summary>
-----BEGIN PGP MESSAGE-----

hQIMA7EXBbPWZ7ZKARAAhX7VSqy1T52TQ/WtkUxTniXH/uz0dnAtufH821uta2Ak
sHs45nW82n8RYV153wZb2CSSeRhzMrnVt6wn6y/nZQZ/c3UKRPgozATl2wNabRY1
WrvN7btMBhIQMfCHkVI8gu+cr8lGY6JkKGmBDKUlTEvmjpktlUNFuXLdCOUm60wf
9F2q/P/0DTE0/BRpUMbjfIOxGxP7fW7d2I+5++s8s87tFmn4WUkXRI3g3q7bTQs6
w6Ff4ICSPpPsp+RVI4YnFNAZ5nbnJ/9bhll3obnxBZPwFzDMLKJofIIC3FUnwyS1
jYyPSexvByI/8Q5mB4LfsXzKPXeUZTh2pnPGSj32lmGuR/tJw0S3zdN3JCmin8N7
XUTdEIJFXzen2l9pPD439eETnlYcAYRdAEQ12iuKRHSZYW5atrsQmrvIeW0JtOtJ
JpnW+DXkl+gucsINzNA1yt8qD5i6ZePStlE7lKBuRfe6DYwRIfxWLSAftIPojNx8
0w4icY+0bChtL+sV6IeGR6xKoFzpnfBhK0TFhz8xsOwsrGeUTx3s6hSlHtpCUBJs
OA12QDtwf1veL4zaYhzOxyVTiF+ZobCLaXlBIAsIaoupl/qxl7+0pfqjwMXa9Vwg
OagRhVKOi09BA/xJKkMXgyfNh78umOk0zTX1rmiSe8n3sMtPn2aWhgtVqayPdqHS
6gFesoz8oPWB+L0gZeGqtJORk2y22oJkVyhTrUeDWO11TqN3FZts70m/3VRbmyJx
RsHSt0w+5hqml1axb4FtlZ1QIzpPWDn3Wgin6uaQC15oy/g9WoXp83CBOFX509CE
E4UMU+VtPo1Bo/IiXrsUv4m/nVNc+lOUuKYFTvNsc1t5DM6xlED1Jv0RCS+9g0my
KPkgQTNENtAYYfnhwS4rR5T3rhkv86Cd4hLADmiykcsfOTyOGlYHsdIyEzTGNm++
SMOrSbasLbkpvBtdfbP93MT1mTeVCEhkGxRQm+bBEaR5ydwr0GpNPKT/UHGDGi0w
7CvoSHwE2fAnnZRemCm0Zbih5y3TdnjfIWcjGDe9jzPvjFaoqCG80FTp2jn2YYe8
wX6AsqfhPj0+j2jnTB4nV8UZlle1GmCO6ginL3ZyBiFbP8MuRCnkiNfWOlcRkwI4
yRvKx7eDAEQq24cF2RgE593yhmtdWa1eG6l1dUByauRH2djgQSWg+gB2WKjWzzkn
bQGteaywB/sBu1H7d746qwrY2tYuSWhzaXgeols5mp1uYlvAB/KxodV4w7PPAslA
9frZTVLF3I/yqlcBAq6712I/YIkurSbbzLAB4o+TfdcrYYRjj2dwZiWB5dv1ZDbQ
QDi9aS82LnZ7bCQl9rwnEdrarMLeEjLYZSVu+ZJotxXSOj+O9xSr5l5GJGeTzKjr
Fk7ZJFcJTY8bfLxlLWMfVmv1K5C63qjJsPr5/QO025xPxiPI3dapY2fTc3kQC+fz
BJ78XgJHVxZ35u0G0FXNM/DrUmzMVuiA5HRSwAqqBOpv4bf2Kbztw2MG/yJ05j8t
Z6TCEfjYGy+gmr9O8UfZg8PgJpS6D3dfLQc0WSzBl+OWZ82MIVmnxDLpmTf/0OpW
TpCXEE/r+72NkToHHX2LXDJT9VSt2Fy7IJYjPrm/5iVQhmbwcvx1OKny1r5nRnDW
fQGoke4nQwkMorVuJdoXs0q79TUIVTonvewyh5kMym/93vcdyirh0+W/fI6Ji2FI
fOLqerDoe3i2vGItLZJWd8E8xKDvqwsCx7ONh92AoSVmTN68EzZJoZSvXbyBZqvc
zaiOdyQkmlukL+k5Z2jWuAeGcnRKMwM/XjAdvGBbSK8t2iBu7MEEyrUhKVg2Hzj3
1oeJdlft43dDVCbOFY5jDPxE38kDz9b6ZtnMYAe60He1pun38Ys4C9u/BLWnyfq3
Tmzvzq/a4GupSwDwBuAvM2axW124K1YObgznfSyc5RT5TJrcKKYFdOlV9OVBqAVg
GQ0WQhfZ7zdtDPCeZH4wb/s4+iIFdY0sfiPTIB0OmIN3NucJQfKtcEc1C+QlJIYG
0lAu1KBh8OR02lc6gMoNo3rBKHaL9MFkPGSY+jcL3ZBXA/tMa4nvl28jsvPuMkw/
V8iYLr8sbrEIn8x2JA8/74PqnEUxCAMloGlSFKWmBFNYe8EQ6FBZZbYb+3hUjo10
Ck7xoR4dC0EUwTwRf14gwmL9Nrvtn97szNYiDYJk45ZlQh5kbMmrtQHXh9qtFi2H
XMvh6rzEfpMnFCy7N5o9NsH0FmO7gBebGTcbO8iRP7MrXau4k8dY6gHC9H55acS7
fv3ArC2xZJwSs5JURn54rZ6RyzN+WoIq4OXxPc+hDmFk1NV+2CuZl+ed1/wj5//2
cKma964DrdQFR441C/pXBCK4iJMsy3XN3mr/p5IjryWFbBn6bcOdu7iu+Nuo6LY0
BsAaGYKyXcYe1zmcrYHRlkWQ0lm4Xjbg5STzOfIYcwFN6/raHkOG9Igo1sqxzy42
6aZ4zUeJiRIWtozjIAVmiAik5tZuqJh+wBTqURvSkdIi3G2QLTEijlOXRuN1UADZ
vLggTiX2HdGN6KJ7qvcjcpKEEea0fRDXDRVJy+zwyo5axhqNhroP7RQKELvMl+78
q1/pXDmUGC631ItzvRbXHCkuASw03a/MQL1kqvgnGi70y1k6Jsdoxciw/EpPEzYw
BqAcnyoFcXGqKBSuIABxdONrsdMusBvOrArY
=juMv
-----END PGP MESSAGE-----
</datails>

**Comment by dclayto1** [comment]
If it helps to know more people are experiencing this, I am as well. I was on the same Chrome version as @Helianthella and experiencing this, as well as still experiencing after updating to "Version 85.0.4170.0 (Official Build) dev (64-bit)"

**Comment by klvnraju** [comment]
Thanks for reporting this.
Are you also seeing the same console errors @Helianthella is seeing? (especially the cookies being blocked in future versions of chrome)

Please note that those are warnings, and do not conclusively say that is the reason for the failure.
We are adding additional logging which should say the reason for failure.

If you can close all browser instances of chrome and try logging in again. (We have seen some instances where this fixed the issue, It would help us understand if these two issues are different)

**Comment by klvnraju** [comment]
Can you please check if `Block third-party cookies` setting is on?
![image](https://user-images.githubusercontent.com/25800054/84844852-2d9d6600-b000-11ea-9b77-1b31196f1cbb.png)

**Comment by Helianthella** [comment]
In my case it isn't set to block third-party cookies (only does in Incognito)

![image](https://user-images.githubusercontent.com/3507758/84853163-91d61f00-b02c-11ea-8e89-7bc3c0f99eb7.png)

**Comment by dclayto1** [comment]
Sorry, forgot to respond. I was not seeing the warnings that @Helianthella was seeing, but I did have the 401 error log for that GET request to the "keychain-keys" endpoint.

However, this is how I do my primary development, so I needed a working environment and rolled-back to Chrome stable and everything is working again

**Comment by Helianthella** [comment]
I can confirm that downgrading (to chrome v84 in my case) fixes the issue for me too so this appears to be v85+ specific

**Comment by josundt** [comment]
I am also experiencing the same loop behavior. For me it also started around the time when this issue was created. I am using a AAD guest account which has the appropriate privileges in the Azure Subscription where the code space is hosted. 

Logging in with this user used to work fine, but suddenly stopped working.

I have tested logging in with the latest versions of Chrome, Edge (chromium) and Firefox, but the login loop happens in all of them.

Logging in through the auth code flow from the **VSCode Insiders Codespaces extension** also fails; the error message is _"Sign In: Partner context has not been set yet, please ensure you are signed in"_

**Comment by Helianthella** [comment]
my chrome v84 (beta channel) auto-updated to v85 and the bug came back
manually downgrading again to v84 solves the issue but this is not sustainable

**Comment by Helianthella** [comment]
As of 2020-08-02 I am no longer able to reproduce this behaviour so I guess it was fixed?
