### ISSUE TITLE
Unable to start and connect to existing environment.

### ISSUE THREAD

**Issue by halfnibble** [MicrosoftDocs/vscodespaces#581]
I have a group of students using VS Code Online (aka codespaces) for the quarter.

We have one environment for one student that will not start and therefore cannot be connected to. Everything looks fine in Azure, and the resourceGroup is correct. The account can create, start, and connect to new environments, but she cannot connect to her existing one (that has all her code).

Since this is likely a limited scenario or edge case, can someone message me on Teams or email to get more information about what is going on? Thanks.

Alias: jowedeki

**Comment by lostintangent** [comment]
We've made numerous improvements to the reliability of connecting to Codespaces, and so I'm going to close this as resolved. Please let us know if you're still running into issues, and we'll look into what might be going on. Thanks!
