### ISSUE TITLE
git credential manager failing

### ISSUE THREAD

**Issue by bartr** [MicrosoftDocs/vscodespaces#583]
/.vsonline/bin/vso gitCredential  is throwing an exception (see below) and I can't push to a repo that I have permission to.

- If I remove the credential manager from .gitconfig, I am able to push
- If I override the remote name with my userId:PAT, I am able to push

## Error

vsonline@codespaces ~/workspace/foo/ $ /.vsonline/bin/vso gitCredential
[CLI E] Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CloudEnvironments.CLI.Commands.GitCredentialHelperCommandStrategy.<>c__DisplayClass18_1.<<Register>b__1>d.MoveNext() in E:\A\_work\510\s\src\VSOnline\CLI\Commands\GitCredentialHelperCommandStrategy.cs:line 77
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\510\s\src\VSOnline\CLI\Program.cs:line 147
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CloudEnvironments.CLI.Commands.GitCredentialHelperCommandStrategy.<>c__DisplayClass18_1.<<Register>b__1>d.MoveNext() in E:\A\_work\510\s\src\VSOnline\CLI\Commands\GitCredentialHelperCommandStrategy.cs:line 77

**Comment by edgonmsft** [comment]
Hi Bart!

This is a strange issue, can you give me more context?

- Did it start failing at some point and used to work before?
- Can you send me how the git credential is configured? `git config --list`
- Is the repository public?
- Are you using web or desktop?

Thanks!

**Comment by bartr** [comment]
The repo in question is on a GitHub Teams site and I'm using my GitHub ID which is an admin on the repo. Note that my GH ID is enrolled in Microsoft Open Source which requires 2FA (not sure if that has any impact)

I just checked and I only see the problem when I try to push to that repo. I can push to my repos or our GH Enterprise repos without issues.

If I mark the repo private, VSO fails to create the Codespace because of permissions.

LMK if I can help debug - it seems like an edge case since it's just that one repo.  I'll try creating another repo in that GH Teams org and see if that works or not.

**Comment by edgonmsft** [comment]
2FA shouldn't have an impact. 

I assume you are using the web, can you try doing it from the desktop or another browser? Its possible that the token we have from when you authorized GitHub is not the correct one for that repo.

**Comment by bartr** [comment]
I tried from another browser and got prompted to login and authorize. It still didn't work.

It's not working on our github enterprise repos either and I know that was working last week. Not sure what's going on.

I can add you as a contributor to a test project in our GH Enterprise and you can try to duplicate if that helps.

**Comment by bartr** [comment]
https://github.com/retaildevcrews/vsotest

You should have an email invite for the repo. There's nothing there except a readme and an MIT license file.

I get the error on git push from the terminal

**Comment by edgonmsft** [comment]
Thanks!

I just tried it and managed to push from vscode desktop, but it failed from the web.

Let me take a closer look and get back to you.

**Comment by lostintangent** [comment]
We've made a lot of improvements to our Git credential manager over the last few months, and so I'm going to close this as resolved. Please re-open it if you're continuing to encounter problems. Thanks!
