### ISSUE TITLE
Default plan name and resource group still have "vso-" prefix

### ISSUE THREAD

**Issue by gregvanl** [MicrosoftDocs/vscodespaces#585]
Should auto-generated names be changed to use a prefix like "vsc-" to reflect the VS Online -> VS Codespaces rebranding?

![image](https://user-images.githubusercontent.com/12818376/84725740-2ca4ff80-af40-11ea-8bc0-62d2c56527a2.png)

**Comment by jkeech** [comment]
These changes have been deployed 🚀
