### ISSUE TITLE
Gatsby JS Development - Blank Screen on forwarding port

### ISSUE THREAD

**Issue by waywardm** [MicrosoftDocs/vscodespaces#588]
Regarding use of Gatsbyjs in VS Codespaces

I cannot seem to develop using the Gatsby Development command when it goes  to the forwarding port it is a blank screen. When you check the source it is loading the initial page but not injecting the code into the browser, as gatsbyjs is becoming ever more popular I would have thought this would need looking at, I have successfully managed using gitpod ide in the past.

**Comment by chkn** [comment]
Does Gatsbyjs use websockets? Our current port forwarding solution in the browser has a lot of limitations. For instance, websocket connections don't work (see #196). You can get around that by installing the Codespaces extension in VS Code on the desktop and connecting from there.

**Comment by ravikumarpasupuleti** [comment]
Is there a work around or fix for this to run gatsby projects?

**Comment by jkeech** [comment]
@ravikumarpasupuleti The workaround for now is to connect from desktop VS Code to the Codespace. Full port forwarding will work correctly there.

**Comment by ravikumarpasupuleti** [comment]
Thanks It worked @jkeech .

**Comment by lostintangent** [comment]
Closing this as a duplicate of #117.
