### ISSUE TITLE
VS Code extension repository quick pick example is vsonline-quickstart

### ISSUE THREAD

**Issue by gregvanl** [MicrosoftDocs/vscodespaces#597]
The quickstart repository has been renamed to vscodespaces-quickstart to align with the rebranding.

https://github.com/microsoft/vscodespaces-quickstart

The quickstart docs have been updated but the VS Code extension example should also be updated to vscodespaces-quickstart.

See "e.g. microsoft/vsonline-quickstart" text below:

![image](https://user-images.githubusercontent.com/12818376/85074874-1f6f5700-b172-11ea-87e2-535e5d53f67e.png)

**Comment by osortega** [comment]
Thanks for reporting this.
I'll be making the change shortly.
