### ISSUE TITLE
Unable to start/create the environment on vso-plan-southeastasia, again

### ISSUE THREAD

**Issue by tyamamushi** [MicrosoftDocs/vscodespaces#598]
Hello, my environment on vso-plan-southeastasia have come to unable to start as same as issues#343

**Comment by osortega** [comment]
Hello @tyamamushi , I'm sorry this happened again.
Do you see any logs under the developer tools?

cc/ @edgonmsft

**Comment by edgonmsft** [comment]
Hi!

@tyamamushi could you also provide us with your environment id?

**Comment by lostintangent** [comment]
Closing this due to lack of action ability, and the fact that we believe this issue should be resolved. Please re-open it if you’re still running into issues. Thanks
