### ISSUE TITLE
Can’t sign in on iPad in Safari

### ISSUE THREAD

**Issue by kylewill** [MicrosoftDocs/vscodespaces#607]
Whenever I login I am taking to the live.com login flow. “Signing in” spinner loads, then see this error:

“Login failed due to unexpected error. Please log out and try again.”

No issues on Pop_OS / Chrome with this account. I’ve tried incognito, cellular, ads disabled, and erasing all web history / cache. 

![IMG_0091](https://user-images.githubusercontent.com/3108182/85478572-8170f780-b58a-11ea-92ae-04d8cca5d75d.png)

**Comment by maswitzer** [comment]
Disabling Prevent Cross-Site Tracking in Safari settings will allow you to log in. This is a work around though, not an official solution.

**Comment by kylewill** [comment]
Ah, confirmed this works as a workaround.

**Comment by davide-rota** [comment]
+1, probably you already know this but you may need to implement the authorization code grant with PKCE -> https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas

**Comment by VincentDondain** [comment]
This is a duplicate of https://github.com/MicrosoftDocs/vscodespaces/issues/362, the current workaround is to disable Safari's cross-site tracking (Settings > Safari > Turn off "Prevent Cross-Site Tracking").
