### ISSUE TITLE
Display PyQt application in Codespaces

### ISSUE THREAD

**Issue by nsanka** [MicrosoftDocs/vscodespaces#608]
How to display a simple PyQt application in codespace using visual studio code on Windows? It gives error "Error: Can't open display:". I already have Xming X server running and tested opening the same application by connecting to another Linux machine using X11 Forwarding. How to do that in codespace environment?

**Comment by cjwlife** [comment]
Did you find the solution for it? I have also faced the issue

**Comment by lostintangent** [comment]
Thanks for reporting this! We're tracking this via #497, so I'm going to close this as a duplicate, and we can continue the conversation in that issue. Thanks!
