### ISSUE TITLE
Full Screen support on iOS

### ISSUE THREAD

**Issue by DAddYE** [MicrosoftDocs/vscodespaces#615]
Hi,

would be awesome, if you could add the tag:

```html
<meta name="apple-mobile-web-app-capable" content="yes">
```

This should allow ios/ipados users, to add http://online.visualstudio.com to the home screen, after which, you'll be able to open in safari without the clutter of address bar and tabs.

**Comment by VincentDondain** [comment]
Hi,

Great suggestion 👍, this is now done! Please let us know if you have any more feedback on this issue.

**Comment by DAddYE** [comment]
Hi @VincentDondain, thanks so much for fixing it.

I opened another issue #768 for fixing the copy/paste issue on ipad.
