### ISSUE TITLE
Feature Request: Specify a browser to open the OAuth URL

### ISSUE THREAD

**Issue by mnixry** [MicrosoftDocs/vscodespaces#620]
For some reason, I cannot set the default browser configuration correctly, so vscode cannot handle the opened website by calling the default browser, therefore this prevents me from logging into the Visual Studio Codespace.
I hope this plugin can add an option to specify a browser to open the OAuth authentication URL.

**Comment by lostintangent** [comment]
We're now using the built-in VS Code authentication, and so any browser setting here would need to be added to VS Code itself. So I'm going to close this as external. If you're still running into an issue, it would be awesome if you could file a bug on the microsoft/vscode repo. Thanks!
