### ISSUE TITLE
Add the GitHub CLI to the base image

### ISSUE THREAD

**Issue by jkeech** [MicrosoftDocs/vscodespaces#632]
Update the base image to include the `gh` CLI from https://github.com/cli/cli. This makes it easy to manage PRs, repos, issues, etc within GitHub.

**Comment by kumarz** [comment]
https://github.com/microsoft/vscode-dev-containers/pull/427

I tested locally with a docker container the github CLI.

TODO: the authentication part.

**Comment by jkeech** [comment]
This has been deployed! 🚀  The `gh` CLI is now installed in the base image.
