### ISSUE TITLE
Document Azure permissions needed to create environments - corporate AAD auth

### ISSUE THREAD

**Issue by RobPurcellUK** [MicrosoftDocs/vscodespaces#64]
My MSDN Azure account is linked to my company Azure AD for authentication.

When trying to create a new environment, or register a local one, I am sent to the browser to authenticate.

The browser then displays an error:
>Need admin approval
>Visual Studio Services Client needs permissions to access resources in your organisation that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

I don't know what permissions it wants, or what it's trying to do. My guess is creation of service principals, which is something which blocks almost everything I try to do in Azure, as that permission isn't granted to any of our accounts.

Can the flow be documented somewhere, so we know what permissions are needed, what will be created in detail (service principals, resource groups etc)?

**Comment by lostintangent** [comment]
@RobPurcellUK Thanks for filing this issue! We'll try to get the docs updated ASAP 👍

**Comment by legomushroom** [comment]
@RobPurcellUK thanks for the feedback! We have a couple of alternative sign-in flows currently (and we are working on switching on just one). Mind posting the URL of the sign-in page you are landing on? That should help us to pin down the issue.

**Comment by RobPurcellUK** [comment]
Hi @legomushroom - I can.
I'm not sure if there's anything sensitive in the URLs posting them on here - should I message you some other way with it instead, or would it be OK?

**Comment by RobPurcellUK** [comment]
It looks like some of the info needed is referenced over here:
https://github.com/MicrosoftDocs/vsonline/issues/104
though the point at which there's an error is different in that case, it still seems to be about required permissions in an Azure subscription.

**Comment by stephensheridan** [comment]
Is there any update on this error? I'm trying to adopt Visual Studio code online in my organisation and cannot get passed this error. No idea of what privilieges are required or what needs to be done.

**Comment by nikmd23** [comment]
With the announcement that [Visual Studio Codespaces is consolidating into GitHub Codespaces](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), this doc update is no longer necessary. I'm closing this issue.
