### ISSUE TITLE
How to test web application?

### ISSUE THREAD

**Issue by PhilRussellCodespaces** [MicrosoftDocs/vscodespaces#640]
I've been searching the docs for this but can't find anything.  I created a Visual Studio Codespace and built a little web application there, that serves on port 8080.  Now I want to access this web application through my web browser.  How can I do that?  I can't find anything that tells me what the public IP or URL is, or whether I need to create a public IP.  Can anyone tell me how to do this?  Thanks.

**Comment by srivatsn** [comment]
The documentation here for forwarding a port and accessing it is here - https://docs.microsoft.com/en-us/visualstudio/online/how-to/browser#port-forwarding

**Comment by lostintangent** [comment]
Closing this as resolved. Please re-open it if you're still running into an issue. Thanks!
