### ISSUE TITLE
Distributing Codespaces

### ISSUE THREAD

**Issue by Blickensdoerfer-J** [MicrosoftDocs/vscodespaces#643]
I want to provide multiple users in the azure active directory with codespaces. Up until now i only have seen the possibility to let every user create a plan. The problem is, that in total only two plans can be created. Is there a way to increase the plan/codespace quota? Or is there another way to provide codespaces to users in an active directory?

**Comment by lostintangent** [comment]
Hey! We've increased the plan limit per subscription, and so you shouldn't be restricted to 2 any more. I'm going to close this as resolved for now, but please let me know if you're still running into issues. Thanks!
