### ISSUE TITLE
Default Oryx images have conflicting `apt` sources

### ISSUE THREAD

**Issue by jarrodldavis** [MicrosoftDocs/vscodespaces#644]
As it stands today, the default "blank" container provided by Visual Studio Codespaces is based on Debian 9 (`stretch`) through Microsoft's [Oryx images](https://github.com/microsoft/oryx). For some reason, this default Codespace has a conflicting `apt` source list in `/etc/apt/sources.list.d/buster.list`. This is pulling in the main sources for Debian 10 (`buster`) even though the image isn't on that version. This causes unresolvable package conflicts when trying to install any package that (directly or transitively) depends on the `libc6` (GNU C Shared Libraries) package.

To reproduce the issue:
1. Create a blank Codespace (by not specifying a repository)
2. Run `sudo apt-get update`
3. Run `sudo apt-get install ca-certificates`

Deleting the `/etc/apt/sources.list.d/buster.list` file resolves this issue, but I don't understand why the it's there in the first place when it causes this problem.

**Comment by jkeech** [comment]
Thanks for reporting this! We'll look into how this conflicting sources entry is getting added. Separately, we are also looking at switching to buster, but we definitely should not be mixing both at the same time.

**Comment by jkeech** [comment]
We've removed the source from the base image. The updated image will be rolling out next week for all newly-created Codespaces.

**Comment by jkeech** [comment]
This fix has been deployed 🚀
