### ISSUE TITLE
is code space support for multi tenant environment

### ISSUE THREAD

**Issue by jayasimhamadhira** [MicrosoftDocs/vscodespaces#648]
We used code space for devops practise and tried to create a workspace where i cant see the subscription details but in azure they added me as owner in subscription.

I want to know how i can create code space workspace on other tenant subscription.  

Can someone help me to get an idea how i achieve this for my other tenant subscription where i am guest user in that tenant.

**Comment by jkeech** [comment]
This looks like the same issue as #39. We are actively working on supporting this scenario. I'm going to close this issue so we can track in #39. Thanks!
