### ISSUE TITLE
vso script not able to start service/daemon on openSUSE Tumbleweed : 20200707

### ISSUE THREAD

**Issue by danchev** [MicrosoftDocs/vscodespaces#650]
- OS: openSUSE Tumbleweed : 20200707
- VSO: v1.0.2453.1726

I'm getting the following error when I run `user@suse:~> vso start --service` 
```
[2020-07-10 02:16:35.145 CLI I] vso v1.0.2453.1726 (pid: 5876)
[CLI E] systemctl not found at /bin/systemctl
[2020-07-10 02:16:35.393 CLI E] [!ERROR] systemctl must be installed at /bin/systemctl
```

**Comment by Davsterl** [comment]
We require systemd to run as a service but you can run as a process as an alternative
