### ISSUE TITLE
Scrolling on iPad not working w/ External mouse

### ISSUE THREAD

**Issue by dmitryyankowski** [MicrosoftDocs/vscodespaces#653]
I'm using Safari on my iPad with an external mouse, but I cant scroll with my mouse wheel in a file. Any ideas how I can fix this? Thanks

**Comment by dmitryyankowski** [comment]
Bumping this up. :)

**Comment by avillega** [comment]
This is the main reason I am not using code spaces. Hope they add better support for iPad in the future

**Comment by dmitryyankowski** [comment]
Bump!

**Comment by dmitryyankowski** [comment]
Any updates on this?
