### ISSUE TITLE
"The 'Go' extension is recommended for this file type." references incorrect extension id.

### ISSUE THREAD

**Issue by asw101** [MicrosoftDocs/vscodespaces#654]
When opening a .go file in VS Codespaces you will be prompted to install the Go extension.

However, clicking `Install` will search for `@id:ms-vscode.go` rather than `@id:golang.go` (see: https://code.visualstudio.com/blogs/2020/06/09/go-extension ).

**Comment by paulgmiller** [comment]
Ditto. Even if you use the go example setup you get this popup everytime.

**Comment by lostintangent** [comment]
Thanks for reporting this! This issue should now be resolved, and Codespaces will properly install the `golang.go` extension when it encounters a Go project. Please re-open this if you're still encountering an issue. Thanks!
