### ISSUE TITLE
[Self hosted] flag to answer "run as service" question

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/vscodespaces#657]
If you run `vso start` without `--service` you are prompted with:

```
Would you like to run as a persistent service/daemon? [Y]/[n]: [2020-07-14 18:49:21.075 CLI E] [!ERROR] Object reference not set to an instance of an object.
```

How can I answer yes to this in a non-interactive fashion?

**Comment by taiyosogawa** [comment]
Hi @TylerLeonhardt, unfortunately a fully non-interactive mode is not yet supported. Beyond indicating whether to run as a service, authentication currently requires user interaction. I'll tag this issue as an enhancement request.

**Comment by JustinGrote** [comment]
@TylerLeonhardt after a couple hours of futzing with trying to use diagnostics.process and stream input redirection to figure this out, I tried something stupid and it worked!

```powershell
"n`n" | C:\Users\jgrote\AppData\Local\VSOCodespaceAgent\vso.exe start -s 48759ba7-c496-43ac-ba0e-xxxxxxxx -r vso-codespaces -p vso-codespaces-westus2 -n Temp-023d398c-d7bc-46c4-9fe1-716c2223d800
```

> [2020-07-22 23:10:50.188 CLI I] vso v1.0.2475.20889 (pid: 15388)
> [2020-07-22 23:10:50.436 CLI I] Authenticating...
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code F6RM9XSHL to authenticate.
> [2020-07-22 23:11:01.782 CLI I] When connecting to this Codespace, you will be logged in as: ADSL-S-JGROTE\jgrote
> Would you like to run as a persistent service/daemon? [Y]/[n]: [2020-07-22 23:11:01.785 CLI I] Will run as a process
> [2020-07-22 23:11:02.669 CLI I] A Visual Studio Codespaces plan is required to register a self-hosted Codespace.
> [2020-07-22 23:11:03.980 CLI I] A Codespace already exists with the name Temp-023d398c-d7bc-46c4-9fe1-716c2223d800
> Enter a Codespace name or blank to use [Temp-023d398c-d7bc-46c4-9fe1-716c2223d800-1]: [2020-07-22 23:11:03.986 CLI I] Authenticating...
> [2020-07-22 23:11:05.193 CLI I] Creating your Codespace...
> [2020-07-22 23:11:08.174 CLI I] Authenticating...
> [2020-07-22 23:11:09.905 CLI I] Saving local configurations...
> [2020-07-22 23:11:10.620 CLI I] Waiting for your Codespace to become available...
> [2020-07-22 23:11:15.866 CLI I] All done! Connect: https://online.visualstudio.com/environment/08de2ced-d675-4282-b3cb-dbd45de3fa25

**Comment by TylerLeonhardt** [comment]
omg 😅

**Comment by TylerLeonhardt** [comment]
Yeah this is nice - I've got a nearly non-interactive experience:

Dockerfile:
```dockerfile
FROM mcr.microsoft.com/powershell:latest

RUN apt-get update && apt-get install wget
RUN curl -L https://aka.ms/install-vso-linux | sh

COPY LICENSE README.md /

COPY entrypoint.ps1 /entrypoint.ps1

ENTRYPOINT ["pwsh", "-Command", "/entrypoint.ps1"]
```

entrypoint.ps1:
```pwsh
param($SubscriptionName, $PlanName)

Set-Location $HOME
"y`nn`n" | vso start -s $SubscriptionName -p $PlanName

Read-Host -Prompt "Press ENTER or ^C to stop server."
```

usage:
```pwsh
docker run -it vso:latest -SubscriptionName  "My Sub" -PlanName "myplan"
```

The only thing that I can't get past is device auth.

**Comment by JustinGrote** [comment]
For the device Auth I'm watching for the display of the line and then do it on my local workstation, then it proceeds.

Per my other issue, hopefully they add certificate or secret Auth for a service principal.

**Comment by Davsterl** [comment]
We could make this work for the non-service case easily.

**Comment by 2percentsilk** [comment]
Given [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) and self-hosted support will be retired on November 20, 2020, we are not scheduling further investment in this service and will be closing this issue. We encourage you to join the discussion on self-hosted support on [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/19), where we’ll be gathering feedback to help inform our roadmap.

Thank you for participating in our public preview and providing this feedback!
