### ISSUE TITLE
Simultaneous Codespaces active

### ISSUE THREAD

**Issue by Blickensdoerfer-J** [MicrosoftDocs/vscodespaces#658]
I have a problem with my visual studio codespaces. With active directory i created two tenants that are using VS Codespaces. Each of them has exactly one plan with two codespaces. There are two problems currently:

- With both tenants i cannot create a third codespace even though the quota should allow to have three codespaces per plan. When trying to create a third codespace i get "You have exceeded the codespace quota"

- Of all the four codespaces only two can be used at the same time. When trying to connect to a third codespace it does not load and it is written "You have exceeded the codespace quota". I have not found any documentation about the limitation of active codespaces.

**Comment by Davsterl** [comment]
Hello,
We need to update our documentation here but we have a limit now on the number of active codespaces. It depends on your type of subscription and matches the cap on the number of active VMs that Azure allows for.
I'll ensure our docs are updated accordingly.

**Comment by saramarcondes** [comment]
Hi, I actually only have a single codespace and am unable to create a new one due to the same quota error even if I am disconnected from the single codespace I have. Is this part of the same issue or should I open a separate issue?

**Comment by Davsterl** [comment]
Hi Sara,
Is the codespace active? You should be able to create a second one when one is suspended. 
What type of azure subscription do you have?

**Comment by 2percentsilk** [comment]
Removing doc bug as we've published the Azure quota doc.

**Comment by saramarcondes** [comment]
@Davsterl That was the issue, thanks! I was trying to have two spaces active at a single time. Perhaps the error message could be more descriptive?

**Comment by lostintangent** [comment]
Closing this issue issue as resolved, since we updated the docs to make this clearer. Please re-open it if you're continuing to encounter an issue. Thanks!
