### ISSUE TITLE
Polish: Remote Explorer - Details - group attributes under a node 'Attributes'

### ISSUE THREAD

**Issue by egamma** [MicrosoftDocs/vscodespaces#66]
Suggest to group the environment attributes under an 'Attributes' node in the details section, same as it is done for containers (see below).

<img width="280" alt="image" src="https://user-images.githubusercontent.com/172399/68207654-a995f100-ffcf-11e9-93be-75c2a2e5bdc2.png">

<img width="312" alt="image" src="https://user-images.githubusercontent.com/172399/68207610-9420c700-ffcf-11e9-8931-e847951381f1.png">

**Comment by lostintangent** [comment]
@egamma Ah yeah I really like this suggestion!

**Comment by lostintangent** [comment]
Since ports are now exposed via the shared ports view, I'm going to close this, and we can re-asses any UX changes as part of the "UX audit" that the team is doing right now 👍
