### ISSUE TITLE
How to upload files into codespace?

### ISSUE THREAD

**Issue by DanielHabenicht** [MicrosoftDocs/vscodespaces#660]
Apparently some people are asking this question: https://stackoverflow.com/questions/62284623/how-can-i-upload-a-file-to-a-visual-studio-codespaces-environment/62838450#62838450

Would be great if it gets documented. 

Thanks for the great tool!

**Comment by bpasero** [comment]
@DanielHabenicht you can drag and drop folders and files into the explorer to upload.

**Comment by DanielHabenicht** [comment]
Yep, I know. I thought that this would be the right place to document.

**Comment by srivatsn** [comment]
@abuchholtzau

**Comment by nikmd23** [comment]
Since [Visual Studio Codespaces is consolidating into GitHub Codespaces](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), I've moved this issue to the GitHub docs repo. Please track it here: https://github.com/github/docs/issues/1792.
