### ISSUE TITLE
VS IDE compatibility topic

### ISSUE THREAD

**Issue by gregvanl** [MicrosoftDocs/vscodespaces#670]
Outline what users can expect when they use the VS IDE with a cloud-hosted VS Codespaces.
- Brief description of the difference between using VS IDE client with local tools and workloads versus a codespace
- Which IDE features are available or not.
- Which IDE features might require a private preview.

This topic might live in the VS IDE docset or might be under Codespaces.

**Comment by kendrahavens** [comment]
This [blog post](https://devblogs.microsoft.com/dotnet/using-visual-studio-codespaces-with-net-core/) from Build included a paragraph on setting expectations for .NET Core customers. It may be good to reuse as an intro here.

> For now, we recommend using Codespaces for .NET Core projects that are solely console, ASP.NET Core, or library apps. No designers are implemented so any apps with UI that relies on designers should wait for later versions. Think backend or middle-ware apps with few dependencies outside a public NuGet feed. Apps that are ‘server-ready’ that run in relative isolation will be the easiest to start with. For this first preview version, no Azure services can connect to the development environment of your app including KeyVault and AAD integration. Some of the features you know and love like CodeLens, ENC, code actions with sub menus, NuGet Package Manager, etc. will also not be available in this first preview. Hopefully, this helps paint the picture of isolated, server-side apps that are good candidates for development in the Visual Studio Codespaces preview.

We started an [internal doc](https://microsoft.sharepoint.com/teams/VSSaaS/_layouts/OneNote.aspx?id=%2Fteams%2FVSSaaS%2FShared%20Documents%2FGeneral%2FVS%20SaaS&wd=target%28VS%20Nexus%2FPrivate%20Preview.one%7C679C51E9-7EEE-4CEB-B9BE-3A7F9D6F214A%2FPrivate%20Preview%20Feature%20expectations%7C7C838739-BA62-4010-863C-6D23A288056F%2F%29onenote:https://microsoft.sharepoint.com/teams/VSSaaS/Shared%20Documents/General/VS%20SaaS/VS%20Nexus/Private%20Preview.one#Private%20Preview%20Feature%20expectations&section-id={679C51E9-7EEE-4CEB-B9BE-3A7F9D6F214A}&page-id={7C838739-BA62-4010-863C-6D23A288056F}&end) of features that aren't yet supported and when support work may begin. We should still follow-up with area owners before it moves externally.

**Comment by gregvanl** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/codespaces/supported-features-codespaces
