### ISSUE TITLE
.netcore code is not loading references appropiately in Omnisharp

### ISSUE THREAD

**Issue by juanc5ibanez** [MicrosoftDocs/vscodespaces#674]
Hi, I actually not sure if this is from codespaces or Omnishart
Description
I  attempted to open a .netcore project, looks like it does not load the references, says that it cannot import system. If I do try to compile though it compiles successfully (using dotnet build).

![image](https://user-images.githubusercontent.com/17993720/88019385-0c82e480-cb6d-11ea-93a2-f396f3422bf7.png)

**Comment by juanc5ibanez** [comment]
looks like its covered here https://github.com/OmniSharp/omnisharp-vscode/issues/3913

**Comment by jkeech** [comment]
@edgonmsft and @dmgardiner25 can you see if this is related to the switch to the Linux universal base image or any other of recent .NET Core related changes in the image, such as #472?

**Comment by Stewartarmbrecht** [comment]
Thought I would help with steps to recreate.  This seems like a pretty big deal.  Looks like codespaces do not currently support dotnet core development.

Create new codespace.
Open browser editor.
Run the following in the terminal:

```
dotnet new sln
dotnet new web
dotnet sln add workspace.csproj
dotnet restore
dotnet build

```

Restore and build work. IDE looks like this:
![image](https://user-images.githubusercontent.com/1000121/88341471-41c13b00-cd03-11ea-9672-26196de45078.png)

**Comment by jkeech** [comment]
Fix: https://github.com/microsoft/vscode-dev-containers/pull/430

This will get deployed to the service next week

**Comment by jkeech** [comment]
The fix for this issue has been deployed! Let us know if you continue to see any IntelliSense errors like this on newly-created Codespaces.

**Comment by Stewartarmbrecht** [comment]
Looks great!!
![image](https://user-images.githubusercontent.com/1000121/88973660-7003c500-d285-11ea-9afc-2d97965d8be3.png)
