### ISSUE TITLE
containers leave zombie processes

### ISSUE THREAD

**Issue by ribrdb** [MicrosoftDocs/vscodespaces#676]
When I run ps inside my codespace terminal (without doing any image customization), I see lots of zombie processes.
I assume this is the docker zombie problem: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

I think either you should use the --init argument to docker run, or the base image should be setup to use it's own init process to reap zombies.

**Comment by legomushroom** [comment]
@ribrdb do you think those related to docker? Mind posting the list of the processes here?

**Comment by ribrdb** [comment]
Yes, it appears docker doesn't reap zombies by default, because it was originally intended to run one process with no children.

I'd rather not post the list of things I'm running, but I see leftovers from every bazel build and every test run.

**Comment by ribrdb** [comment]
I just connected to an environment that was previously suspended. Haven't done anything yet and it's already got one zombie:
```
$ ps ax
...
  241 ?        Z      0:00 [vsls-agent] <defunct>
```

**Comment by legomushroom** [comment]
`vsls-agent` is the a system process that is responsible to create the connection tunnel from the client to the remote codespace. Does it cause any issues in your codespace? If it consumes too many resources, that is something we want to fix.
The reason I am asking to post the processes list so we can confirm that those processes are not the ones we run inside the codespace to make it functional, of course, please remove any processes that can reveal personal/sensitive info.

**Comment by ribrdb** [comment]
I don't really know if this is causing any problems. From the article linked above:

> Apart from the fact that zombie processes hold kernel resources, zombie processes that don't go away can also interfere with software that check for the existence of processes. For example, the Phusion Passenger application server manages processes. It restarts processes when they crash. Crash detection is implemented by parsing the output of ps, and by sending a 0 signal to the process ID. Zombie processes are displayed in ps and respond to the 0 signal, so Phusion Passenger thinks the process is still alive even though it has terminated.

Also it's just confusing. I found this when I was trying to debug a test that seemed to be failing for no reason. I looked at ps to see if there was some process running that was using ports required by the test, and there were so many zombie processes that I couldn't read the ps output at all. I have no idea if the test failure was somehow caused by this, but it definitely prevented me from doing my normal debugging.

Fixing it seems like it should be really simple, all you need to do is add the `--init` option to the docker run command.

Here's a list of zombies from another session that was running a bit longer. But I still hadn't really done anything yet, just waited for all the extension to finish loading for the files that were previously open.

```
$ ps ax|grep defunct
   499 ?        Z      0:00 [lang_server_lin] <defunct>
   509 ?        Z      0:00 [sh] <defunct>
   510 ?        Z      0:00 [sh] <defunct>
   513 ?        Z      0:00 [sh] <defunct>
   592 ?        Zs     0:00 [java] <defunct>
   604 ?        Z      0:00 [sh] <defunct>
   611 ?        Z      0:00 [sh] <defunct>
   641 ?        Z      0:00 [git] <defunct>
   652 ?        Z      0:00 [sh] <defunct>
   696 ?        Z      0:00 [sh] <defunct>
   723 ?        Z      0:00 [sh] <defunct>
   751 ?        Z      0:00 [git-remote-http] <defunct>
   777 ?        Z      0:00 [sh] <defunct>
   930 ?        Z      0:00 [git] <defunct>
   931 ?        Z      0:00 [node] <defunct>
   940 ?        Z      0:00 [gocode] <defunct>
  1165 ?        Z      0:00 [node] <defunct>
  1438 ?        Z      0:01 [vsls-agent] <defunct>
  2423 pts/2    S+     0:00 grep defunct
```

**Comment by ribrdb** [comment]
Ok, I take it back. This is definitely causing problems. Bazel now refuses to run because it's waiting for that defunct java process (592) to exit.

**Comment by jkeech** [comment]
Thanks for reporting this @ribrdb! I wasn't aware of the zombie process issue until you posted about it. We'll look into running the containers with `--init`.

**Comment by MichalCz** [comment]
This is a known bug with all containers in vscode, not Codespaces specific.

**Comment by ribrdb** [comment]
I don't really agree. In general you don't know that any container is intended to run multiple processes, so assuming they always want init seems wrong. But for codespaces the containers are definitely intended to run multiple processes so the definitely need an init process.

**Comment by jkeech** [comment]
This fix has been deployed! 🎉 Docker containers are run with the `--init` flag now.
