### ISSUE TITLE
Document devcontainer.json properties specific to Windows-based codespaces

### ISSUE THREAD

**Issue by gregvanl** [MicrosoftDocs/vscodespaces#681]
There may be properties added to the existing devcontainers.json schema specifically to configure Windows-based codespaces.

This documentation could be added to the existing Configuring Windows Codespaces https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/configuring-windows or might be a new topic.

**Comment by acangialosi** [comment]
I believe this topic will impact other docs beyond the Codespaces repository. There are a few references throughout VS Code docs that discuss customization. Windows based Codespaces are not limited to VS IDE. They will be accessible from VS Code and the Web editor. So we should make sure these Code topics have relevant Windows Codespace documentation.
	https://code.visualstudio.com/docs/remote/codespaces
•	Configuration section should talk about devinit and link off to a specific topic.
	https://code.visualstudio.com/docs/remote/containers
•	Should have a reference off to the Windows Codespace customization topic

**Comment by gregvanl** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/codespaces/customize-codespaces
