### ISSUE TITLE
codespaces too expensive

### ISSUE THREAD

**Issue by webstermath** [MicrosoftDocs/vscodespaces#688]
I have enjoyed using Codespaces so far and appreciate the hard work going into it, but after reviewing my bill on Azure, I realize that it is not worth the cost.  I am a Chromebook user and was hoping Codespaces would provide the virtualized solution for development that I was seeking.  While it generally does meet the requirements for a fully virtualized development environment necessary for developing on a Chromebook, the cost is absurdly prohibitive.  I have decided in the end to just use another computer and to develop locally.  I write this only in the hopes it becomes constructive feedback in the development of Codespaces.

**Comment by nikmd23** [comment]
Hi @webstermath. Thanks for taking the time to leave this feedback. We really appreciate it! I’m glad to hear that you enjoyed using Codespaces. 😀

On the other side of the coin, I’m also disappointed that the value to cost equation did not balance out for you. I’d love to learn more about this:

- Without being too exact about it, what was your actual bill, and what was your expected bill?
- What was your usage behavior in terms of number of total Codespaces, number simultaneously active Codespaces, the instance types you used, etc.

This information will be able to help us optimize for more scenarios.

Also, for what it’s worth, we’re always working to increase the value to cost ratio. Sometimes that’s by adding more features and value into the service, and other times that’s by working to reduce the costs. In the coming months we have work planned for both, and depending on your usage, we hope that we’ll be able improve the balance for you.

**Comment by webstermath** [comment]
So as of right now my bill is about $24 and is forecast to be about $30 for July.  I had planned to develop much more with codespaces so I assume my bill would be significantly higher.  I currently have two codespaces but never use them simultaneously.  They are both the 4 core, 8 gb ram instances. 

As a full-time developer, Codespaces appeared to provide the virtualized development environment I was looking for to develop on a Chromebook.  Although it performs that task fairly well, I can not justify the cost. For that amount of money charged, I will be better served by buying a new laptop and developing locally.

I do hope this feedback is helpful.

**Comment by lostintangent** [comment]
@webstermath As @nikmd23 mentioned, we really appreciate this very thoughtful feedback. It's extremely helpful.
Now that [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), we'll be discussing any potential pricing changes through GitHub. In the meantime, I'm going to close this issue. Thanks again!
