### ISSUE TITLE
This codespace is not compatible with this version of Visual Studio

### ISSUE THREAD

**Issue by TrevorHerr** [MicrosoftDocs/vscodespaces#696]
Are Self-hosted codespaces not supported in Visual Studio 2019 at this time?

Steps:
1. On host machine Open VS Code and Sign-in into codespaces.
2. Create a self hosted codespaces.
3. Open Visual Studio 2019 Preview on local machine and select **Connect to a codespace**
4. Visual Studio gives the following error: **This codespace is not compatible with this version of Visual Studio. You need to create a new codespace to connect with this version of Visual Studio.**

Connecting via VS Code or the browser works just fine.

Thanks

**Comment by jkeech** [comment]
Hi @TrevorHerr, that's correct. Self-hosted Codespaces only support VS Code and browser clients today, since the self-hosted agent only knows how to spin up a VS Code backend currently. The type of client (VS Code or Visual Studio) has to match the type of the backend. Since the agent only spins up a VS Code backend, the only clients that can connect are VS Code clients (either desktop or web).

**Comment by TrevorHerr** [comment]
Makes sense thank you! Any idea if adding the ability spin up a Self-hosted codespace in Visual Studio 2019 is coming soon? 

Closing the issue but would love a response even if it is just a vague soon, far off, never, answer. Codespaces has be super helpful for the team as we have a pretty complex environment (multiple databases, multiple sites working together, etc) and would this to be an option for our backend developers.

**Comment by abuchholtzau** [comment]
Hey @TrevorHerr, no immediate plans to bring self-hosted to VS but it's definitely something we're considering after we get the basics settled for VS. We're constantly taking feedback from the community to learn what we should prioritize though so thanks for providing this feedback!

**Comment by TrevorHerr** [comment]
Thanks for the responses @abuchholtzau and @jkeech. I appreciate the transparency and keep up the great work with Codespaces.
