### ISSUE TITLE
Codespace fails to connect to remote extension host server

### ISSUE THREAD

**Issue by nemosupremo** [MicrosoftDocs/vscodespaces#698]
When starting a workspace, Codespace fails to connect to the remote extension host server due to an axios error. I can still connect via Google Chrome, but not through VSCode.

Error
```
Failed to connect to the remote extension host server (Error: Axios response: message[Request failed with status code 400] host[online.visualstudio.com] status[400] data[The requested SKU 'premiumLinux' is not available in location: WestUs2])
```

VSCode
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
```

**Comment by bratsche** [comment]
Hi @nemosupremo, are you still having this problem? If so can you also include what version of the codespaces extension you have installed, and are you connecting using Microsoft or Github?

**Comment by jkeech** [comment]
We've identified the issue that affects resuming Codespaces located in the non-default region (the one that isn't determined as the closest one). We're working on preparing and deploying a fix.

**Comment by jkeech** [comment]
The fix has been deployed. I'm going to close this issue out, but let us know if you see this again. Thanks!

**Comment by nemosupremo** [comment]
This seems to be working now.
