### ISSUE TITLE
The linux install script fails to install because the executable has been renamed

### ISSUE THREAD

**Issue by TylerLeonhardt** [MicrosoftDocs/vscodespaces#699]
Check out the script:
https://aka.ms/install-vso-linux

It chmod's the old executable name `vso` but it appears as if the executable has been renamed to `codespaces`.

The install script fails because it can't find the `vso` executable.

**Comment by jkeech** [comment]
@davsterl

**Comment by jkeech** [comment]
The install script has been fixed. I'm going to close this issue, but let us know if you continue to see problems and we can re-activate. Thanks!
