### ISSUE TITLE
Integration of VSCodespaces as an ide for students Microsoft Classroom

### ISSUE THREAD

**Issue by utsavsinghal5** [MicrosoftDocs/vscodespaces#704]
We are an early age ed-tech startup working to bring the experience of coding to a younger age group. We wanted to use MS Teams to organize our classes. VSCodespaces seems like a great tool to fulfill our needs. We want to provide it as an independent IDE on browsers for our users. But to run it, there is a need to register on azure. We would like to know that is there any feature that one azure space can be bought by the company and all the students can independently use it to run VSCodespaces?

**Comment by lostintangent** [comment]
@utsavsinghal5 Hey! Thanks for reaching out. We're in the process of consolidating Codespaces into GitHub Codespaces, and as part of that, we're focused on GitHub being the entry point for all developers. We don't have any plans to enable whitelabeling/integration with platforms, but if this is something you'd like to see, it would be awesome if you could file an issue on the [GitHub Support Community](https://github.community/c/codespaces-beta/45) forum. Thanks!
