### ISSUE TITLE
Support for on premise org deployment

### ISSUE THREAD

**Issue by davidanthoff** [MicrosoftDocs/vscodespaces#706]
Are there any plans to provide an option for an on premise organization wide deployment? I think there are various options for other Azure Services to run on premise on an orgs own hardware, is that a scenario that might also be supported for Codespaces?

The concrete scenario I have in mind is a university that wants to provide coding environments for teaching. Most universities that I know have their own compute resources for that scenario and won't be willing to rent time from MS or some other cloud provider for this. But at the same time the functionality of Codespaces would be fantastic for a teaching environment. In my ideal world a student could sign into codespaces with their university account, have all the UI and functionality, but then the compute nodes would actually run in some university data center.

I guess my question is really both for the VS Codespaces and Github Codespaces situation.

**Comment by lostintangent** [comment]
Hey! We're in the process of consolidating Codespaces into GitHub Codespaces, and so the logical solution for this would be to integrate Codespaces into GitHub Enterprise Server (GHES). We're currently focused on enabling GitHub.com and GitHub Enterprise Cloud, and we don't have any concrete plans for enabling GHES in the near future. If this is something that would be critical for your usage, it would be awesome if you could file an issue on the [GitHub Support Community](https://github.community/c/codespaces-beta/45) forum. This is where we're now tracking roadmap items for GitHub Codespaces, and so we can continue to conversation over there. Thanks!
