### ISSUE TITLE
What's the point with Microsoft announcing both VS Codespaces and GitHub Codespaces?

### ISSUE THREAD

**Issue by ChayimFriedman2** [MicrosoftDocs/vscodespaces#709]
I'm not sure this is the right place to ask this question, but I can't find an answer anywhere else.

**Why did Microsoft release both VS Codespaces and GitHub Codespaces?** They're too similar to live together. Yes, they have some differences, like the ability to raise a GitHub Codespaces environment with one click from a GitHub repo, but I'm sure this can be done without differentiating the products.

Why didn't Microsoft build one unified product? To be clear, I think Codespaces are great thing, but two products are just... confusion. I have no other words.

Is this the result of lack of coordination between the VS team and the GitHub team?

Hope to get an answer soon, and again, many thanks for the great product(s). That's a big step in the cloud world, and makes it easier than ever to contribute to any open-source project (and a great way to make GitHub acquisition profitable, I think 😉).

Best regards.

**Comment by lostintangent** [comment]
Hey! Last Friday, we announced that [Codespaces is consolidating into GitHub Codespaces](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), and so I'm going to close this issue as resolved 😄  Thanks again for your feedback here, and let us know if you have any other questions 👍
