### ISSUE TITLE
Document what's included in the universal (default) Linux container

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#710]
In the absence of a `devcontainer.json` file pointing to a different image/file, Codespaces uses [our Universal Linux image](https://github.com/microsoft/vscode-dev-containers/blob/master/containers/codespaces-linux/.devcontainer/Dockerfile) as the default container. 

It'd be great to have a document that lists what's installed in that container (including its base image) by default.

cc @Chuxel @2percentsilk @gregvanl for awareness

**Comment by lostintangent** [comment]
Closing this as resolved per [this document](https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/configuring-codespaces-for-your-project#about-default-codespace-configurations). @2percentsilk can you make sure we're tracking any further doc improvements as part of your broader doc strategy? Thanks!
