### ISSUE TITLE
Port forwarding connection loop

### ISSUE THREAD

**Issue by mlynch** [MicrosoftDocs/vscodespaces#711]
If I forward a port running a web app (in this case using Stencil: https://stenciljs.com/), the "connecting to forwarded port" screen displays on a loop. I see the correct web app page load for a split second before this shows over and over:

![image](https://user-images.githubusercontent.com/11214/89217217-67670380-d591-11ea-9337-4a1ed5a635f1.png)

**Comment by lostintangent** [comment]
This issue should now be resolved! I just tried creating a Codespace for a [Stencil app](https://github.com/khaledosman/stencil-realworld-app) and was able to launch the dev server using a forwarded port. Let me know if you're still running into issues. Thanks!
