### ISSUE TITLE
Codespace won't start.

### ISSUE THREAD

**Issue by danyhoron** [MicrosoftDocs/vscodespaces#714]
My environment is: https://online.visualstudio.com/environment/e001df0a-ebdf-4b72-bbb5-f54d4631ee55
When I try to connect to it, it would say: `Starting` for a minute and then move back to `Suspended`.

Might be related to #664

**Comment by fara-nak** [comment]
sorry to see you have issue resuming your environment, we are looking into the issue and will update soon...

**Comment by edgonmsft** [comment]
Hi Daniel!

We diagnosed the issue with your Codespace and took corrective action.

Could you please let us know if it now starts correctly?

Thanks!

**Comment by danyhoron** [comment]
@edgonmsft I was able to resume it.

Thank you

**Comment by danyhoron** [comment]
@fara-nak, @edgonmsft I'm encountering the same issue again.

It seems that it happens when I open a workspace within my codespace, and it auto suspends after 30 minutes of inactivity.

**Comment by fara-nak** [comment]
sorry to hear that, let me take a look

**Comment by fara-nak** [comment]
@danyhoron could you please give it another try?

**Comment by danyhoron** [comment]
@fara-nak I tried. 
Now it gets stuck in `Starting` it won't switch back to `Suspended` after a minute as it did before.
