### ISSUE TITLE
SPFx WebParts give HTTP 504 ERROR when run from browser version.

### ISSUE THREAD

**Issue by sebastianrogers** [MicrosoftDocs/vscodespaces#715]
Create a Hello World SPFx webpart as outlined in https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part

```sh
gulp serve
```

[13:38:47] Server started https://localhost:4321
[13:38:47] LiveReload started on port 35729
[13:38:47] Running server
[13:38:47] Opening https://localhost:5432/workbench using the default OS app

Navigate to https://localhost:5432/workbench

Error given:

```html
This page isn't working at the moment
GUID.app.online.visualstudio.com took too long to respond.
HTTP ERROR 504
```

**Comment by sebastianrogers** [comment]
Hi There

Any response to this?

Cheers

**Comment by lostintangent** [comment]
This issue should now be resolved, since we deployed a new version of our port forwarding service! Please re-open the issue if you're still encountering any problems. Thanks!
