### ISSUE TITLE
Issues pair programming with Codespaces

### ISSUE THREAD

**Issue by t-eckert** [MicrosoftDocs/vscodespaces#716]
Hi, I am very excited for Codespaces and tried recently to stream pair programing on Twitch with a buddy of mine using Codespaces. We had different odd issues we couldn't troubleshoot live. I realized the stream is probably a useful document of real usage, in case it helps with the development process. 

Here is a link to the stream:  https://www.twitch.tv/videos/691383040

**Comment by 2percentsilk** [comment]
Hey @t-eckert 
That stream isn't available anymore :( Any ways you could give us some details on what happened? Or have a copy of the stream you could share?

**Comment by t-eckert** [comment]
Totally! I will make a note to write this up soon or find a VOD that is shareable. I know these issues can be hard to replicate so I figured having a user experience recording would be helpful. If I can talk to my friend about details, I will be happy to write something up. I think this product is awesome! Keep up the good work!

**Comment by lostintangent** [comment]
@t-eckert Thanks! If you get a chance to write out this feedback, it would be awesome if you could file it at the [Live Share](https://github.com/microsoftdocs/live-share) repo, so that that team can take a look. Thanks!
