### ISSUE TITLE
Codepaces hangs on "resume codespace"

### ISSUE THREAD

**Issue by paulgmiller** [MicrosoftDocs/vscodespaces#721]
using online.visualstudio.com as user pmiller@microsoft.com.

I've created two go environmetns and both worked fine for weeks before they both seem to go into the same state where they could not resume.  Sadly there's not any more logs. The environments names are go-dev-alpha and go-dev-beta. 

Plan is pmiller-codespaces in the subsciption: c1089427-83d3-4286-9f35-5af546a6eb67 rg: pmiller-dev

Would love if it dumped some sort of logs after more than a minutes. We're developers we love scrolling text.

**Comment by 2percentsilk** [comment]
A few questions:
1. When did the environments start acting up in this way?
2. Is it possible you've hit a quota limit? See our docs for [quota info ](https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/quota-limits)
3. Have you tried connecting to these Codespaces through the VS Code extension? If the same error happens in VS Code, can you look at the “VS Codespaces” output Window and paste the logs here? 
4. For the web failure, if you look in the network tab when making the request to resume, can you see if there is a failed request? If so, the failed request should have a vssaas-request-id response header. Can you send us that id so we can look at what happened with that particular request?

**Comment by paulgmiller** [comment]
1. Alpha stopped responding 3 weeks ago. So I created go-dev-beta. It stopped tuesday night?  (8/4)
2. I have the only Visual Studio Online Plan in my sub and no other environment is active: Not sure how I identify what offer category I'm in but don't think this it.

Seeing if I can get more logs from vscode or f12

**Comment by paulgmiller** [comment]
3. 


```[Client I] Trace log: C:\Users\PMILLE~1.RED\AppData\Local\Temp/vsonline_logs/20200805_220438_15966650783770_VSCode.log
[Client V] Initializing authentication
[Client V] Initializing self-hosted environment registry
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[Command:d I] Decorator starting: l
[Command:d I] Decorator starting: a
[Client I] User logged in as pmiller@microsoft.com
[Client I] User logged in as pmiller@microsoft.com
[EnvironmentDetailsExplorer I] Updating environment details
[Command:v I] Decorator starting: l
[Command:v I] Decorator starting: a
[Connect I] Connecting to environment: {"label":"go-dev-beta","isRunningInCloudEnvironment":false}
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
[EnvironmentDetailsExplorer I] Updating environment details
```
Continues spinning on Updating environment details

**Comment by 2percentsilk** [comment]
Ahh this looks like a self-hosted environment. Did you register with the CLI or through a client? You may have to re-register the machine. Also, if the machine you registered is asleep or off, it could trigger this problem as our self-hosted client doesn't have the capability to wake up self-hosted machines.

cc @taiyosogawa for more insight.

**Comment by jkeech** [comment]
@2percentsilk, this is not a self-hosted Codespace. @fara-nak is investigaing.

**Comment by taiyosogawa** [comment]
@2percentsilk, the `Initializing self-hosted environment registry` is just a log message that is printed when the VSCode extension initializes. It doesn't necessarily indicate that it's a self-hosted codespace.

**Comment by paulgmiller** [comment]
Yep not self hosted. 

No errors from network debug window on https://online.visualstudio.com/environment/4d463b2a-bd67-4a37-97f6-9050e8b03ffd just 200's looping.

**Comment by 2percentsilk** [comment]
Today I learned! Thanks for that insight John and Taiyo. I'll let Fara take it from here!

**Comment by paulgmiller** [comment]
Also I can get to other environments in the same plan like : https://online.visualstudio.com/environment/5f6f76e7-60ba-45c7-a289-1c74b2716be6 and they start up

**Comment by fara-nak** [comment]
@paulgmiller sorry for the issue you are seeing, could you please try to resume both codespaces one more time and let me know if this time they would resume or not?

**Comment by paulgmiller** [comment]
go-dev-alpha came up. go-dev-beta still hung.

**Comment by fara-nak** [comment]
so for alpha, what do you mean it's not functional? how does it look like?

for beta, can you suspend it wait like couple min and retry please?

**Comment by paulgmiller** [comment]
For alpha the normal ui came up but with no files or terminal and hte eror message I pasted. 

Trying again.

**Comment by paulgmiller** [comment]
Second try alpha worked. Got console/files this time. Beta still stuck in resuming codespaces.

**Comment by fara-nak** [comment]
ok glad alpha worked, please give some more time to investigate beta again.

**Comment by paulgmiller** [comment]
To be clear these aren't mission critical. I care alot more about rootcausing why this happened than getting them up immediately. Thanks @fara-nak!

**Comment by fara-nak** [comment]
yes Paul, we appreciate it, this helps us figure out our bugs thanks alot

**Comment by fara-nak** [comment]
hey Pal, could you please try suspending and starting beta one more time?

**Comment by paulgmiller** [comment]
Tried twice. No luck

**Comment by paulgmiller** [comment]
Alpha also seems to have become broken again.

**Comment by fara-nak** [comment]
Thanks Paul, we are aware of the issue and still investigating the solution, will update here once we have your codespaces up and running...

**Comment by paulgmiller** [comment]
Codespaces team has made a hotfix to make this corruption far less likely.
