### ISSUE TITLE
Cannot create a Codespace - "Creating the codespace" does not finish

### ISSUE THREAD

**Issue by TanjaBaecker** [MicrosoftDocs/vscodespaces#726]
Creating a codespace is not completing ... 
![Bildschirmfoto 2020-08-09 um 12 14 54](https://user-images.githubusercontent.com/66383417/89729867-f795c480-da39-11ea-81a3-15b3e0e57125.png)
:
- vso-plan-westeurope
- Browser: firefox, chrome,safari
- using MS Azure Account with subscription 
Is it a temporary or general problem

**Comment by 2percentsilk** [comment]
Sorry you're running into this issue. It looks similar to #705 so could you start by checking the health of the subscription you're using with VS Codespaces? 

If your subscription is in good health, could you look in the network tab when making the request to create a codespace and see if there is a failed request? If there is a failed request, it should have a vssaas-request-id response header. Can you send us that id so we can look at what happened with that particular request?

**Comment by TanjaBaecker** [comment]
It does now work. There is an undocumented requirement, that I needed to create an DevOps organization first, before I was able to successfully create a Codespace.

**Comment by TanjaBaecker** [comment]
It does now work. There is an undocumented requirement, that I needed to create an DevOps organization first, before I was able to successfully create a Codespace.
