### ISSUE TITLE
UI cues when a file is manually saved when auto-save is turned on

### ISSUE THREAD

**Issue by abychat** [MicrosoftDocs/vscodespaces#729]
When I am making changes to a bunch of files with auto-save on, if I save a file manually using Command+S on a Mac or the File menu, there is no way for me to tell that the file was actually saved. Given that the auto-save feature is on and the delay might be set to a very small amount , this might seem unnecessary, but either getting a prompt that auto-save is on or no changes to save or that file changes were saved after I manually hit save would not make it seem like nothing is happening when I am trying to save the file manually.

With a browser-based IDE which is prone to session time outs, not getting feedback from the IDE when I issue a command or use the menu might incorrectly signal end of a session or cause an unnecessary panic that the IDE is not responding.

**Comment by lostintangent** [comment]
Thanks for reporting this! VS Code already provides a visual cue for indicating that a file is "dirty" (has unsaved changes), which displays a dot in the editor's tab handle (to the right of the file name). That provides a subtle/unobtrusive way to know that your changes have/haven't been saved, without us needing to rely on an additional UI treatment (which for many developers, could be extremely noisy). Does this seem sufficient for your needs?

As a result of this existing behavior, I'm going to close this issue as "won't fix". If you think this experience can be improved, it would be awesome if you could file an awesome on the microsoft/vscode repo, so we can discuss the right behavior for VS Code all-up, and not just Codespaces. Thanks!
