### ISSUE TITLE
I can't create codespace

### ISSUE THREAD

**Issue by studyingJM** [MicrosoftDocs/vscodespaces#739]
Create New Codespace: Please try again in a few minutes or select a plan in another location.

**Comment by jkeech** [comment]
Sorry for the inconvenience! We have an outage right now in a couple regions: https://vsstatus.visualstudio.com/. We're working to bring those regions back up as quickly as possible.

**Comment by taiyosogawa** [comment]
Fix is currently rolling out to all regions.

**Comment by taiyosogawa** [comment]
Thank you for reporting. The issue has been resolved - please give it another try.
