### ISSUE TITLE
Cannot start workspace

### ISSUE THREAD

**Issue by Band-Aid** [MicrosoftDocs/vscodespaces#740]
I keep on getting an error and unable to start a workspace.
I've been trying for the past 30 mins but still no luck. Also tried booting the workspace from VSCode but still no luck.

![image](https://user-images.githubusercontent.com/21311546/90034455-9c92f480-dcfb-11ea-8258-2a74a2eff286.png)

**Comment by jkeech** [comment]
Sorry for the inconvenience! We have an outage right now in a couple regions: https://vsstatus.visualstudio.com/. We're working to bring those regions back up as quickly as possible.

**Comment by taiyosogawa** [comment]
Fix is currently rolling out to all regions.

**Comment by taiyosogawa** [comment]
Thank you for reporting. The issue has been resolved - please give it another try.
