### ISSUE TITLE
Codespaces times out when running from Azure Functions

### ISSUE THREAD

**Issue by justinytchen** [MicrosoftDocs/vscodespaces#745]
I am currently trying to start a Codespaces session from an Azure Function (inside the profile.ps1 file) by downloading/extracting the executable and then running it on the first HTTP call. On the machine, it seems like the executable is running correctly and it generates a URL to the session, but when opening the session, it times out.

Error message:
Unable to open 'data': Unable to read file 'vscode-remote://vsonline+f9e2f5de-12fc-4ca4-9dd5-683ce202e34c/d:/home/data' (Error: Time limit reached).

**Comment by lostintangent** [comment]
We're in the process of [consolidating Codespaces into GitHub Codespaces](#788), and as part of that, we need to migrate our self-hosted support to GitHub's CLI in the future. In the meantime, we're not investing time into any new use cases for it, and so I'm going to close this as won't fix for now. If this is a scenario you'd still like for us to support, it would be awesome if you could comment on [this issue](https://github.community/t/self-hosted-codespaces/131361/19), which we're using to collect feedback on self-hosted support in GitHub Codespaces. Thanks!
