### ISSUE TITLE
[iOS][Safari] Login failed due to unexpected error

### ISSUE THREAD

**Issue by MarczakIO** [MicrosoftDocs/vscodespaces#746]
Failed to login on Safari on iOS.

Works fine on Edge on iOS. Re-logging and closing browser didn’t help.

<img width="479" alt="Visual Studio Codespaces" src="https://user-images.githubusercontent.com/32310272/90315809-94ff6580-df1e-11ea-9f4d-fe4f99f874e2.png">

**Comment by VincentDondain** [comment]
@MarczakIO can you try disabling Safari's cross-site tracking (Settings > Safari > Turn off Prevent Cross-Site Tracking)?

**Comment by VincentDondain** [comment]
Should be similar to https://github.com/MicrosoftDocs/vscodespaces/issues/362 (feel free to reopen this issue if the above workaround didn't work for you).
