### ISSUE TITLE
Share plan with other users?

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/vscodespaces#752]
Where's the documentation on how to share a billing plan with other users? The one I created can only be seen by me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30864310-18d0-1b24-10c8-7ba05b13040a
* Version Independent ID: 5ef5fedc-4da1-7d80-8a77-a3f01baf76a6
* Content: [Visual Studio Codespaces with a browser Quickstart - Visual Studio Codespaces](https://docs.microsoft.com/en-us/visualstudio/codespaces/quickstarts/browser)
* Content Source: [vscodespaces/quickstarts/browser.md](https://github.com/MicrosoftDocs/vscodespaces/blob/master/vscodespaces/quickstarts/browser.md)
* Product: **visual-studio-family**
* Technology: **visual-studio-codespaces**
* GitHub Login: @nikmd23
* Microsoft Alias: **nimolnar**

**Comment by 2percentsilk** [comment]
As of right now, plans are per-user. We are evaluating organization support and multi-user plans but have no dates to share at this point.

**Comment by OffColour** [comment]
Can you you updagte the documentation to state this please? We wasted a load of time trying to set permissions to make this work as it's no use to us without it.

**Comment by chryw** [comment]
@OffColour Thanks for posting this! I also wasted hours to figure out role assignment.

**Comment by OffColour** [comment]
> @OffColour Thanks for posting this! I also wasted hours to figure out role assignment.
> Update: In case anyone else is looking for team/org billing plan info, @2percentsilk kindly pointed me to this solution --> give users a role with write access on the **subscription** scope. Just tried it and it works. Thanks @2percentsilk !

Definitely have to create a new subscription specifically for it then!

**Comment by nikmd23** [comment]
With the announcement that [Visual Studio Codespaces is consolidating into GitHub Codespaces](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), this doc update is no longer necessary. GitHub Codespaces does not have the concept of a Plan like VS Codespaces did. I'm closing this issue.
