### ISSUE TITLE
Unable to register Codespace

### ISSUE THREAD

**Issue by martellaj** [MicrosoftDocs/vscodespaces#755]
Transferred from: https://github.com/microsoft/vscode/issues/105016

Issue Type: <b>Bug</b>

I've been using Codespaces since Microsoft started WFH. Today, I was unable to connect to my Codespace that's registered on my dev box at work. I connected to my machine and tried unregistering and re-registering it, but it gets stuck (~over 15 minutes~ indefinitely) on the "Registering Codespace..." step. 

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (24.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
sort-typescript-imports|mic|1.4.1
vscode-azureappservice|ms-|0.18.0
csharp|ms-|1.23.0
azure-account|ms-|0.9.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.2669
debugger-for-chrome|msj|4.12.10
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.35
ejs-language-support|Qas|0.0.1
project-snippets|reb|0.5.0
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by martellaj** [comment]
FWIW, there are 2 other people on my team (we work on outlook.com) who are also experiencing this issue.

**Comment by 2percentsilk** [comment]
@taiyosogawa any ideas?

**Comment by martellaj** [comment]
I left it running since I created the original issue (about 3 hours ago) and I just got the notification that it was registered, but it didn't actually work.

![image](https://user-images.githubusercontent.com/1019478/90685538-ccbc2500-e21e-11ea-895c-e83b0a43f43f.png)

**Comment by martellaj** [comment]
I found the output with an error message:

[SelfHostedCodespaceRegistration I] vso: [2020-08-19 20:28:05.290 SelfHostedAgent E]

{
  "Time": "2020-08-19T20:28:05.290284Z",
  "Message": "selfhostedmonitor_monitorasync-share-error",
  "Level": "error",
  "OptionalValues": {
    "Attempt": "1",
    "ErrorException": "RemoteInvocationException",
    "ErrorMessage": "Value cannot be null. (Parameter 'hubClientHost')",
    "ErrorDetail": "[RemoteInvocationException]: Value cannot be null. (Parameter 'hubClientHost')\r\n--- Stack Trace ---\r\nMicrosoft.Cascade.Rpc.RemoteInvocationException: Value cannot be null. (Parameter 'hubClientHost')\r\n   at Microsoft.Cascade.Rpc.ResponseError.ThrowAsException() in E:\\A\\_work\\581\\s\\src\\Rpc\\Messages.cs:line 624\r\n   at Microsoft.Cascade.Rpc.RpcProxy.SendRequestAsync(RequestMessage request, CancellationToken cancellationToken, IProgress`1 progress) in E:\\A\\_work\\581\\s\\src\\Rpc\\RpcProxy.cs:line 240\r\n   at Microsoft.Cascade.Rpc.RpcProxy.InvokeWithResultAsync[TResult](String methodName, Object[] arguments, CancellationToken cancellationToken) in E:\\A\\_work\\581\\s\\src\\Rpc\\RpcProxy.cs:line 196\r\n   at Microsoft.VisualStudio.VSOnline.Core.Managers.WorkspaceManager.ShareAsync(ICascadeClient client, String path, Boolean allowAnonymousGuests, String workspaceId, UserAccountInfo userAccountInfo) in E:\\A\\_work\\581\\s\\src\\VSOnline\\Core\\Managers\\WorkspaceManager.cs:line 113\r\n   at Microsoft.VisualStudio.VSOnline.Core.Managers.WorkspaceManager.ShareAsync(String path, Boolean allowAnonymousGuests, String workspaceId, String pipeName, String serviceUri, UserAccountInfo userAccountInfo) in E:\\A\\_work\\581\\s\\src\\VSOnline\\Core\\Managers\\WorkspaceManager.cs:line 77\r\n   at Microsoft.CloudEnvironments.CLI.VmAgent.Monitoring.Monitors.SelfHostedMonitor.MonitorAsync(Action`3 OnMonitorDataReady, IDiagnosticsLogger logger) in E:\\A\\_work\\581\\s\\src\\VSOnline\\CLI\\VmAgent\\Monitoring\\Monitors\\SelfHostedMonitor.cs:line 81\r\n",
    "CorrelationId": "7295c8f3-9a95-4cfc-aed9-393a53405fb5",
    "VsoAgentVersion": "1.0.2675.37553",
    "ComputeResourceId": "8b28e472-8094-40ec-a6f2-0ff3cef123ed",
    "ComputeId": "8b28e472-8094-40ec-a6f2-0ff3cef123ed",
    "RunAsUser": "REDMOND\\joem",
    "CloudEnvironmentId": "8b28e472-8094-40ec-a6f2-0ff3cef123ed"
  }
}

**Comment by taiyosogawa** [comment]
@rodrigovaras, this looks like it could be related to your changes on Friday. I don't have context on the hubClientHost - do you know what conditions would cause it to be null?

**Comment by rodrigovaras** [comment]
Investigating but it looks that now we require a valid hub clieint host to share, will create a PR to fix it.

**Comment by rodrigovaras** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/Cascade/pullrequest/268901

**Comment by martellaj** [comment]
@rodrigovaras Thanks for addressing so quickly! How can we expect the change to make it to Code?

**Comment by rodrigovaras** [comment]
the PR has just completed, not sure how you guys pull new images from our master branch.

**Comment by taiyosogawa** [comment]
We're deploying a hotfix. Should be out shortly.

**Comment by taiyosogawa** [comment]
The hotfix has been deployed - please give it another shot. If you ran from vscode, no extension update is required.

**Comment by martellaj** [comment]
@taiyosogawa @rodrigovaras Thanks again! Just confirmed that it's fixed for me.
