### ISSUE TITLE
register the server

### ISSUE THREAD

**Issue by enhuichang** [MicrosoftDocs/vscodespaces#764]
https://online.visualstudio.com/environment/0a46ec82-e848-42de-a517-0b7ad1b51f2f

i tried register the server.However it is failed

**Comment by smvanderweide** [comment]
You can work around this issue by creating a plan in your current location from online.visualstudio.com or by using the Codespaces extension in VSCode. If you are unsure which location you are currently in you can go to online.visualstudio.com/api/v1/locations. If you create your codespace using that plan, it should work.

**Comment by khkh-ms** [comment]
We have deployed the fix this week. You should not need workaround to connect to your codespace.
