### ISSUE TITLE
Increase docker shared memory?

### ISSUE THREAD

**Issue by jkiritsis-public** [MicrosoftDocs/vscodespaces#772]
I'm trying to follow the fastai course (https://github.com/fastai/course-v4), using codespaces for the jupyter notebook. 
however im getting an error from pytorch about running out of memory (chapter 1, run your first notebook), which according to this: https://github.com/ElderResearch/gpu_docker/issues/38 seems to be because docker is configured with too low shared memory.
I checked my codespace creation logs and there did not seem to be any docker command for shared memory, so that might be something that is needed?

My codespace is the standard plan, so i dont think it should run out of memory, but i might have misunderstood something.

Steps to reproduce:
1. Create standard codespace
2. connect through vscode.
3. Create new jupyter notebook.
4. Change python to 3.8. (install whatever vscode tells you to install to make it work)
5. Restart the notebook to use new interpreter.

Now, run the following commands in the notebook, in their own separate widgets.
1. !git clone https://github.com/fastai/course-v4
2. pip install torch torchvision
3. pip install fastai

Now, open the 01_intro.ipnyb in the nbs folder and run the widget under "Running your first notbook". It should fail with "DataLoader worker (pid 942) is killed by signal: Bus error. It is possible that the dataloader's workers are out or shared memory. Please try to raise your shared memory limit".

I also tried installing the pytorch libraries for CPU usage, but got the same result.

**Comment by jkeech** [comment]
@jkiritsis-public, the Standard Linux SKU has 8 GB of RAM, and we do not limit RAM inside the docker container today -- you have access to the full available system memory. If you run `top` or `free -m` while your app is running, what does the memory utilization say? If you are maxing out at 8 GB and need more RAM, you could upgrade to Premium Linux which will give you 16GB of RAM.

**Comment by jkiritsis-public** [comment]
thank you for your response.

Top says that i have 1gig free, 2gig used, and 5gig buff/cache.
free says i have 0.5 gig free, 5.2 gig available.

In my linked issued they said they needed to launch docker with --shm-size=8G to make it work, that is not relevant here?

**Comment by jkeech** [comment]
@jkiritsis-public, are you running multiple containers and trying to share memory between them? If so, how are you spinning up the second container (not the main Codespace one that the Codespace service spins up for you)?

**Comment by jkiritsis-public** [comment]
no only the default container, but i did not know if that command had any effect on your internal handling of the containers.
I managed to get it working by limiting the batch-size, so it was clearly memory related at least.. i dont know if i used all 8 gig, but it seems like the most reasonable assumption right now so i will close this.

thank you very much for your quick replies and your help.

**Comment by jkeech** [comment]
@jkiritsis-public, it's possible that the shared memory was still an issue. We don't currently support overridding `shm-size` unless you use a devcontainer.json that references a Docker Compose file (https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir). But we could add that support if needed.
