### ISSUE TITLE
Make the CODESPACES env var available before the initializeCommand is run

### ISSUE THREAD

**Issue by BerriJ** [MicrosoftDocs/vscodespaces#777]
Hi,

I recently created a [devcontainer boilterplate](https://github.com/BerriJ/devenv)  for coding in R, Python, and writing in Latex.  This works flawlessly on Manjaro / Arch with VS-Code locally. It pulls the docker image from dockerhub and sets up some vs-code extensions. However, opening this repo in codespaces fails with at "Preparing you Codespace". It says "The Codespace failed". How can I access the logs?

![image](https://user-images.githubusercontent.com/37799358/91582182-bd8c5400-e94f-11ea-9a2c-20a3abd4351f.png)

The [repo](https://github.com/BerriJ/devenv) is public so please try it if you want.

Thanks in advance
BerriJ

**Comment by jkeech** [comment]
Thanks for reporting this @BerriJ! We have a bug where the logs are not being surfaced properly today for this type of failure. I looked at the logs on the backend, and it's failing in the `initializeCommand`. It looks like `xhost local:root` is causing the problem. I removed it in my testing and the Codespace spun up successfully.

**Comment by BerriJ** [comment]
Oh thank you so much. This is great news. However since I'm also using it locally: is there some way to ignore this when setting up a GitHub codespace but executing it when running locally? Maybe some kind of if else check?

Thanks again. :)

**Comment by jkeech** [comment]
cc @Chuxel 

Unfortunately, there's not a good way to condition that out in Codespaces in the `initializeCommand` right now. Inside the container, we set an environment variables `CODESPACES=true`, but we don't currently set that when the `initializeCommand` is running. Maybe there is some other environment variable check you could do to differentiate local vs Codespaces and then only run the `xhost` command if the variable is set. The if/else conditioning would need to be via the inline script inside `initializeCommand`.

**Comment by BerriJ** [comment]
Thanks for this hint. I'll look into this and I'm more than motivated to open a PR if I come up with something amazing. :)

**Comment by jkeech** [comment]
Let us know if you find something that works! We can also look at adding the `CODESPACES=true` variable during the `initializeCommand` execution to make conditional behavior for Codespaces in that script much easier.

**Comment by BerriJ** [comment]
I think adding CODESPACES=true at the stage the `initializeCommand` runs would be fantastic.

For now, I fixed it like this:

I'm setting CODESPACES=false locally in my .zshrc and I've inserted an if-statement into the `initializeCommand`:

`"initializeCommand": "docker pull berrij/devenv:master; if [ '$CODESPACES' = false ]; then xhost local:root; fi",
`
Obviously, this isn't optimal since manual work is needed on the local machines. So adding the CODESPACES=true variable inside the remote would be fantastic.

However, I intended to source all those init commands from an external script like [that](https://github.com/BerriJ/devenv/commit/e03467a022f1239ea274d256a20e35e234f5e176). However, this didn't work although it should be equivalent to my code above. I bet the script isn't executable in the cloud?!

Thanks again :)

**Comment by lostintangent** [comment]
@jkeech Did we still want to use this issue to track making the `CODESPACES` env var available before the `initializeCommand` script was run? Otherwise, it seems like we have resolved the issue of errors not being properly surfaced?

**Comment by jkeech** [comment]
> @jkeech Did we still want to use this issue to track making the `CODESPACES` env var available before the `initializeCommand` script was run? Otherwise, it seems like we have resolved the issue of errors not being properly surfaced?

Yep, we can use this issue to track making the `CODESPACES` variable available on the host for `initializeCommand` in addition to the existing variable we set on the container.

**Comment by lostintangent** [comment]
@jkeech OK cool, I'm updating the title of this issue then. Thanks!

**Comment by jkeech** [comment]
This change has been deployed! The `CODESPACES=true` variable is now available for the `initializeCommand` to read if you want conditional logic that only runs in a Codespace.

Here's a minimal example devcontainer.json:
```
{
    "initializeCommand": "echo CODESPACES=$CODESPACES",
    "image": "mcr.microsoft.com/vscode/devcontainers/base:ubuntu"
}
```

Creation log output:
```
COMMAND: /bin/sh -c "echo CODESPACES=$CODESPACES"
Started: 2020-11-06T00:07:15
CODESPACES=true
/bin/sh process exited with exit code 0
Finished: 2020-11-06T00:07:15
```
