### ISSUE TITLE
Codespaces cannot start or join live share audio call 

### ISSUE THREAD

**Issue by vrlb** [MicrosoftDocs/vscodespaces#778]
Hi,

I am using vscodespaces live share on Edge browser but i cannot start an audio call. Even when people (who started an audio call in vscode) invited me to join, I got the invite notification, but the `Audio Call` in `Session Details` did not change. May I know how to fix this?

Machine: Linux, 4 Cores, 8 GB

**Comment by lostintangent** [comment]
Hey! Codespaces doesn't currently support the Live Share Audio extension. If this is something you'd like to see supported, it would be awesome if you could file a feature request on the microsoftdocs/live-share repo. Thanks!
