### ISSUE TITLE
Creating codespace will always fail

### ISSUE THREAD

**Issue by sawa-zen** [MicrosoftDocs/vscodespaces#780]
When I try to create a Workspace in Codespaces, it always goes to Failed to create and I can't create it. What can I do to solve this problem? I'm having trouble finding a place to look at the logs, etc. and I don't have any hints.

The Workspace screen only showed a WebSocket error
![ZI95jUDB](https://user-images.githubusercontent.com/3971271/92009319-4ad20d00-ed83-11ea-8e7e-b367bd7440fa.jpg)

**Comment by jkeech** [comment]
@sawa-zen, are you using a custom container config in `devcontainer.json`? If so, can you share the repo or a minimal example that reproduces the issue?

We do have a bug right now where the creation logs are hidden soon after the environment goes into a Failed state, which makes it hard to debug (/cc @chkn). But you might be able to see the failure logs in the terminal for a split second before it refreshes (possibly with a screen recording that you can pause). You won't be able to see the logs in the console or network tab -- they are expected to show up on the page itself when the creation fails.

**Comment by sawa-zen** [comment]
@jkeech 
I'm not using devcontainer.json. And I couldn't see any errors in the console either :(

**Comment by jkeech** [comment]
@sawa-zen, can you share the repo you are using during the creation if it's not sensitive? Also, can you share the url you see during the creation (particularly the id at the end of the url)?

**Comment by lostintangent** [comment]
We've recently improved the error logging for Codespace creation, and so I'm going to close this as resolved. If you're still running into an issue, please re-open this and we'll investigate your specific repro. Thanks so much!
