### ISSUE TITLE
Can not resume my code space

### ISSUE THREAD

**Issue by pawanpyakurel** [MicrosoftDocs/vscodespaces#782]
Issue Type: <b>Bug</b>

for some reason I can not resume my code space. My codespace used to frequently get disconnected but this time i can't resume it . I have lot of my uncommitted changes  in the codespace . Could you please help me resume my codespace so that i can get my work done ?

Your help is greatly appreciated.

Thanks
Pawan 

Extension version: 1.0.2739
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.30GB free)|
|Process Argv|C:\pawan\Evivez\evivez-web|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jkeech** [comment]
Hi @pawanpyakurel, sorry you are running into problems resuming your Codespace. Can you share the ID (or the full url that shows up when you try to resume it)? We’ll be happy to take a look at trying to get it working again for you.

**Comment by csjune** [comment]
Me neither. I can't resume my codespace on browser and vscode. Is there a general way to fix this? @jkeech

**Comment by jkeech** [comment]
@csjune, can you provide your Codespace Id for us to take a look?

**Comment by csjune** [comment]
> 
> 
> @csjune, can you provide your Codespace Id for us to take a look?

Sure. It's https://online.visualstudio.com/environment/6cb85818-9b5c-4658-8747-8afea6a99fbe

**Comment by klvnraju** [comment]
@csjune, looks like the filesystem got corrupted which we fixed. Can you try resuming the codespace now and tell if that worked from your end?

Note that it is going to take a bit longer for the first time when you resume.

**Comment by csjune** [comment]
> 
> 
> @csjune, looks like the filesystem got corrupted which we fixed. Can you try resuming the codespace now and tell if that worked from your end?
> 
> Note that it is going to take a bit longer for the first time when you resume.

@klvnraju I tried to resume my codespace again and again but I got same error "Connecting to Codespace {CODESPACE NAME} failed. Error". I also tested to create new codespace, it failed too.

**Comment by jkeech** [comment]
Closing this issue since we haven't heard back. Please re-open if this is still a problem. Thanks!
