### ISSUE TITLE
Web UI unable to create or connect to a codespace in sponsored or paid subscription

### ISSUE THREAD

**Issue by nialldalton** [MicrosoftDocs/vscodespaces#783]
**Summary**

- the web ui at https://online.visualstudio.com/environments is unable to create a codespace and gets stuck in a loop trying to create a billing plan; some resources are visible via Azure portal
- the web ui is unable to connect to a no-repo codespace I create via VSCode
- the preview command group `codespace` in `az` in unable to show details of any created codespace nor create one
- I can create an empty codespace using vscode
- I cannot create a codespace with a private / secured repo in vscode since authentication is not being handled properly; it only handles the case where no password/personal access token is required to clone the repo. Using a workaround of externally caching the credentials allows vscode to clone the repo within the codespace.

**Versions of client software**

- MacOS 10.15.6
- Microsoft Edge  85.0.564.44
- Google Chrome 85.0.4183.83
- `az` version is
```
{
  "azure-cli": "2.11.1",
  "azure-cli-core": "2.11.1",
  "azure-cli-telemetry": "1.0.5",
  "extensions": {
    "codespaces": "0.3.0"
  }
}
```

**Problems observed**

NB. clearing caches, logging in/out, and other such common web client advice has no impact on any of the problems below.

1. It takes the web ui several minutes to go from "Fetching your codespaces" to timing out and giving the "You don't have any codespaces" message.

![Screen Shot 2020-09-03 at 6 10 50 AM](https://user-images.githubusercontent.com/539805/92120788-5981e980-edae-11ea-882a-3dcfecd9caae.png)

2. Although billing plans are created within the subscription, they are never shown in the web ui, so I'm stuck in a loop where the only path is to "Create new plan".

![Screen Shot 2020-09-03 at 6 11 21 AM](https://user-images.githubusercontent.com/539805/92120842-68689c00-edae-11ea-8e32-6b7ee1b18300.png)

3. Sometimes, when attempting to use the same plan name, I get a "204 - Access Failed" error.

4. Attempting to examine the plans created by the web ui using `az` fails:

```
% az codespace list --plan vscs-plan-westus2 --resource-group vscs-rg-1ffb379
Command group 'codespace' is in preview. It may be changed/removed in a future release.
ResourceNotFound - The Resource 'Microsoft.Codespaces/plans/vscs-plan-westus2' under resource group 'vscs-rg-1ffb379' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

Looking in the Azure portal, I see this:

```
{
  "id": "/subscriptions/XXX/resourceGroups/vscs-rg-1ffb379/providers/Microsoft.VSOnline/plans/vscs-plan-westus2",
  "name": "vscs-plan-westus2",
  "type": "Microsoft.VSOnline/plans",
  "location": "WestUs2",
  "tags": {},
  "properties": {
    "userId": "CurrentUser"
  }
}
```

where XXX is actually my real and correct subscription id. I have also tried various fresh resource groups / plans.

5. I can create an empty (no repo) codespace via VSCode but then the web ui cannot connect to it:

![Screen Shot 2020-09-03 at 6 42 48 AM](https://user-images.githubusercontent.com/539805/92122850-d3b36d80-edb0-11ea-8e05-651716fdcacb.png)

6. I cannot create a codespace with a repo since authentication to github cannot be provided as far as I've found so far. I tried using https as documented since ssh keys are not supported. The VSCode extension does not prompt for a password, where I can provide a personal access token since 2FA is enabled on the repo, so the codespace cannot be created as the repo cannot be cloned. Working around this, purely to test as this is not sufficient for general use, via external caching allows the clone to proceed.

I'm happy to provide further information in private if Microsoft wants to look at the Azure side of things etc.

**Comment by nialldalton** [comment]
FWIW this silently cleared itself up from one day to the next so closing it with the assumption everything has been handled behind the scenes!

**Comment by nialldalton** [comment]
Well serves me right for tempting fate; it looks like authentication is having trouble and preventing users from opening existing spaces or creating new ones.

![Screen Shot 2020-09-14 at 11 47 23 AM](https://user-images.githubusercontent.com/539805/93125525-224deb00-f680-11ea-8348-e0b0299b64a5.png)

**Comment by jkeech** [comment]
@nialldalton, there's an ongoing incident right now affecting Codespaces ☹️. We're working on getting it back up ASAP. https://vsstatus.visualstudio.com/

**Comment by nialldalton** [comment]
#hugops!

**Comment by contention** [comment]
@jkeech Does that outage affect GitHub codespaces too? Struggling to connect there as well. 😬

**Comment by jkeech** [comment]
> @jkeech Does that outage affect GitHub codespaces too? Struggling to connect there as well. 😬

Yes, it does. A fix is being deployed now.

**Comment by jkeech** [comment]
@nialldalton, @contention we are starting to see recovery of the service now and resumes of existing Codespaces should start working. We're going to validate for a few more minutes and then re-enable new Codespace creations in GitHub Codespaces.

**Comment by jkeech** [comment]
The incident affecting Codespaces has been resolved and creation/resume should be working again. I'm going to go ahead and re-close this issue, but please open a new one if you continue to see any issues. Thanks!
