### ISSUE TITLE
CANT SIGN IN TO online visual studio

### ISSUE THREAD

**Issue by ash-netizen** [MicrosoftDocs/vscodespaces#785]
cant sign in to https://online.visualstudio.com/ as it throws below error

![image](https://user-images.githubusercontent.com/50423343/92137850-4f520080-ee2b-11ea-87db-5eb3126200b7.png)

Please help..

**Comment by jkeech** [comment]
@ash-netizen, can you try from an Incognito/In-Private browser session in case there are some cookie/local storage issues interfering with the login?

**Comment by ash-netizen** [comment]
Thanks, I ended up installing desktop client and it works well.

**Comment by ash-netizen** [comment]
Desktop Client works just fine after installing necessary extensions.
