### ISSUE TITLE
Unable to change Instance Type in GitHub Codespaces

### ISSUE THREAD

**Issue by Rishit-dagli** [MicrosoftDocs/vscodespaces#790]
Issue Type: **Feature Request**

While using [GitHub Codespaces](https://github.com/codespaces) and creating a new codespace I have no option where I could change the Instance Type. As of now, I believe an instance type is pre-specified for you maybe while reviewing a PR a "Basic" instance is created, and so on. It would be helpful to have this option customizable by the user while creating a codespace.

Though I have not yet tried it out I believe that this could maybe be customized with the Preferences Sync, but it would be great to have this right while creating one.

**Comment by lostintangent** [comment]
Hey! We'll be adding support for changing the instance type in GitHub Codespaces very soon 👍 Additionally, we're in the process of moving all GitHub-specific discussions to the [GitHub Support Community](https://github.community/c/codespaces-beta/45), and so if you wanted to start this conversation there, that would be awesome. Thanks!

**Comment by Rishit-dagli** [comment]
> Hey! We'll be adding support for changing the instance type in GitHub Codespaces very soon 👍 Additionally, we're in the process of moving all GitHub-specific discussions to the [GitHub Support Community](https://github.community/c/codespaces-beta/45), and so if you wanted to start this conversation there, that would be awesome. Thanks!

Sure I could port this request on GitHub support community to be notified when this feature would be live. Thank you.
