### ISSUE TITLE
Cannot login / use codespaces in Safari

### ISSUE THREAD

**Issue by dbogatov** [MicrosoftDocs/vscodespaces#791]
This is from https://github.com/microsoft/vscode/issues/105452

- VSCode Version: whatever is latest in codespaces now
- OS Version: browser (Safari)

**I honestly tried to use Microsoft support, but that seems to be for business customers only**

Steps to Reproduce:

1. Go to online.visualstudio.com
2. Click "Sign in" button
3. Observe constant redirects
4. Observe "Login failed due to an unexpected error. Please log out and try again."

**I am absolutely sure that my account is OK, I can login with Chrome and I know my password!**

Also, I tried private tab, clearing cookies etc.
From googling I see that people generally can use codespaces from iPad and Mac Safari.
So I think there may be something wrong with my account.
Could you please help?

Does this issue occur when all extensions are disabled?: N/A

**Comment by lostintangent** [comment]
@legomushroom @plisy Do we have any known issues with Safari?

**Comment by legomushroom** [comment]
@dbogatov can you try enabling 3rd party cookies for the `online.visualstudio.com` domain? 

That is under Preferences -> Privacy :

![image](https://user-images.githubusercontent.com/1478800/92949721-6aff6d00-f410-11ea-98bf-5481313c852b.png)

Please let me know if that makes any difference to you. We currently rely on `microsoftonline` for authentication which is confidered 3rd party by the browser since the domains not match. cc @klvnraju

**Comment by dbogatov** [comment]
@legomushroom I’ll try soon, thank you!

**Comment by dbogatov** [comment]
By the way, I recently got an invite to Codespaces beta and I can say that iPadOS Safari works like a charm with it.
Which makes me blame authorization even more.

There are some issues, of course, like not being able to scroll with trackpad and cmd+w not closing a tab, but I guess those are separate issue and will be resolved separately.

**Comment by legomushroom** [comment]
@dbogatov 

We've announced [sunsetting VSO service in favor of GitHub Codespaces recently](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/), so I'd suggest migrating to GitHub if possible. 

For the `cmd + w` issue, that an issue that we actively looking into now, there are few workarounds:

- use full-screen mode when possible
- install the codespace as PWA

Both allow the `cmd + w` shortcut to be intercepted by the vscode workbench so it works as expected out of the box.

For the `scroll with trackpad` issue, @VincentDondain was looking at the possible solutions.

**Comment by VincentDondain** [comment]
Hi,

The scrolling issue is unfortunately a bug in WebKit and it's being tracked by the VSCode team here: https://github.com/microsoft/vscode/issues/106232

**Comment by lostintangent** [comment]
Closing this as resolved, since @dbogatov has migrated to GitHub Codespaces ad is't encountering this issue anymore. Please re-ope it if you're still encountering a login problem. Otherwise, we'll track Safari bugs via other issues. Thanks!

**Comment by wziska** [comment]
I have exactly the same problem on ipad using Safari browser. Unfortunately I wasn’t lucky enough and didn’t get access to GitHub’s codespaces (i’m on the waitlist couple of months). @lostintangent is there any chance to speed up the process of getting the access (it looks like this issue won’t be fixed anytime soon)?

**Comment by 2percentsilk** [comment]
@wziska if you're the subscription owner for the account you use with VS Codespaces, you should have gotten an email with steps for expedited access. If you can't find that email, feel free to [contact us](vscs-transition-help@microsoft.com) for further help.

**Comment by wziska** [comment]
Thanks for help. I’m using MSDN subscription to access VS codespaces, but didn’t get any email. And the link above leads nowhere.

**Comment by 2percentsilk** [comment]
Whoops link error. Give it a shot now :)
