### ISSUE TITLE
Doesn't sign in

### ISSUE THREAD

**Issue by MintStudios** [MicrosoftDocs/vscodespaces#793]
Issue Type: <b>Bug</b>

Install codespaces
Click sign in
continue button doesn't do anything on microsoft page, and signing in never works.

It should work

Extension version: 1.0.2779
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lostintangent** [comment]
@legomushroom Any thoughts here on what might be going on?

**Comment by legomushroom** [comment]
@MintStudios what browser do you use? "continue", does it brings vscode to the focus?

**Comment by MintStudios** [comment]
Restarting VS Code seemed to fix the issue. I'm not sure what caused it, but it's fixed.
