### ISSUE TITLE
VSCode Extension is breaking the certificate chain for other extensions

### ISSUE THREAD

**Issue by GordonSmith** [MicrosoftDocs/vscodespaces#803]
Installing https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline is breaking other VS Code extensions.

In my case the following JavaScript call is failing:
```
fetch("https://play.hpccsystems.com:18010/WsWorkunits/WUQuery.json")
    .then(r=>r.json())
    .then(d=>console.log(d))
    .catch(e=>console.error(e.message))
    ;
``` 
With the following error:  
```
request to https://play.hpccsystems.com:18010/WsWorkunits/WUQueryjson failed, reason: unable to verify the first certificate
```

Uninstalling this extension resolves the issue.

**Comment by lostintangent** [comment]
@plisy this seems related to the issue with us injecting a global `fetch`? I'm going to close this as resolved, but please confirm that that's correct, and re-open it if necessary. Thanks!

**Comment by GordonSmith** [comment]
That sounds plausible especially if you are not handling the "rejectUnauthorized" option?  Is there an issue I can track (or has a fix been released)?

**Comment by plisy** [comment]
@GordonSmith We used to polyfill fetch in the extension but we fixed that last week.
