### ISSUE TITLE
Missing Azure Subscriptions in Visual Studio CodeSpaces 

### ISSUE THREAD

**Issue by SalmanKaleem** [MicrosoftDocs/vscodespaces#805]
We have a requirement for 100 deployments of Visual Studio Codespaces. However, I cannot provision due to unavailability of subscriptions in the drop down list. I have already enabled Visual Studio and  resource providers in the Subscription and provided admin consent for the use of the VS within Azure AD.

https://login.microsoftonline.com/%7Btennant_id%7D/adminconsent?client_id=a3037261-2c94-4a2e-b53f-090f6cdd712a&redirect_uri=https://online.visualstudio.com
https://login.microsoftonline.com/%7Btennant_id%7D/adminconsent?client_id=9db1d849-f699-4cfb-8160-64bed3335c72&redirect_uri=https://online.visualstudio.com

**Comment by jkeech** [comment]
Hi @SalmanKaleem, thanks for your interest in Codespaces! In case you haven't heard, we are transitioning to GitHub Codespaces, which is built directly into GitHub. As part of that change, we are retiring our Azure service in the next couple months: https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/. I would recommend looking to see if GitHub Codespaces would be a good fit for your organization and not starting with a new deployment of Visual Studio Codespaces in your Azure subscriptions.

**Comment by 2percentsilk** [comment]
Hi @SalmanKaleem, can you clarify where you aren't seeing the subscription in the drop down list? Is this on the [portal](https://online.visualstudio.com)?

**Comment by SalmanKaleem** [comment]
I cannot see subscriptions in the drop down list while creating Codespaces in the following URL.
https://online.visualstudio.com/environments/plan?showCreateEnvironmentPanel=true

**Comment by 2percentsilk** [comment]
Is it possible you have multiple tenants/directories associated with your account? I hypothesize you might be running into something similar to folks in Issue #39

**Comment by SalmanKaleem** [comment]
I do have access to multiple tenants/directories and multiple subscriptions. What is the fix?

**Comment by jkeech** [comment]
Hi @SalmanKaleem, unfortunately there is no good solution for multi-directory AAD support in Codespaces. We only support the default tenant/directory today, and we are not investing further in adding multi-directory support since we are switching to GitHub Codespaces with GitHub auth.

**Comment by SalmanKaleem** [comment]
Is there a workaround to get this moving. Can we setup with an account
without access to multiple directories or subscriptions?

Regards,
Salman Kaleem

**Comment by lostintangent** [comment]
@jkeech Are there any workarounds for now? Otherwise, maybe we could help fast-track this customer into the GitHub beta to make sure they're unblocked for their hack-a-thon.

**Comment by jkeech** [comment]
@lostintangent, this customer already reached out via Azure support internally. I'm going to close this issue since we have the other offline conversation.
