### ISSUE TITLE
Github Codespaces OpenJDK12 support

### ISSUE THREAD

**Issue by Jas0nch** [MicrosoftDocs/vscodespaces#806]
I use openjdk12 in my local machine and it seems that openjdk12 is not supported yet in the Github Codespaces. Is there any method to use openjdk12 in github codespaces?

**Comment by jkeech** [comment]
@Jas0nch, can you ask the question at https://github.community/c/codespaces-beta/45? Support for GitHub Codespaces is through the GitHub Community site. Thanks! I'll be happy to provide a response over there for others to find it as well 😄
