### ISSUE TITLE
Spinner on suspended codespaces

### ISSUE THREAD

**Issue by kieferrm** [MicrosoftDocs/vscodespaces#812]
Issue Type: <b>Bug</b>

Using VS Code desktop:
1) Connect to a GH Codespace
2) Let it sit idle until it suspends
3) Dismiss the dialog
4) Open the Remote Eplorer

-> The suspended box shows with a spinner. This does not self-correct. I need to manually refresh the view.

![image](https://user-images.githubusercontent.com/4674940/94292053-4b3c6e80-ff11-11ea-9ce1-c6121e064249.png)

Extension version: 1.0.2823
VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:51.469Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_7628614 --crash-reporter-id d4b72415-0109-45b3-a1a7-967fdd12f0f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.61GB (3.81GB free)|
|VM|0%|
</details>

**Comment by srivatsn** [comment]
@taiyosogawa @wangjaso can you please take a look at this?

**Comment by taiyosogawa** [comment]
Hi, thanks for reporting - I just merged in a fix for this.

**Comment by lostintangent** [comment]
@taiyosogawa This appears to be fixed? Can we close this as resolved now? Thanks!

**Comment by taiyosogawa** [comment]
Yep! Please let us know if you continue to see this issue in the latest available version of the Codespaces extension (>= 1.0.3007)
