### ISSUE TITLE
My codespaces cannot be resumed 

### ISSUE THREAD

**Issue by tszkanlo** [MicrosoftDocs/vscodespaces#816]
My codespaces is https://online.visualstudio.com/environment/177aefca-5f28-40f8-89b6-6f4bfc6bf15d
I was using it yesterday and today it cannot be resumed. Please help on the issue and thank you.

**Comment by jkeech** [comment]
Hi @tszkanlo! Sorry you are having issues resuming your Codespace. We'll take a look to see if we can get it running again.

cc @lorenpaulsen, @jfullerton44

**Comment by lorenpaulsen** [comment]
We believe we have resolved the issue. Could you try starting this Codespace again?

**Comment by tszkanlo** [comment]
still cannot be connected. could you please help check on this again? thanks a lot

**Comment by cmbrose** [comment]
Hi @tszkanlo - I'm working on manually restoring your Codespace currently.

In the meantime, if it would help, I have archived the data on the disk and can send it to you - just reach out to me at bcaleb 'at' microsoft 'dot' com

**Comment by cmbrose** [comment]
I've also finished some manual steps to attempt to repair the codespace now - could you please try restarting it again?

**Comment by tszkanlo** [comment]
@cmbrose thank you for your help. I have just retried and seems the codespace is still not available to be resumed. 😢

**Comment by cmbrose** [comment]
Unfortunately I don't think Codespace can be repaired, but I've provided the archive via email. I'll go ahead and close this one.
