### ISSUE TITLE
Headless CodeSpaces Selfhosted environment. CLI Error: We could not find any subscriptions. Please create an Azure Subscription on 

### ISSUE THREAD

**Issue by subhankars** [MicrosoftDocs/vscodespaces#817]
I'm trying to create a headless CodeSpaces self-hosted machine. I have created an Ubuntu VM in Azure. Installed all the tools as per this [document](https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/vsonline-cli#installation).
While starting the CodeSpaces from the CLI, I'm getting below error after authentication. 

```
XXXuser@XXXX:~$ codespaces start -i /subscriptions/xxxxxxx-89c6-42d1-af31-e823280xxxxx/resourceGroups/codespace-rg/providers/Microsoft.VSOnline/plans/codespace-plan
[2020-10-08 15:59:31.706 CLI.start I] Authenticating...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXAYASQ to authenticate.
[2020-10-08 16:03:01.304 CLI.start I] When connecting to this Codespace, you will be logged in as: codespaceuser
Would you like to run as a persistent service/daemon? [Y]/[n]: y
[2020-10-08 16:03:04.298 CLI.start I] Will register as a service/daemon
[2020-10-08 16:03:04.637 CLI.start E] [!ERROR] We could not find any subscriptions. Please create an Azure Subscription on https://azure.microsoft.com.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ddae03-fc1a-52fb-b2fa-85e3afc51264
* Version Independent ID: 1c64c119-b551-9357-d905-2386eee4cd72
* Content: [How to use the Codespaces CLI](https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/vsonline-cli#start-codespaces)
* Content Source: [vscodespaces/reference/vsonline-cli.md](https://github.com/MicrosoftDocs/vscodespaces/blob/master/vscodespaces/reference/vsonline-cli.md)
* Product: **visual-studio-family**
* Technology: **visual-studio-codespaces**
* GitHub Login: @2percentsilk
* Microsoft Alias: **allisb**

**Comment by lostintangent** [comment]
Thanks for reporting this. We're tracking this issue via #775, so I'm going to close this as a duplicate and we can continue the conversation over there 👍
