### ISSUE TITLE
Can't resume codespaces

### ISSUE THREAD

**Issue by ganjarsetia** [MicrosoftDocs/vscodespaces#818]
**Describe the bug**
My codespaces (beta) https://ganjarsetia-api-express-mongo-gf44.github.dev/
I'm just doing open source project and feel enjoy using codespaces but
I accidentally stop the codespaces container. I tried open the my codespaces, it fail & show error.

![image](https://user-images.githubusercontent.com/3258090/95501452-87240900-09d2-11eb-95d6-75bea2e0dc7e.png)

**Expected behavior**
When click link existing codespaces, it should continue
 
Brower-based editor details:
- Browser Brave
- Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

So how to start the container/codespaces ? I have uncommitted files

**Comment by jkeech** [comment]
Hi @ganjarsetia, support for GitHub Codespaces is actually on github.community. This repo issue tracker is only for VS Codespaces (the Azure service). Can you repost your issue on https://github.community/c/codespaces-beta/45 so other GitHub Codespaces users can find it if they are running into the same issue?

That said, this looks like an issue with Brave (or maybe one of your browser extensions?) not sending the origin or referrer headers as part of the auth flow, which is a security check that our service is doing. We'll need to investigate more. In the meantime, you should be able to try from another browser like Chrome or Edge which should work.

**Comment by legomushroom** [comment]
@ganjarsetia we are restricting the origins of incoming transitions to the Codespace to come only from the `github.com` origin and as @jkeech said, looks like the Brave does not send those headers properly.

I was not able to repro this on mac osx, even with strict blocking policies so wondering if you have any additional extensions installed that can remove the headers. Did you try without any extensions installed?

**Comment by ganjarsetia** [comment]
@jkeech ah sorry I didn't know about that I'll close this issue. Thanks

@legomushroom No I dont have any extensions remove the headers. I tried your suggestion but it still failed. Btw I'm using Linux Pop OS 20.04 LTS

When I tried using firefox it works!

Do you think this is bug with Brave or cross browser ?

**Comment by legomushroom** [comment]
@ganjarsetia that only Brave browser bug - they claim to block and `Referer`/`Origin` headers to improve privacy which does not conform to the w3c spec. You can hit the same issue with some of the aggressive referer/origin header policies.

Maybe Linux has a slightly different model since I couldn't repo this on Mac OSx reliably.
