### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by chanrose** [MicrosoftDocs/vscodespaces#831]
Right now I am using Ionic React project on the Codespace in which usually works when I try to launch my development server with "npm start or ionic serve" but somehow now I try to run again, it doesn't work, it gives out error "504 Gateway Timeout" I tried with different connection and network as well but it doesn't work. I did tried to create a new blank project as well but it doesn't work out well either.
![image](https://user-images.githubusercontent.com/51664152/98250356-e7927000-1fa9-11eb-8abe-d2d9d0fb750e.png)

**Comment by srivatsn** [comment]
@plisy can we take a look at that request id?

**Comment by andyweiss1982** [comment]
I am having the same problem with a dead simple express app, request id is `aaf0128d52834c78261737742662fbae`.

**Comment by Tekiter** [comment]
Same issue here. Request id is `b841c9664530f0487edcad3e6f3979cc`

**Comment by samr28** [comment]
Also having this issue.

Nice pfp @Tekiter

**Comment by stefanjf** [comment]
Same error here. Request id 674c131586b940eb10c3fb7da264a46a

**Comment by plisy** [comment]
We've identified the cause and are working on a fix.

In the meantime opening the forwarded port from terminal output (ctrl/cmd + click on the localhost link) is a workaround.

**Comment by chanrose** [comment]
> 
> 
> We've identified the cause and are working on a fix.
> 
> In the meantime opening the forwarded port from terminal output (ctrl/cmd + click on the localhost link) is a workaround.

Somehow it works once a while

**Comment by ruthbacci** [comment]
I also have the same issue - Port forwarding used to work. Now I just get bad gateway.

**Comment by chanrose** [comment]
It works fine on me now. How about the others?
