### ISSUE TITLE
vsls agent using memory and cpu

### ISSUE THREAD

**Issue by ibuildthecloud** [MicrosoftDocs/vscodespaces#837]
**Describe the bug**
My environment is really quite slow and I discovered  /.codespaces/agent/bin/vsls-agent was using 5gb of ram and 100% CPU.  I don't know how to reproduce and now the VM is no longer accessible.

**To Reproduce**

**Expected behavior**

**Screenshots**

![vsls-agent](https://user-images.githubusercontent.com/1754002/99749194-3c9aaf80-2a9b-11eb-824e-bdfa29ba72d7.png)

**More details (please complete the following information):**
 - Codespace Instance Type: Linux
 - Client:  VS Code
 - Are you acessing Codespaces from a tablet, laptop, or deskop? Which one? Laptop
 
Brower-based editor details:
- Browser [e.g. chrome, safari]: Firefox
- Version [e.g. 22] 82.0.3

VS Code details:
- Version:
- Extension version:
- Channel: [Stable / Insiders]

Visual Studio details:
- Version: 
- Channel: [Release / Preview]

**Additional context**

**Comment by ibuildthecloud** [comment]
I ran into this issue setting up a codespace for github.com/rancher/k3os. I tried creating another workspace and it seems to never initialize.  If you have any ability to look at this instance, this codespace is the broken one https://ibuildthecloud-rancher-k3os-m5c6.github.dev/

**Comment by ibuildthecloud** [comment]
I ran strace against the process and I think you're stuck in an infinite loop traversing circular symlinks

```
[pid 14980] lstat("/var/lib/docker/vsonlinemount/workspace/k3os/images/30-bin/root/images/20-rootfs/root/images/30-bin/root/images/20-progs/root/images/30-bin/root/images/20-rootfs/root/images/30-bin/root/images/20-rootfs/root/images/20-progs/root/images/20-rootfs/root/images/20-progs/root/.git/packed-refs", {st_mode=S_IFREG|0644, st_size=3619, ...}) = 0[pid 14980] 
```

The directory `k3os/images/30-bin/root/` is a symlink to `..`

**Comment by jkeech** [comment]
Thanks for reporting! This is definitely not expected, and we're looking into it.

**Comment by jkeech** [comment]
@ibuildthecloud, we've identified the issue and are working on a fix. The code that is doing the repo scan is part of the automatic extension inference code which gets invoked if the repo does not provide a set of extensions to install via devcontainer.json. The bug fix is to alter that repo scan to not follow links, which will avoid the infinite recursion.

In the short term, you should be able to workaround this by adding a [devcontainer.json](https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/configuring-codespaces-for-your-project#creating-a-custom-codespace-configuration) to the repo with a non-empty `extensions` array.

**Comment by jkeech** [comment]
There were two places where this was happening:
1) In the Codespaces agent
2) In `oryx build`, which we use to automatically restore and build different types of projects if you do not specify a `postCreateCommand`.

The fix for (1) has just been rolled out. For (2), I filed microsoft/Oryx#882.

I'm going to close this out since the original issue with vsls-agent should now be fixed on new codespace creations. Please let us know if you continue to see issues!
