### ISSUE TITLE
Cloud codespaces unavailable

### ISSUE THREAD

**Issue by thbst16** [MicrosoftDocs/vscodespaces#840]
As of 11/24/20 @ 10 PM EST:

- Codespaces on US-EAST plan disappeared this evening
- New codespaces show as created but never load
- Can't create codespaces with same name in region with error "Cloud codespace already exists" even though there are no codespaces shown for account

**Comment by jkeech** [comment]
@thbst16, sorry you're having issues. Can you provide some more details such as subscription id or Codespace id(s)? Are you accessing from the web or desktop?

**Comment by thbst16** [comment]
- Accessing from the web
- Subscription: a96d1be0-8bbf-4b78-bf76-fe18462f59b8
- RG: vso-rg-49ad290
- No codespace ID's to provide -- they're all inaccessible / gone on web

**Comment by jkeech** [comment]
Thanks for the details. I've found the issue and am working on a permanent fix. I've made a small tweak to your profile which should work as a short term solution. Can you verify whether it's working now?

**Comment by thbst16** [comment]
**Did not work.** New spaces still stuck spinning after creation and I'm getting codespace name conflicts for spaces that aren't showing but were there yesterday.

**Comment by jkeech** [comment]
@thbst16, the quick fix I tried to make is not going to work unfortunately. I'm working on pushing out the permanent fix.

**Comment by thbst16** [comment]
Thanks @jkeech. Any sense on ETA?

**Comment by jkeech** [comment]
I'm running the change through some validations right now to make sure things look good. ETA 1 hour to get the change pushed to East US.

**Comment by thbst16** [comment]
Rocking. Please drop an update when the change hits and I'll give it a look from my end.

**Comment by jkeech** [comment]
@thbst16, the fix has been deployed to East US. Can you retry?

**Comment by thbst16** [comment]
Whatever you did definitely worked. Brought back my good Codespaces and the junk I was trying to create the last couple of hours, like the "asdfasdf" image.

Thanks so much for the hugely quick turnaround.

**Comment by jkeech** [comment]
Awesome, glad to hear it's working. I'm going to push the fix out to the rest of the regions now. Closing this issue, but please re-open or file a new one if you hit other issues. Thanks!
