### ISSUE TITLE
Getting billed even though I am not using CodeSpaces

### ISSUE THREAD

**Issue by callmekatootie** [MicrosoftDocs/vscodespaces#841]
**Describe the bug**
Hello, I have received invitation to use CodeSpaces and did use it as soon as I received the invite. I have not used it in the past month though.

Additionally, I was under the impression that during the beta period, CodeSpaces is free to use.

Yet, I have a line item in my Azure Invoice for Visual Studio Codespaces:

I contacted Azure support and they requested that I raise an issue here for you to look into it. The amount is minor - I am not worried about that, but I do see the same entry in the past couple of months too and I am sure that I have not used it for couple of months now.

**Expected behavior**
I should not be charged for CodeSpaces

**Screenshots**
The line item in my invoice indicating charges for Visual Studio CodeSpaces:

![image](https://user-images.githubusercontent.com/2317133/100598403-af6e1b00-3324-11eb-8799-ef73f43f3d7a.png)

**More details (please complete the following information):**
 - Codespace Instance Type: I do not recollect now, but I think I tested it out with Linux in the past
 - Client: I recollect using both the browser and VSCode
 - Are you acessing Codespaces from a tablet, laptop, or deskop? Which one?
Desktop only
 
Brower-based editor details:
- Browser [e.g. chrome, safari]: Google Chrome
- Version [e.g. 22] 87.0.4280.66 (Official Build) (64-bit)
I am pretty sure that I have updated Chrome in the past couple of months - at least after I had used CodeSpaces last.

VS Code details:
- Version: 1.51.1 Though I am certain that I have updated it since I last used CodeSpaces

**Additional context**
I am not sure what other information I can provide publicly but let me know if it is safe to share the invoice ID or something like that that you will find useful.

**Note** Before the Github CodeSpaces beta invitation, I was also using CodeSpaces through VSCode (I do not recollect how though and I do not see the previous documentation about it too - can only see the one about github codespaces). I imagine there's something leftover from it perhaps and I am getting billed for it? Either way, would like to know how I can stop getting billed for it (and yet not lose my beta invite)

**Comment by jkeech** [comment]
@callmekatootie, sorry for the confusion. There are two separate services: Visual Studio Codespaces, which is a public preview Azure service that is deprecated; and GitHub Codespaces, which is a GitHub feature that is in beta right now.

The Azure bill you are seeing is for Visual Studio Codespaces. There is a charge for Visual Studio Codespaces documented on the Azure pricing page, both for active usage and for inactive usage, where we keep the storage for your Codespaces around so that you can come back at any time and pick up where you left off. You can log in to https://online.visualstudio.com to delete in Codespaces that exist, which will stop billing for them.

GitHub Codespaces is free to use currently, and it is not associated in any way to your Azure subscriptions. Deleting your VS Codespaces plans/Codespaces will not have any impact on your ability to use GitHub Codespaces.

**Comment by callmekatootie** [comment]
Thank you @jkeech for pointing me in the right direction.

I logged in to https://online.visualstudio.com/ (which btw, redirects me to https://visualstudio.microsoft.com/services//github-codespaces/ the first time I visit, but the second time, mysteriously allows me to login!) and I find that I do not have any codespaces. Please see screenshot below:

![image](https://user-images.githubusercontent.com/2317133/100690476-9d37bf80-33ac-11eb-814d-789246e9dd58.png)

Despite this I am getting billed. Let me know what else I can check or do to prevent getting billed

**Comment by jkeech** [comment]
@callmekatootie, is your subscription shared with anyone else? If so, it’s possible they have Codespaces in a billing plan. The other way to delete the resources is to go to the Azure portal and look for any Visual Studio Codespaces billing plans. You can delete the billing plan resource from the resource group(s) which will delete the attached Codespaces and stop the billing. Let me know if that works.

**Comment by callmekatootie** [comment]
@jkeech No. I am the only user in my account.

I do see two resource groups on Azure Portal, but no resources under them. Just to be safe, I have deleted them. I'll let you know if I get billed again this month. Thank you for your assistance.

**Comment by jkeech** [comment]
If you share your subscription ID we can look on the backend and confirm whether the plans and Codespaces are deleted. I wouldn’t want you to get charged any more than expected if you aren’t going to use Visual Studio Codespaces anymore.

**Comment by callmekatootie** [comment]
Thank you. My subscription id is `574680fc-edf6-401a-a7a9-90a07a0149cc`

**Comment by jkeech** [comment]
@callmekatootie, do you happen to have the dates for the usage on your bill? The only Codespaces plan I see for that subscription was deleted on October 10, 2020, and all billing events stopped at that point. You should not see any Codespaces usage in your Azure bill after October 10.

**Comment by callmekatootie** [comment]
The billing period on the invoice is from 10th of October until 9th of November.

The amount is really small - so I can take this as a one off issue and get back to you next month if I still see the line item in my invoice perhaps?

**Comment by jkeech** [comment]
You could wait until next month and see. You could also try looking in the "Cost analysis" pane on the subscription resource and see if you see any usage for this month. It should look something like this:

![image](https://user-images.githubusercontent.com/746020/100701740-13103c80-3355-11eb-9745-421dd4ef9c93.png)

**Comment by callmekatootie** [comment]
Thank you. It says "No usage or purchases reported during this period" - so I am guessing I should not see any bills for this period. Will keep you posted.

**Comment by jkeech** [comment]
Sounds good. I'm going to go ahead and close this as resolved, but please feel free to re-open or file a new issue if you see unexpected usage on your next bill. Thanks for using Codespaces, and I hope you'll continue to use GitHub Codespaces in the future 👍.
