### ISSUE TITLE
All iconography is missing

### ISSUE THREAD

**Issue by savannahostrowski** [MicrosoftDocs/vscodespaces#846]
**Describe the bug**
I opened a new codespace and none of the icons populated.

**To Reproduce**
1. Create new codespace from scratch
2. See iconography is missing after codespace is done initializing

**Expected behavior**
To see icons

**Screenshots**
![image](https://user-images.githubusercontent.com/8949415/104062400-44c7bf00-51af-11eb-8200-cef585f6b4fe.png)

**More details (please complete the following information):**
 - Codespace Instance Type: Linux
 - Client: Browser-based
 - Which one? Desktop
 
Brower-based editor details:
- Browser [e.g. chrome, safari]: Chrome 
- Version [e.g. 22]: Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by jkeech** [comment]
@legomushroom to help investigate. Client-side browser console logs would probably be helpful for troubleshooting. Was this codespace in prod or dev/ppe?

**Comment by jkeech** [comment]
Hi @savannahostrowski! Thanks for reporting. This screenshot looks like GitHub Codespaces which is being supported on the GitHub Community site at https://github.community/c/code-to-cloud/codespaces-beta/45. Would you mind filing the issue there? cc @legomushroom

**Comment by savannahostrowski** [comment]
Sure thing!

**Comment by legomushroom** [comment]
Closing in favor of the community thread and as dup of https://github.com/microsoft/vssaas-planning/issues/1925
