### ISSUE TITLE
Cannot connect to a VSO Codespace: "Failed to start VS Code Remote server."

### ISSUE THREAD

**Issue by dbanisimov** [MicrosoftDocs/vscodespaces#848]
**Describe the bug**
Cannot connect to a Visual Studio Online Codespace. Online portal shows a blank screen with an error in the browser console: "Failed to start VS Code Remote server.". Connecting from VSCode gives the same result with the same error shown in the extension message.

The issue started approximately in the morning January 21st (PST time).

- Instance type: Standard (Linux): 4 cores, 8 GB RAM

- Browser: Win10 Edge
- Version: 88.0.705.49

VS Code details:
- Version: 1.53.0-insider
- Extension version: 1.0.3076
- Channel: Insiders

**Additional context**
- Region: WestUS2
- Environment: fc83d958-1007-4b57-a156-a8d0113368cd
- Subscription: c7f728b0-0fc8-4e71-95c2-3cf560346f8d

**Comment by jkeech** [comment]
Hi @dbanisimov, sorry you are having issues. We're investigating the problem that is preventing you from connecting to the codespace.

**Comment by jkeech** [comment]
@dbanisimov we've pushed out an update that will give us more detailed logs for this failure. Can you retry the connection and let us know after you've done so? It is likely to still give the error, but we'll have more insight into what is causing it to fail. Thanks!

**Comment by dbanisimov** [comment]
Hi @jkeech, thank you for looking into this! I've just retried the connection from the browser, logs are here:
[online.visualstudio.com-1611428969152.log](https://github.com/MicrosoftDocs/vscodespaces/files/5860895/online.visualstudio.com-1611428969152.log)

**Comment by jkeech** [comment]
Thanks @dbanisimov! We understand the issue and are working on the fix.

**Comment by jkeech** [comment]
@dbanisimov I've pushed a fix to West US 2. Can you retry and let us know how it goes?

**Comment by dbanisimov** [comment]
Just checked and the codespace works ask expected. I can successfully start, suspend and restart it both from the browser and from the vscode. Thank you @jkeech so much for the quick resolution!

**Comment by jkeech** [comment]
@dbanisimov glad to hear that it's working now and sorry again for the issues.

Friendly reminder in case you haven't seen it that Visual Studio Codespaces is shutting down on February 17 (less than one month away) as we are focusing only on GitHub Codespaces going forward. Please migrate your source code off of the codespace prior to February 17 to avoid any disruption or data loss. Thank you for being a Codespaces customer and we hope you'll consider switching to GitHub Codespaces! As an existing Codespaces user, we can help you get beta access to GitHub Codespaces if you'd like.

**Comment by dbanisimov** [comment]
Thanks for the reminder! I'm aware of the upcoming deprecation and has safely migrated the code. I'm on the GitHub Codespaces beta list, but unfortunately it doesn't support private org repositories yet. So I'm using the old Codespaces from time to time.
