### ISSUE TITLE
Having the option to reboot the github codespace

### ISSUE THREAD

**Issue by nimda95** [MicrosoftDocs/vscodespaces#850]
Hello Microsoft
Can you give the option to reboot github codespaces, I have blocked mine in an infinite loop.
Well, here it is.

**Comment by 2percentsilk** [comment]
Hi there! Thanks for this feedback but could you please file this at https://github.community/c/code-to-cloud/codespaces-beta/45?

This repo is for VS Codespaces and will be archived upon the service's approaching retirement.
