### ISSUE TITLE
The value of the setting "codespaces.accountProvider" changes "Uninitialized" automatically from "GitHub" after saving it

### ISSUE THREAD

**Issue by v-xinda** [MicrosoftDocs/vscodespaces#851]
**VS Codespace:** v1.0.3076

**VS Version:** 1.53.0 (user setup)
**Commit:** 8490d3dde47c57ba65ec40dd192d014fd2113496
**Date:** 2021-02-03T20:36:38.611Z
**Electron:** 11.2.1
**Chrome:** 87.0.4280.141
**Node.js:** 12.18.3
**V8:** 8.7.220.31-electron.0
**OS:** Windows_NT x64 10.0.19042

**Repro Steps:**
1. Make sure the VS Codespaces installed.
2. Open the Setting file --> Add the following setting --> Save it.
`"codespaces.accountProvider": "GitHub"`
3. Check whether save the setting successfully or not.

**Expect:**
Save the setting "codespaces.accountProvider" successfully.

**Actual:**
The value of the setting "codespaces.accountProvider" changes "Uninitialized" automatically from "GitHub" after saving it.
![image](https://user-images.githubusercontent.com/57662131/107138790-761fe000-6951-11eb-97b0-3363965fe51d.png)

**Comment by jkeech** [comment]
Hi @v-xinda, this extension is deprecated and will be removed from the marketplace in a few weeks when Visual Studio Codespaces is shut down. Please switch to the GitHub Codespaces extension for accessing your GitHub Codespaces. Thanks!
