### ISSUE TITLE
Question d’exten```json  { 	"messages": [ 		{ 			"type": 2, 			"message": "`menuBar/webNavigation` is not a valid menu identifier", 			"extensionId": { 				"value": "ms-vsonline.vsonline", 				"_lower": "ms-vsonline.vsonline" 			}, 			"extensionPointId": "menus" 		} 	], 	"activationTimes": { 		"codeLoadingTime": 196, 		"activateCallTime": 4, 		"activateResolvedTime": 1658, 		"activationReason": { 			"startup": true, 			"extensionId": { 				"value": "ms-vsonline.vsonline", 				"_lower": "ms-vsonline.vsonline" 			}, 			"activationEvent": "*" 		} 	}, 	"runtimeErrors": [] } ```sion

### ISSUE THREAD

**Issue by TheManInPink** [MicrosoftDocs/vscodespaces#855]
- Issue Type: `Bug`
- Extension Name: `vsonline`
- Extension Version: `1.0.3076`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

Question d’exten```json  { 	"messages": [ 		{ 			"type": 2, 			"message": "`menuBar/webNavigation` is not a valid menu identifier", 			"extensionId": { 				"value": "ms-vsonline.vsonline", 				"_lower": "ms-vsonline.vsonline" 			}, 			"extensionPointId": "menus" 		} 	], 	"activationTimes": { 		"codeLoadingTime": 196, 		"activateCallTime": 4, 		"activateResolvedTime": 1658, 		"activationReason": { 			"startup": true, 			"extensionId": { 				"value": "ms-vsonline.vsonline", 				"_lower": "ms-vsonline.vsonline" 			}, 			"activationEvent": "*" 		} 	}, 	"runtimeErrors": [] } ```sion

**Comment by 2percentsilk** [comment]
This extension has now been deprecated as the Visual Studio Codespaces service has been retired. Please uninstall the extension.

If you're interested in continuing to use Codespaces, we recommend you apply for the [GitHub Codespaces beta](https://github.com/features/codespaces).
