### ISSUE TITLE
Management portal layout is off in high resolution monitors.

### ISSUE THREAD

**Issue by srivatsn** [MicrosoftDocs/vscodespaces#92]
From an internal report:

In a monitor with 2560X1440 the management portal looks like this:

![res](https://user-images.githubusercontent.com/20570/68305635-e5c36300-005c-11ea-8c85-1e227065aae4.jpg)

**Comment by lostintangent** [comment]
Closing this, now that we're [transitioning Codespaces to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/).
